### ISSUE TITLE
Failed to play all video

### ISSUE THREAD

**Issue by zeppelin33** [cguZZman/plugin.googledrive#100]
As of today its not working at all for playing any video.

**Comment by KinjigMedia** [comment]
Same here, my .strm files are working only 5% of the time. Occasionally it will work. Unfortunately it is not reliable as of today.

**Comment by AlgusDark** [comment]
Same, I thought I was the only one with the trouble. I tried different things but failing all the time.

**Comment by EdgarCMl** [comment]
I have the same problem, i can't play my movies ☹️

**Comment by null2264** [comment]
I have the same problem, many of my movies/tv shows cant be played...

**Comment by gsantosoliver** [comment]
I am facing the same issue. It seems it is related to  #92 and it seems that @cguZZman is already working on it.

**Comment by cguZZman** [comment]
I'm working on this. Let's track the progress with #92

**Comment by cguZZman** [comment]
As a workaround, can somebody test if it works when selecting a different stream format? not the original.

**Comment by brunosaragiotto** [comment]
Work, but you can't change the audio or the subtitle.

**Comment by zeppelin33** [comment]
Yes works great for regular file streaming

**Comment by zeppelin33** [comment]
Thanks again cguzman

**Comment by JuenTingShie** [comment]
> 
> 
> Work, but you can't change the audio or the subtitle.

Same, even use original format.
Really need my subtitles
Test on raspbian buster kodi 18.5

**Comment by brunosaragiotto** [comment]
> > Work, but you can't change the audio or the subtitle.
> 
> Same, even use original format.
> Really need my subtitles
> Test on raspbian buster kodi 18.5

Already fix in the update
https://github.com/cguZZman/plugin.googledrive/issues/92#issuecomment-583819779
