### ISSUE TITLE
Do not load stored videos

### ISSUE THREAD

**Issue by fernankodi** [cguZZman/plugin.googledrive#101]
Greetings to all. I have Kodi installed along with the Google plugin, both updated, on different platforms (Windows 10, Android and libreelec) and I have never had problems when playing videos on mp4. However, for some time now, although it shows the files, it is not able to play any of them.

I would appreciate you studying the problem for resolution in future updates of the plugin.

To do this, I send you the corresponding log.

Thank you.

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4176943/kodi.log)

**Comment by gsantosoliver** [comment]
Check #92

**Comment by vaccarieli** [comment]
Thanks to the recent update the plugin is now working.

**Comment by fernankodi** [comment]
Thanks for the help.
