### ISSUE TITLE
External Subtitles displayed incorrectly in Kodi after latest updates on #92

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#102]
**Describe the bug**
The external subtitles are not displayed correctly after the fix on #92. Instead of displaying "Language (External)" it is displaying a random string.

**To Reproduce**
1. Upload a movie to Google Drive, name it movie.mkv 
2. Upload the movie's subtitles to the same directory as the movie on step 1 and name it "movie.LC-CC.srt" where LC = Language code and CC = Country Code
3. Export the folder as .strm fies
4. Make sure the Google Drive plugin is set to load subtitles files.
5. Play the movie
6. Go to the subtitles interface and check the subtitles availables. The subtitles uploaded on step 2 will be displayed under a random string instead of  "Language (External) " 

**Your debug log file**
Log - https://paste.kodi.tv/erivokerux.kodi

**Screenshots**
**Google Drive Files:**
![Screen Shot 2020-02-09 at 1 31 01 PM](https://user-images.githubusercontent.com/31668431/74105872-7750de00-4b40-11ea-828b-a426fdbf31c3.png)

**Kodi - Subtitles interface during movie playback**
![Screenshot_20200209-141618](https://user-images.githubusercontent.com/31668431/74105819-04476780-4b40-11ea-990f-9a22ebe4c6f8.png)

**Comment by cguZZman** [comment]
There is no fix for this issue with the new way google requires to download files. What you are seeing is the last part of the URL used to download your file, which Kodi takes as the filename. 
Fixed this issue before with a "download" service, which masks that URL with a "fake" one that ended with the real name, and in that way Kodi displayed the name correctly.
Now, this mask is not possible with the change in the api. The only solution I can think right now is if Kodi adds an option to also pass the name of a subtitle, apart from the URL.
So, for now, this will be the way it will be working.

**Comment by gsantosoliver** [comment]
Thanks for the explanation!

**Comment by DonghaoZ** [comment]
> 
**Is it possible to display the corresponding subtitles first?**

In my case, a season of episodes has 20 subtitles in just one folder, and I can't recognize them. So, if this plugin can at least sort the corresponding subtitles to the first one, kodi could display them automatically.

**Or set up a local server to forward all the requests**

I don't know how exactly this plugin works, but maybe use a request forwarder work like this: plugin://plugin.googledrive/file_id/file_name --> https://google.drive/file_id

![image](https://user-images.githubusercontent.com/130685099/234718207-e9bc1eff-7c16-4a36-9a7e-e187c768731f.png)

**Comment by DonghaoZ** [comment]
Successfully resolved the issue by displaying only the corresponding subtitles. Just modify `get_subtitle()` in `\resources\lib\provider\googledrive.py`
```Python
  def get_subtitles(self, parent, name, item_driveid=None, include_download_info=False):
      parameters = self.prepare_parameters()
      item_driveid = Utils.default(item_driveid, self._driveid)
      subtitles = []
      parameters['fields'] = 'files(' + self._get_field_parameters() + ')'
      parameters['q'] = 'name contains \'%s\'' % Utils.str(Utils.remove_extension(name)).replace("'","\\'")
      parameters['pageSize'] = 1000
      files = self.get('/files', parameters = parameters)
      for f in files['files']:
          subtitle = self._extract_item(f, include_download_info)
          if subtitle['name_extension'].lower() in ('srt','idx','sub','sbv','ass','ssa','smi'):
              # Add this line to compare file names
              if Utils.remove_extension(name) in subtitle['name']:
                  subtitles.append(subtitle)
      return subtitles
```
