### ISSUE TITLE
External Subtitles does not display

### ISSUE THREAD

**Issue by mikemorkodi** [cguZZman/plugin.googledrive#103]
Using KODI 18.6 with google drive 1.3.1

steps:
upload a movie to your drive and upload an srt file with the same name of the movie to the same drive directory.
load the movie using google drive add-on, normally the external subs should be picked automatically, but this is not the case here, and when i select them from the subs menu, they wont show,  
side note: subs within the mkv container are load automatically as expected  

 
attached log file:
https://paste.kodi.tv/olabipimix.kodi

attached - screen shot of the external subs that can be selected but does not presented.
![the first sub is the external one](https://user-images.githubusercontent.com/17107425/74128742-84c0a380-4be6-11ea-9655-97870843875a.png)

**Comment by mikemorkodi** [comment]
Please Note: 
1.it works just fine via strm files, but not direct from the addon.
2. I hope that this issue is not a duplicate since i already seen a similar bug that been opened,

**Comment by cguZZman** [comment]
Thanks for the report. Will take a look on it soon.

**Comment by ebs111** [comment]
@cguZZman simply check what link you get for the subtitle you will see that it's 127.0.0.1..., I explained where the problem is and what the fix could be and working

**Comment by cguZZman** [comment]
No localhost url is used to download subtitles. You are using and old version of the common module then.
@mikemorkodi please post your complete log file always so I can check everything faster without wasting time.
