### ISSUE TITLE
Subtitles not working in the new version

### ISSUE THREAD

**Issue by ebs111** [cguZZman/plugin.googledrive#104]
Since the new version is using the googleapi as the final play link and not the 127.0.0.1, all the subtitle method is wrong since the pattern that the player is chaking (local Host and port) is no longer valid , and simply adding the '?subtitle' to the link won't work.
So it needs to be revised , 
Thank you so much for this add-on , if you could please check that issue ,
Thanks

**Comment by gsantosoliver** [comment]
Take a look at #102

**Comment by cguZZman** [comment]
Source mode will be removed unless I find a solution, which seems very unlikely. The '?subtitle' link was intended for source mode only.

**Comment by ebs111** [comment]
ok, as source does not work but , in the player there is also a problem since it uses the "subtitles.append(DownloadServiceUtil.build_download_url" function which give the " 127.0.0.1" link to the subtitle , the correct way may be to use the "self._get_item_play_url(urllib.quote(Utils.str(subtitle['name'])), driveid, item_driveid, subtitle['id'])" instead.
i tested it and it works.

**Comment by gsantosoliver** [comment]
> ok, as source does not work but , in the player there is also a problem since it uses the "subtitles.append(DownloadServiceUtil.build_download_url" function which give the " 127.0.0.1" link to the subtitle , the correct way may be to use the "self._get_item_play_url(urllib.quote(Utils.str(subtitle['name'])), driveid, item_driveid, subtitle['id'])" instead.
> i tested it and it works.

@cguZZman - did you see this?

**Comment by gsantosoliver** [comment]
> Source mode will be removed unless I find a solution, which seems very unlikely. The '?subtitle' link was intended for source mode only.

@cguZZman - when (if) you remove the source - the external subtitles will still work even with the wrong names, won't they?

**Comment by cguZZman** [comment]
Apart from the source mode, subtitles are working as of now. That mentioned player code was part of the source mode subtitle assignment, so is not relevant. If your subtitles are not working, please log an issue with your debug log file.

**Comment by cguZZman** [comment]
I see #103 was logged. Let's continue the conversation there since it has the required info.
