### ISSUE TITLE
Custom thumbnails

### ISSUE THREAD

**Issue by fernankodi** [cguZZman/plugin.googledrive#106]
Dear authors of the plugin, could it be possible that in future updates of this addon they incorporated the possibility for the user to customize the thumbnails of his movie collection instead of the frame that Google places by default?

Thank you and congratulations for the great work.

**Comment by cguZZman** [comment]
Sounds like a good new feature, but with all the real life work and pending bugs, will be something at the bottom of the list. Thanks for the suggestion.

**Comment by boytempp** [comment]
I found that when I put picture file folder.jpg in the movie folder in export .strm, folder, the picture will shown as thumbnail in kodi movie.

**Comment by cguZZman** [comment]
The export function support local artwork now. 
Just put all your artwork and nfo in your drive, then export them and add them to your library. It will get your custom thumbnails and configuration from your nfo.
