### ISSUE TITLE
Show picture/thumbnail as movie folder by folder.jpg

### ISSUE THREAD

**Issue by boytempp** [cguZZman/plugin.googledrive#107]
As the feature of Kodi, it can show folder picture in each movie folder by naming the file as folder.jpg but for google drive, even I put the picture file in each folder as folder.jpg, the picture cannot show as folder picture.  Can you make this thing happen?  To export .strm for creating movie list is great but there are always many problem to make everything right.  Thank you so much for your effort.

**Comment by cguZZman** [comment]
The export function support local artwork now.
Just put all your artwork and nfo in your drive, then export them and add them to your library. It will get your custom thumbnails and configuration from your nfo.
