### ISSUE TITLE
Request: Please send the updated plugin to KODI repo.

### ISSUE THREAD

**Issue by Geranospiza** [cguZZman/plugin.googledrive#109]
Hello. My apologies for creating an "issue". It is not my intention to disturb the programmer.
I was wondering when was the programmer intending to release the updated plugin to the KODI repo. I have already installed it in my device without an issue thanks to the programmer's repo, but unfortunatelly not all of us know or are willing to learn how to add repo and stuff and rely on KODI to update it for them.

Thank you, and once more, my apologies for disturbing you.

**Comment by cguZZman** [comment]
Request to update the Kodi repo has been submitted.
Now we just need to wait until they merge it.
