### ISSUE TITLE
Videos no longer playing (was working till yesterday)

### ISSUE THREAD

**Issue by jumanji88** [cguZZman/plugin.googledrive#110]
**Describe the bug**
As of today, the videos are not playing off google drive using the add-on.
When one select's a video, the loading circle appears and then nothing happens.
Have tried multiple devices and complete uninstall and reinstall of KODI on all devices but the issue persists irrespective of video type

**To Reproduce**
~~v1.2.12~~ v1.3.2 installed from cguZZman add-on repo.
After installing the add-on through kodi add-on browser and adding the account to the add-on.
1. Go to Add-Ons
2. Select Google Drive
3. Select your own drive (whatever the name might be after you add your account)
4. Select My Drive
5. Select test folder (which I have created, or you could go to any video directly)
6. Select Video
Post this, the circle appears in the middle for a bit, then nothing happens and returns back to the file list screen. Momentarily I could see the file name on the top right but that disappears as well.

**Your debug log file**
https://paste.kodi.tv/obohekofub

**Screenshots**
PS: GIF was recorded after going into Google Drive add-on, right before selecting a test video file and before enabling the debug mode. I tried this with multiple other files but the result is exactly the same.
![Screen-Recording-2020-02-14-at-4](https://user-images.githubusercontent.com/17648924/74520825-54c71800-4ee6-11ea-901d-6af23ea7f2b4.gif)

**Comment by jumanji88** [comment]
**UPDATE:**
I had a hunch so checked something.
This issue seems to occur when one selects "original format" as a playback resolution. A processed video plays just fine if I select a lower resolution processed format like "640x360".

I am attaching a log, but I cannot attach the screen recording gif until the test video is processed by the google servers.

PS: I have a 1gbps wired internet connection, so bandwidth isn't an issue. I can stream 4k files/streams without a hiccup.

Log File:
In this case, I opened the google drive addon and went to the file. First I try to play the file by selecting "Original Format" which didn't work. Then I selected the same file as "640x360" and it worked.
https://paste.kodi.tv/zohejaqeke

**Comment by jumanji88** [comment]
Just realised the latest version is 1.3.2. Tested the issue with that, but it's still there.
I uninstalled Kodi, reinstalled it, added the repo manually and installed the latest version through that. Checked multiple videos but they won't play on the original resolution but will play a processed lower resolution.

New Log File
https://paste.kodi.tv/zarowupiwa

**Comment by SEYEM44** [comment]
Hello,

I'm having the same issue since yesterday. I've tried playing video from a mac and from my android phone, but in each case, the circle appears and nothing happen, then returns back to the file list screen.

I remove kodi from my mac and reinstall it but it is exactly the same.

**Comment by cguZZman** [comment]
Sounds like a google ban.
update the addon now. just uploaded a new version.
After that, go to your video file, display the context menu and select "Check for Google ban".
Send me  your debug log file and post your screenshot.

**Comment by cguZZman** [comment]
New version is 1.3.3 for the google addon and 1.2.10 for the common drive addon

**Comment by jumanji88** [comment]
> New version is 1.3.3 for the google addon and 1.2.10 for the common drive addon
Updated to 1.3.3 and tried again. Same issue. I tried even more files now with **Original Resolution,** some of them play properly, others not so much. Choosing a processed resolution works for all files.

Let me know if you want me to test in a certain way to help diagnose this.

Log File: https://paste.kodi.tv/zacasisosu

Screenshot of _Check_
<img width="1680" alt="Screen Shot 2020-02-14 at 12 06 03 PM" src="https://user-images.githubusercontent.com/17648924/74552251-cb820680-4f22-11ea-91e9-73fe4d75ecd0.png">

**Comment by cguZZman** [comment]
Your common cloud drive addon is not updated. I mentioned it for that reason.
Also no need to play the video for this test. The purpose is to check the reason for the failure.

**Comment by jumanji88** [comment]
> Your common cloud drive addon is not updated. I mentioned it for that reason.
> Also no need to play the video for this test. The purpose is to check the reason for the failure.

Ah. Thanks mate. It’s set on auto update, I thought it would’ve updated on its on. Anyway, Just updated the Cloud Drive Common Module to v1.2.10. I think that fixed the issue as the earlier file is playing now. 

I’ll test it out with more video files. If any more pop up, I’ll do a google ban check and post the debug log here if the check passes. Would that be alright? @cguZZman

**Comment by cguZZman** [comment]
That's fine.
Also I checked your debug log file and confirmed you had a ban from google:
```
{
 "error": {
  "errors": [
   {
	"domain": "global",
	"reason": "downloadQuotaExceeded",
	"message": "The download quota for this file has been exceeded."
   }
  ],
  "code": 403,
  "message": "The download quota for this file has been exceeded."
 }
}
```
But now the option will be there in case you want to check it again.
In case of a ban, you just need to wait until they remove your ban. No need to post it.
