### ISSUE TITLE
Google drive as source in kodi

### ISSUE THREAD

**Issue by elloboblanco69** [cguZZman/plugin.googledrive#111]
So, in Kodi, I used to be able to set google drive as a source, scan the drive with the movie database, and it would show all the nice movies with names, descriptions, etc, and be able to see them using Kodi's genre's and sorting options.  Now, it seems that Google has stopped that from being able to happen, or am I mistaken?  It still allows me to scan all the movies in but they will not play.  Is this something that you can fix or is it something to give up on?  Are there other options besides just playing the movie with the addon?  Is there a way to add a cover art for each of the movies, put them in the google drive, and have it show that?  I'm sure that you are working on it, but I'm just curious as I am a lowlife who uses this plugin and kodi quite a bit for watching movies...

**Comment by andreaziricardo** [comment]
I am also like this and apparently we have no answer, I believe there is no way

**Comment by jmiskinis** [comment]
Can confirm the same issue. Log output:
```
ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) [...]
WARNING: Process directory [...] does not exist - skipping scan.
```

**Comment by ekkoalex** [comment]
Hey have a look a #92,
