### ISSUE TITLE
Videos (google drive) not playing anymore just keep loading and close

### ISSUE THREAD

**Issue by dvasugit** [cguZZman/plugin.googledrive#113]
Hi,

From a week kodi - google drive, the videos not playing anymore and just keep loading and close.
Can see the files names and thumbnails everything just ok but videos not playing, how to fix the issue. 

Thanks,
vasu

**Comment by ajpozuelo** [comment]
I have the same problem.

**Comment by ekkoalex** [comment]
Hey Guys
Have you checked out #92 
Won't be able to use Gdrive via source anymore

**Comment by ajpozuelo** [comment]
Thank you Ekkoalex

**Comment by dvasugit** [comment]
I was followed below link, and now i can play videos on kodi - google drive,

https://github.com/cguZZman/repository.plugins

Thank you, cguZZman
