### ISSUE TITLE
The source mode did't work, then which mode we can use to watch movie in google drive

### ISSUE THREAD

**Issue by worldyouwyl** [cguZZman/plugin.googledrive#115]
Thanks for your help.

**Comment by Gustav0ar** [comment]
Yeah, I'm having the same issue. I can play videos fine if I browse in files, but if I add as source and try to play it, it just starts to loading and quits (basically nothing happens).

**Comment by cguZZman** [comment]
You can play your videos by browsing your folders within the addon. Or you can export your videos to .strm files and add them to your library.
