### ISSUE TITLE
playing movie from googledrive, I can't play .iso file both in windows 10 and android box. 

### ISSUE THREAD

**Issue by boytempp** [cguZZman/plugin.googledrive#118]
**Describe the bug**
playing movie from googledrive, I can't play .iso file both in windows 10 and android box but it is playable for same files of .iso in USB flash or Hard drive.  I have tried both .strm file and directly to google drive, they produce the same error.  (as tested, black screen with sound for DVD ISO and black tiny mosaic picture in Bluray ISO)

Kodi Leia

**To Reproduce**
1. Go to .iso file in google drive
2. Click on play
3. black screen ( no error pop up)

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4265266/kodi.log)

**Screenshots**
![bluray iso](https://user-images.githubusercontent.com/60927080/75510893-fe49f580-5a1e-11ea-8ad9-668a72353f8e.JPG)
![Capture 1](https://user-images.githubusercontent.com/60927080/75510897-ff7b2280-5a1e-11ea-81c1-1769fab53e3d.JPG)

**Comment by cguZZman** [comment]
your log file does not have debug information. 
turn on debug mode first and then try again.

**Comment by boytempp** [comment]
Here is my log file in debug mode.  Thks for your help.

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4274952/kodi.log)

**Comment by cguZZman** [comment]
Accordingly with your debug log file, Kodi is getting errors decoding your video. I know you have tested it in a local file, but this is more like a Kodi issue. The addon just pass the URL of your file (from google servers) to Kodi so it can be played.
I just made a test with the iso from here: http://www.deniscarl.com/dvdtest (uploaded to my google drive) and it played just fine.
You could test changing the encoding of your iso file or report the issue to Kodi team.
