### ISSUE TITLE
HTTP returned error 503

### ISSUE THREAD

**Issue by g0kuz** [cguZZman/plugin.googledrive#121]
1. Using strm
2. Original Quality
3. Playback starts with bad stuttering and eventually stops after a few seconds.

Since the latest version has google ban feature, I thought it was the problem but when I check, its not. It happens to **ALL** of my files.

However upon investigating, it only happens on my **main** teamdrive. Other secondary teamdrives are not affected by 503. May I know why does this happen. I can download from my **main** teamdrive no problems, just streaming from kodi is giving this issue.

![image](https://user-images.githubusercontent.com/45234964/76059171-230f1180-5fb9-11ea-9bdc-49936809b6d3.png)

![image](https://user-images.githubusercontent.com/45234964/76059155-1b4f6d00-5fb9-11ea-87bc-372745f4645d.png)

**Comment by g0kuz** [comment]
![image](https://user-images.githubusercontent.com/45234964/76062285-5d2fe180-5fc0-11ea-98c7-3d40f85dc519.png)

Now it shows 403.

**Comment by cguZZman** [comment]
Paste always your entire debug file. Not stripped/cut/shorten. Must have debug mode activated.

**Comment by g0kuz** [comment]
I lost the file since it was overwritten. But what does 503 mean? It should be a generic error no?

**Comment by g0kuz** [comment]
[HTTP returned error 503.log](https://github.com/cguZZman/plugin.googledrive/files/4301650/HTTP.returned.error.503.log)
[HTTP returned error 401.log](https://github.com/cguZZman/plugin.googledrive/files/4301651/HTTP.returned.error.401.log)

Here you go @cguZZman 

What is the issue here?

**Comment by cguZZman** [comment]
Your log is stripped or incomplete and does not include debug statements.
https://kodi.wiki/view/Log_file/Easy
Make sure you read the log instructions carefully

**Comment by g0kuz** [comment]
@cguZZman after researching for awhile I got to know the problem. 

After each cache is done, after some time google stops sending packets as it believes KODI has closed the stream. For example if I have memorysize=150MB. Once, I reach 150MB or so KODI will make an attempt to split the files and continue. But this won't work everytime for google since its very picky about this. 

Therefore I ask if you can add a proxy so google continue streaming and think its still streaming. 
E.g. GOOGLE>PROXY>KODI

My current solution is <memorysize>0</memorysize> where it will continue streaming the whole video file. This is just a temporary solution and a proxy will be the end game. Hope you implement it.

**Comment by cguZZman** [comment]
A proxy it's way out of the intended scope of the addon. I would suggest you to create an issue with the kodi team to see if they can fix it in any way.

**Comment by g0kuz** [comment]
> A proxy is way out of the intended scope of the addon.

TBH, its for stability, its indeed in the scope as its only google having this problem. No other streaming ways of KODI like smb/ftp/web has this issue. Only google.
