### ISSUE TITLE
Multiple tracks in video stream can not be select when modifies the original stream quality

### ISSUE THREAD

**Issue by sergiocortina** [cguZZman/plugin.googledrive#122]
**Describe the bug**

Hi. I have an mkv movie with multiple audio streams. When i play in the original quality, i can switch the audio language. but when i hace a slow connection and modify the stream quality from original to 720, kody play the video but yo can not select the audio stream. it only appears when you play in original quality. 
**To Reproduce**
1. Go to google addon
2. Click on setup or configuration
3. Default stream quality has to be in original in order to can select the audio stream
4. when you put 720 for example, and play the video, you can not select the audio stream

i trie under settings assign a default audio stream, but doesnt work

how can i down the quality stream and select de audio stream that i want?

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/61883341/76112013-010c9380-5fa7-11ea-91a4-eda05b7cb334.png)

**Comment by cguZZman** [comment]
This is the same as #69. Please read that issue for the explanation.

**Comment by sergiocortina** [comment]
thanks!
