### ISSUE TITLE
Resume feature causes "CDVDVideoCodecAndroidMediaCodec" on VC1 files. Plays back perfectly without resume.

### ISSUE THREAD

**Issue by g0kuz** [cguZZman/plugin.googledrive#123]
**Describe the bug**
Resume doesn't play VC1 files and crashes kodi. 

Disabling both hardware acceleration(MediaCodec & surface) prevent the crash. So, the resume feature is doing something to the codec to seek?. 

**To Reproduce**

1. Use any Nvidia Shield TV
2. Play any VC1 codec file
3. Playing VC1 works perfectly without resume feature
4. Play the file once and stop to initiate resume point
5. Try playing it again, crash.

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4301772/kodi.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/45234964/76143048-8f1f7180-60ae-11ea-8fe5-caba0aab1189.png)

**Comment by cguZZman** [comment]
Same here, no debug log found.

**Comment by cguZZman** [comment]
As comented before, your debug log file does contains debug information. If you are still having  this issue, please upload the file again in debug mode.
Will reopen this issue once it's provided.
