### ISSUE TITLE
Unknown Error: nfo_export

### ISSUE THREAD

**Issue by null2264** [cguZZman/plugin.googledrive#124]
**Describe the bug**
"Unknown Error:
nfo_export
Please try again"
I dont know what that is

**To Reproduce**
All i did is pressed run export

**Debug Log File**
https://pastebin.com/PApw7MNJ

**Screenshots**
![03-09-20 16:24:43 1366x768 Zi](https://user-images.githubusercontent.com/46041660/76199545-a54e3e80-6222-11ea-8aa4-b7cacf0440c3.png)

**Comment by gsantosoliver** [comment]
@cguZZman - I am facing exactly the same issue on all my devices running Kodi. I can play the movies correctly, either by navigating to them using the plugins explorer or using the existent .strm files.

My debug  https://paste.kodi.tv/afuzanolew.kodi

**Comment by xybydy** [comment]
It seems you two have outdated clouddrive module. Can you pass the versions of both gdrive plugin and clouddrive

**Comment by ferranclotet** [comment]
I have the same Issue. The solution is to activate "Create info files" in the folder export menu. Now it works but it takes so long to explore the folders, much more than before.

**Comment by cguZZman** [comment]
Fixed in Cloud Drive Common Module 1.2.13

**Comment by gsantosoliver** [comment]
> Fixed in Cloud Drive Common Module 1.2.13

wow - wait a minute: where do I get the 1.2.13 since the latest available at yours or Kodi's repos is 1.2.12?

**Comment by cguZZman** [comment]
From my repo. Give it another try.

**Comment by gsantosoliver** [comment]
> From my repo. Give it another try.

I've just done it and it is all the same as before. :(

**Comment by cguZZman** [comment]
Kind of weird. Just tested it in other devices and new version is showing up. If you can, try one more time.

**Comment by gsantosoliver** [comment]
> Kind of weird. Just tested it in other devices and new version is showing up. If you can, try one more time.

Nothing yet. I get the same 1.2.12 vesion. Is there anything I can do to force the new version install?

**Comment by cguZZman** [comment]
Uninstall it (without removing configurations) and install it again from my repository. The dependency in google drive addon is set to 1.2.12, but you should get the new version anyway.

**Comment by gsantosoliver** [comment]
Check this out - here is says 1.2.12:
![Screenshot_20200310-101544](https://user-images.githubusercontent.com/31668431/76321210-78506900-62c0-11ea-81fd-c2abfc7209fd.jpg)

When I click on it says 1.2.13:
![Screenshot_20200310-101548](https://user-images.githubusercontent.com/31668431/76321254-87371b80-62c0-11ea-9415-d0b4d425d6a7.jpg)

I think the first screen is kind of misleading. 

I tried yesterday and noticed that the export is working but it is way slower than before. Sometimes it gives me an error saying my account doesn't have access anymore and it stops the export in the middle (boomer). I will run it again today and will report a new issue if it happens again. 

Thanks.
