### ISSUE TITLE
.strm export has been too slow after the update - it errors and does not complete

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#125]
**Describe the bug**
The .strm export has been too slow. It issues an issue in the middle of the process and does not complete. 

**To Reproduce**
1. Start a .strm export with at least 1500 movies (in their respective folder) in the export.

**Your debug log file**
First 4000 lines: https://paste.kodi.tv/sapofemola.kodi
Next 4000 lines: https://paste.kodi.tv/urodidapof.kodi
Remaning lines: https://paste.kodi.tv/eniyigoday.kodi 

**Screenshots**
Error message that appears in the middle of the .strm export process
![Screenshot_20200312-154951](https://user-images.githubusercontent.com/31668431/76560538-1c344300-6480-11ea-8615-d33f3e5e2e6b.jpg)

**Comment by cguZZman** [comment]
I'm not able to determine the cause of your slowness. Your log file shows some network issues and also your device is taking too long to process the files. But not conclusive.
So I added some extra logging in the addon to help determine the problem. If you can test it again and report back, will be awesome.
About the credentials being invalid, it's a bug. And it's fixed and published now in the new version.

**Comment by cguZZman** [comment]
The extra logging is in the new version, so please update your addon before testing again.

**Comment by gsantosoliver** [comment]
hi @cguZZman - I have done what you said and, at the same time, played a movie. The process finalized. I think that the problem may have been associated with my device going to stand by/sleep during the export. 

Is there a way to make the export process to function just like when a movie plays by preventing the device to go to sleep?

**Comment by cguZZman** [comment]
I have not seen an option to do that from the addon. Put your screen saver to "Dim" and that should prevent your device going to sleep.
