### ISSUE TITLE
tip for source

### ISSUE THREAD

**Issue by azx0021** [cguZZman/plugin.googledrive#127]
Can't use the same strm URL when opening the source? for example when opening the movie through the source, play the strm plugin: // ..... So you wouldn't have to keep doing strms and update everything yourself

**Comment by cguZZman** [comment]
that was the first idea, unfortunately, Kodi only accepts a list of files where the url is the same as the file name. So it's not possible to have a file name "movie.mkv" with the href "plugin://..."
