### ISSUE TITLE
.strm files not automatically generated for "Added to Drive" files

### ISSUE THREAD

**Issue by cboswald95** [cguZZman/plugin.googledrive#129]
I get perfect .strm generation with shared drive folders that've been set to watch for changes, but for folders in the "My Drive" section of google drive that've been added to my drive ([like this](https://www.digitalchaoscontrol.com/wp-content/uploads/2016/10/AddtoMyDrive.jpg)), I get incomplete .strm file generation.

**Comment by cguZZman** [comment]
Don't skip all the required information when creating an issue. It's there because is needed if you want me to validate it.
Create a new issue with required information and only try to export the folder where you are not getting strm files from.
