### ISSUE TITLE
Check for Google ban not detecting downloadQuotaExceeded ban

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#131]
**Describe the bug**
I am not able to play movies. When I click on a movie it takes some time and seems that it will play but then it does not. I checked I can't play the movies on the library (I use .strm exports) nor play the movie navigating to it using the Google Drive add-on's file navigator. I also checked if I am banned and I am not (using the check Google ban feature in the add-on). I am also able to download the same movie from Google Drive using a browser in my computer.

**To Reproduce**
Select a movie, either in the library or navigating to the folder using the Google Drive add-on and try to play it

**Your debug log file**
https://paste.kodi.tv/okekehuxel.kodi

**Comment by cguZZman** [comment]
Weid, because you log file is saying you have a ban from google. 
Will mark this as a bug for the ban check feature.

**Comment by gsantosoliver** [comment]
Hi - I am able to play movies again - but at the time of the problem the check for ban reported that it was ok. I took a screenshot and will post later.

**Comment by wuyuankai** [comment]
I have exactly the same issue,  sometimes it’s not playing but after a while it can play again

**Comment by cguZZman** [comment]
fixed in last version
