### ISSUE TITLE
.strm file is not being made

### ISSUE THREAD

**Issue by medudder** [cguZZman/plugin.googledrive#136]
**Describe the bug**
After scanning google drive folder, 90% of the extensions are  xxxx.mkv.strm  however the other 10% are ".mkv"
Solution, if ".strm" is added to the file  names, then kodi could play the video.

This is clearly a bug.  Please help.  Thx
**To Reproduce**
1. scan your google drive files to produce the "strm" files
2. go to the folder on your device where the .strm files are stored.
3. there you will see that there are several with .mkv as the extension  (instead of strm)

**Comment by chivigoku** [comment]
Same problem here. Some friends have the same behavior.
Looking forward to fix this bug

Thanks in advance

**Comment by medudder** [comment]
Glad to hear I'm not the only one.
Hope someone could fix it.

**Comment by enanno** [comment]
Same here in 3 different devices (Windows, Android 8 and Android TV 8) with Kodi 18.6 and last version of the addon.

**Comment by medudder** [comment]
I tested on 3 devices as well.
2 Nvidia shield TV
1 pc.
Unfortunately, same result.  :(

**Comment by vankdj** [comment]
Yes, some friends and I are the same.  We did not find a solution ... We have done a clean installation and we get the same result

**Comment by medudder** [comment]
if there isn't a solution i might have to look for an alternative media center..... perhaps emby?

**Comment by cguZZman** [comment]
This has been resolved. See #139.

Code fix was merged with version 1.3.6 for the google addon and 1.2.15 for the common drive module.
Will send it to kodi repository soon. It's available in my repository now.

**Comment by medudder** [comment]
Thank you SO MUCH!!!!
Is there any tutorial on how to update the addons on Android?

Thanks again!!
