### ISSUE TITLE
Defunct "Cancel" button in quality selection window

### ISSUE THREAD

**Issue by jmiskinis** [cguZZman/plugin.googledrive#138]
**Describe the bug**
"Cancel" button in quality selection window should permanently close the window. Instead, the window is closed and then reopened again.

**To Reproduce**
1. Select a video file (imported from Google Drive) in media library and play it.
2. In the quality selection window, click "Cancel".

**Screenshots**
https://youtu.be/fcLa7EVyvzo

**Comment by cguZZman** [comment]
Thanks for the report. Will try to fix it soon.

**Comment by jmiskinis** [comment]
Thank you for developing and maintaining this addon. It's been the only reasonable alternative after Plex Cloud service was discontinued. Please consider registering for https://www.buymeacoffee.com/ or something similar, so we can show our support for this endeavor :)

**Comment by cguZZman** [comment]
fixed in last version
