### ISSUE TITLE
movies are getting duplicated

### ISSUE THREAD

**Issue by plafilmes** [cguZZman/plugin.googledrive#141]
I have a problem with duplicate movies, every new update adds the same movie more than once.

how to solve?

**Comment by klyco** [comment]
Check t see if it is creating duplicate .mkv.strm files or .mkvfiles (substitute your file type for MKV)

**Comment by plafilmes** [comment]
> Check t see if it is creating duplicate .mkv.strm files or .mkvfiles (substitute your file type for MKV)

duplicating some .mp4 and .mkv files

**Comment by klyco** [comment]
Ah, different than my issue - it replaces mine.  Upload a debug log.

**Comment by cguZZman** [comment]
Upload a debug log file and explain all the details as requested when creating this issue. 
Will reopen this issue when all required information is provided.
