### ISSUE TITLE
Streaming on different resolution audio and sub wouldn't switch

### ISSUE THREAD

**Issue by vaccarieli** [cguZZman/plugin.googledrive#144]
Whenever there is a slow connection i toggle on the option to allow kodi to change the resolution streaming but when i do it, it won't allow me to switch either the audio or subs, it only takes the primary by default, it only will on the original resolution, is there a way or a work around on this ?

**Comment by hackmonker** [comment]
If it is not the original quality I dont think you can change audio. It selects the default audio

**Comment by cguZZman** [comment]
@hackmonker is correct.
