### ISSUE TITLE
Can't Add GoogleDrive Movies to library

### ISSUE THREAD

**Issue by HelmyBD2** [cguZZman/plugin.googledrive#145]
Dears,
Sorry, but I am new to Kodi, and I am having a silly problem. I successfully added my google drive to Kodi, and I can play movies without a problem.

The issue is that my movies don't show up on the "movies" tab of Kodi (i.e., library)

I tried to add source, but I am not sure how to add Google drive as the source to update the library from.
Best regards,

**Comment by ryanjerskine** [comment]
I don’t believe source mode works anymore. You should export the folder(s) to strm files and then add those strm files to you library.

**Comment by cguZZman** [comment]
Please do as @ryanjerskine says. Source mode won't work in the near future.
