### ISSUE TITLE
Can't Login my google account

### ISSUE THREAD

**Issue by hackmonker** [cguZZman/plugin.googledrive#146]
Whenever I try to add my account, It says error 404 or your ip address has changed. This problem was not there earlier. Any Solutions?

Log - https://pastebin.com/raw/HRPEfJuh

Kodi Version - 18.6

**Comment by cguZZman** [comment]
As the addon says, your public ip changes constantly. This is a security issue for the addon.
Please use another network or provider that does not change your ip constantly.
Or try to add your account faster before the next change of ip happens.
