### ISSUE TITLE
folder monitoring creates .mkv files, not .mkv.strm. This causes Kodi to not play the files

### ISSUE THREAD

**Issue by klyco** [cguZZman/plugin.googledrive#151]
**We had this issue previously and @xybydy was able to fix some of it.  I have the latest fixes installed, but the issue has re-appeared.

Describe the bug

It seems that my Google Drive is creating the files while monitoring my videos folder, however, when it creates the files, it creates a videoname.mkv file, not videoname.mkv.strm file.

This causes an issue for Kodi when I try to play the file from the Library, as it is expecting an MKV file.
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4596110/kodi.log)

 I have captured a log with the same issue happening.
./videos/TvShows/Chopped (2009)/Season 45/S45E20 Beat the Judge Amanda.mkv
./videos/TvShows/Chopped (2009)/Season 45/S45E19 Beat the Judge Tiffani.mkv
When the files were renamed and moved to a new folder (moved from Season 46 to Season 45) in my Google drive, they were recreated as .mkv on my Kodi device, using the google drive add-on.

Thanks!

**Comment by jaylex32** [comment]
> @klyco The log shows this happening under v.1.3.4 of the plugin. Is this still happening after v.1.3.6 as this seems like a duplicate of issue #139 which was fixed in that version.
this is happening in the latest Gdrive addon version out in kodi repo.

**Comment by rodneyshupe** [comment]
> > this is happening in the latest Gdrive addon version out in kodi repo.

@jaylex32 I don't think the Kodi repository has the latest version.  Can you check?

You might want to add @cguZZman 's [repository](https://github.com/cguZZman/repository.plugins)

**Comment by jaylex32** [comment]
> > > this is happening in the latest Gdrive addon version out in kodi repo.
> 
> @jaylex32 I don't think the Kodi repository has the latest version. Can you check?
> 
> You might want to add @cguZZman 's [repository](https://github.com/cguZZman/repository.plugins)

yes the version in Kodi is 1.3.4 which is not the latest, everything is working good now so far, is there a way to update the Kodi version or send a update request to Kodi?

**Comment by cguZZman** [comment]
I'll try to submit next week. But keep my repo installed to always get the latest version.
