### ISSUE TITLE
Not verified

### ISSUE THREAD

**Issue by AllviewTV** [cguZZman/plugin.googledrive#16]
Every time I try to log in I get an error on my web browser saying 'login not verified by google' any ideas how to fix this?

**Comment by cguZZman** [comment]
Click the "Advanced" link, then click in the "Go to xxxxxx.com", type "continue" then click "Next" and you can continue with the authorization.

I'll be working on the issue soon so the app can be verified.

**Comment by Zvezke** [comment]
Oh, I was just about to create a new issue about the lacking 'Advanced' option, but the issue seems to have been noticed already. I hope this will be fixed eventually.

**Comment by cguZZman** [comment]
Hi everybody. Good news: The addon has been verified by google.
You can start adding accounts again and without the warning message.
