### ISSUE TITLE
Drive Shortcuts can't be played

### ISSUE THREAD

**Issue by algoldbe** [cguZZman/plugin.googledrive#163]
**Describe the bug**
Drive Shortcuts can't be played. If you have a folder with shortcuts from shared files or from other folder, they can't be played with the addon.

**To Reproduce**
Try playing a video that is a shurtcut.

Thanks!

**Comment by alazabe** [comment]
Just check the export folder where the plugin export .strm to the files might be deleted !

Are you running Win 10 and 1.3.6 plugin ?

I think we might have the same problem !

**Comment by cguZZman** [comment]
Was an error displayed? Your debug log file is required. That is why is requested when you are creating this issue. Please update your post with your debug log file and the issue will be reopened.
