### ISSUE TITLE
adding extention for file format

### ISSUE THREAD

**Issue by Sphinxroot** [cguZZman/plugin.googledrive#164]
hi .. i want to know if its possible to add other extention file in the addon  ,like epub pdf mobi ext  so whit the plugin ebook reader on kodi  it will read them ? if you need more information  ping me in my git il  put the code in if you wanna try  thanks :)

**Comment by cguZZman** [comment]
can you elaborate? where the extensions should be added and which plugin

**Comment by Sphinxroot** [comment]
yes i got a ebook reader in kodi that open epub pdf and mobi  .. it would be cool if the plugin see those file on and 1click it should open the ebook plugin  for now i only see my pic and video files .

**Comment by Sphinxroot** [comment]
https://github.com/Sphinxroot/script.ebooks if you want to try :)

**Comment by cguZZman** [comment]
it wont work since that plugin reads ebooks directly from filesystem. 
the google drive addon gives a http url to kodi with respective account credentials and kodi make all downloading and playing.
your plugin should do something similar in order to start to be compatible.
