### ISSUE TITLE
Manual run of .strm export starts from scratch instead of only exporting the missing or new .strm files

### ISSUE THREAD

**Issue by silenceofthewans** [cguZZman/plugin.googledrive#165]
**Describe the bug**
Basically if you export a gdrive folder to .strm and tick the options 'watch for changes' and 'update library after export' it will work as expected the first time and from then on. But if you manually go and run export of that folder because you think there might be some files that the export task missed it will start the export process from scratch instead of only adding the missing files. Also if I want to clone the setup to another device copying the strms will play all the library files fine but won't export new gdrive files of the folder that was exported in kodi even if the option 'watch for changes' is checked. For that to happen you have to run the export process on that system (and on each new one) and from then on it will add new gdrive files of that exported folder but this makes the copying of strms useless.

**Comment by 4luk** [comment]
Same kinda issue :( When I add a movie in a folder to the watched folder (watched folder is "movies") (google/movies/big buck bunny 2010/big buck bunny 2010.mkv) it creates a folder but no strm file inside, but when a mkv file is uploaded straight to the watched movie folder (google/movies/big buck bunny 2010.mkv) it creates a strm file for the movie.
This is a fresh install with kodi 18.7 windows 10 x64 and Android
Your app version 1.3.6
Using team drive

The only work around I found was to set schedule automatic export for every few hours. But not sure how many times you can do it through the day before api ban?

**Comment by alazabe** [comment]
I hope the Dev answer this , its really important

**Comment by jaylex32** [comment]
yes this is a issue and also when I have the watched folder option on it exports certain movies wrong without the .strm and only for example .mkv and it wont play and it leaves duplicate covers of movies that dont work.

**Comment by cguZZman** [comment]
There is a "change_token" stored for your account in accounts.cfg. You need that token in order to request next changes. So, you should clone that file also.
The export function will always export everything. There is no other way to ensure all files are exported if you think something is missing. 
The addon uses the mentioned change token to track the changes. That tracking protocol is provided by Google. So, if you think that something is missing even with the tracker, the addon has no other way to know.
