### ISSUE TITLE
Movies stored in Google photo do not appear

### ISSUE THREAD

**Issue by Shenzi13** [cguZZman/plugin.googledrive#166]
Hi evzrybody !

I'm intending to use a Google photo account to store all my légal movies downloaded from torrent...

And so I Wonder if kodi could access thèse movies... 

On Google photo they do appear and are not increasing the 15gb of the drive... It's possible to play the movies even... Good.

But in kodi Google drive addon I can't access them... I just managed to read a movie from Google drive...good... But ! so the limit is only 15gb and not unlimited like Google photo...!

Any solutions ?...

To read a movie stored on google photo with kodi ?

Thanks a lot hope it will help other if find out

**Comment by Shenzi13** [comment]
Answering to myself. It apmears to be waiting for à fix for more than 1 year since Google drive and Google photo separate in 2019 july.

So sad =(

Hope for the release and thank for all

**Comment by cguZZman** [comment]
that was fixed some months ago. make sure you have the latest version from my repository
