### ISSUE TITLE
Add to Offline

### ISSUE THREAD

**Issue by VIJAYzKUMAR** [cguZZman/plugin.googledrive#167]
It would be nice if there was an option to download/offline a video from drive and store it in a place visible only to Kodi and since we can add Kodi as source if any video is downloaded is part of a TV Show it will be replaced by the Downloaded video from strm link untill it's deleted

**Comment by tonymayo** [comment]
is it working for you? for me is down.

**Comment by tonymayo** [comment]
> It would be nice if there was an option to download/offline a video from drive and store it in a place visible only to Kodi and since we can add Kodi as source if any video is downloaded is part of a TV Show it will be replaced by the Downloaded video from strm link untill it's deleted

is it working for you? for me is down.

**Comment by VIJAYzKUMAR** [comment]
> is it working for you? for me is down.
It sure is just checked!

**Comment by cguZZman** [comment]
same as https://github.com/cguZZman/plugin.googledrive/issues/27.
