### ISSUE TITLE
Make the plugin export strm that work with any media player 

### ISSUE THREAD

**Issue by alazabe** [cguZZman/plugin.googledrive#169]
**Is your feature request related to a problem? Please describe.**
The kodi add on export strm with “plugin://“

**Describe the solution you'd like**
Export Strm that can work with any media player

**Comment by olympus123** [comment]
Impossible.

**Comment by alazabe** [comment]
> Impossible.

I dont think its impossible since its python based !

**Comment by olympus123** [comment]
I don't think it's possible for a Kodi addon, Kodi can call python itself, other players can't.
It could be technically possible but this isn't a feature request for this add-on, it's like asking the developer to start a whole new project.

**Comment by alazabe** [comment]
> I don't think it's possible for a Kodi addon, Kodi can call python itself, other players can't.
> This add-on basically gives "instructions" to Kodi about how to call python for getting a playable link.
> It could be technically possible but this isn't a feature request for this add-on, it's like asking the developer to start a whole new project.

No i didnt ask for new project just change the URL so other players can play it 
ISince the URL start with "Plugin://" no other player will play it

**Comment by olympus123** [comment]
plugin:// is not a real protocol like http://. It's not a real url. It's a "fake" protocol for kodi so that it can understand what to do. Kodi uses other "protocols" too, like special://. What you are asking is not possible for a kodi addon. It a different project.

**Comment by jaylex32** [comment]
> plugin:// is not a real protocol like http://. It's not a real URL.
> It's a "fake" protocol for kodi so that it can understand what to do.
> Kodi uses other "protocols" too, like special://, like library://, like videodb://.
> That doesn't mean that all these are real URLs and can be turned to http URL links.
> What you are asking is not possible for a kodi addon.
> It's a different project.

are you the dev of this?
 because this is something that the dev should answer not some random guy and if you are one of the dev then you should consider it because it would be cool to use this feature in other players or servers like Emby.

**Comment by Sphinxroot** [comment]
only cue for this .. if the main objectif is to add .strm file into kodi library not in google drive itself  is to build your own installer package that point to Userdata folder path for the appropriate device .. other than this ,the plugin dont have the upload feature implemented and does`nt read all the file on the gdrive .  other than media file  .. for now you have to add manualy your strm file via a web interface

**Comment by cguZZman** [comment]
thanks @olympus123 for the perfect explanation.
