### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by Falklan** [cguZZman/plugin.googledrive#17]
Is there feature that will allow me to change user accounts?

**Comment by cguZZman** [comment]
I'm not sure I'm following you. 
You can add another account and then delete the previous one. There is no automatic replacement if that's what you want to do.

**Comment by Falklan** [comment]
"Multiple Users" means exactly that. Once an account is added, I have no idea how to add a different account. I don't see any options for this.

**Comment by cguZZman** [comment]
Just select "Add an account..." again. It's always there with the list of accounts.

**Comment by Falklan** [comment]
There is no option to Add an Account... This is what I'm telling you........ 
![kodi - gdrive options](https://user-images.githubusercontent.com/9254619/41503987-1501ebe6-71a7-11e8-9733-920968426dce.png)

**Comment by Falklan** [comment]
I had to wipe my addons to get this to function again. Now it showed the Add Account options. GD...
