### ISSUE TITLE
Movies in folder don't create .Strm

### ISSUE THREAD

**Issue by 4luk** [cguZZman/plugin.googledrive#170]
Tested on windows 10 and ubuntu 20.04
Kodi 18.7
Your google drive addon v1.3.6
My folder structure on computers.
/home/user/desktop/media /Movies/Saw (2004)/Saw (2004).mkv

My folder structure on google drive. 
Google drive/movies

My steps fresh install
1. I go to my movie folder in your addon a press "export to .strm files.."
2. Select my destination as /home/user/desktop/kodi
3.i check "update library after export" and "watch for changes in the cloud folder" and press save and run
4. It creates a folder structure and strm files for each movie eg. home/user/desktop/kodi/Movies/Saw (2004)/Saw (2004).mkv.strm
5. After that if I add a new movie in a folder on Google drive eg.
Google drive/Movies/Saw 2 (2005)/saw 2.mkv
a folder will be created in the kodi folder in a few seconds eg
home/user/desktop/kodi/Movies/Saw 2 (2005)
But no strm file created inside the Saw 2 (2005) folder

Testing
If I put the saw 2 (2005).mkv file into the movie directory without a subfolder eg.
Google drive/Movies/saw 2 (2005).mkv
It will create a strm file for the movie. 
So it looks like it's just not creating strm in subfolders. Is it meant to create a strm in sub folders or have I missed a step?

**Comment by cguZZman** [comment]
Can you upload your debug log file. Activate the debug option just **before** you are going to drop your mkv file in Google Drive so I can see how the addon detects and process the change.
No need to activate the debug before the full export. only once you are ready to put your new file in google drive.

**Comment by 4luk** [comment]
> Can you upload your debug log file. Activate the debug option just **before** you are going to drop your mkv file in Google Drive so I can see how the addon detects and process the change.
> No need to activate the debug before the full export. only once you are ready to put your new file in google drive.

Please see below 
https://pastebin.com/RLAJELqC
Thanks

**Comment by cguZZman** [comment]
I see the error now. Thanks for the log. Will fix it.

**Comment by 4luk** [comment]
> I see the error now. Thanks for the log. Will fix it.

Thanks so much. Really appreciate it can't wait :D

**Comment by cguZZman** [comment]
fixed in last version
