### ISSUE TITLE
"File not found" error.

### ISSUE THREAD

**Issue by pras92** [cguZZman/plugin.googledrive#171]
**Describe the bug**
My first time using this add-on. When i try to play any video file, I get an error "File not found" in my media player. I can confirm the files are playable directly from Google web UI and this had nothing to do with any API limits. I use MPC-BE as my default player, which works fine with other Kodi video addons like Plex & Jellyfin.

**To Reproduce**
1. Go to 'any google folder'
2. Click on 'any video'
4. See error "File not found" in my media player.

**Your debug log file**
https://paste.kodi.tv/gunugasuli.kodi

P.S.: Just to make sure the issue isn't due to MPC-BE, I'll test with a fresh instance of Kodi with it's default player & update here.

**Comment by cguZZman** [comment]
Log file is showing the addon passing the correct url to the player. Looks like MPC-BE does not know how to read urls with custom headers. Take a look on https://kodi.wiki/view/HTTP and check the section "protocol headers" to know how the url is passed.
Let me know how your test with default player goes.

**Comment by pras92** [comment]
Hey @cguZZman 
Sorry for the long delay. Couldn't get a chance to test it out until now.

And thanks for the info. 

On a fresh install, the addon works fine with default player. With MPC-BE, regular http URLs like youtube plays fine, but downloadable files from sample videos in internet isn't playable. It seems MPC-BE doesn't support custom headers, like you've mentioned. 

I'll stick with my portable kodi for now. 
Thank you!
