### ISSUE TITLE
Google Drive as a source

### ISSUE THREAD

**Issue by juangarciac** [cguZZman/plugin.googledrive#174]
**Describe the bug**
When allow "Google drive as a source" is selected it does not appear as a source when trying to add videos to the library under "add videos".
I'm deactivating "Use Google Drive as a source" in the configuration and i do not see any difference, what's the purpose of this feature ? or when I can see an example of the usage ? 

I'm using Kodi 18.7 in a FireTV 4k device

**Comment by 4luk** [comment]
I've never used add as a source before but from what I can see you will need to add your ip with port in your file manager. Then you should be able to use as source.

**Comment by cguZZman** [comment]
take a look on https://github.com/cguZZman/plugin.googledrive/issues/119
