### ISSUE TITLE
GDrive shortcuts compatibilty

### ISSUE THREAD

**Issue by ZeDinis** [cguZZman/plugin.googledrive#176]
Please make the addon compatible with shortcuts to drive files. 

When I trying to open it I get error " Only files with binary contents can be downloaded", I guess addon try to download the shortcut file instead of the target file. 

This is a very new feature of google drive which allow to have vide libraries better organized even with files in different accounts.

Thanks.

**Comment by cguZZman** [comment]
fixed in latest version
