### ISSUE TITLE
Python 3 support for Kodi 19

### ISSUE THREAD

**Issue by jet082** [cguZZman/plugin.googledrive#177]
Currently, when I try to install this add-on with Kodi 19 (on AppleTV), it fails because it requires Python 2.25 and Kodi 19 has Python 3.

I do not know enough about this process to know if this is simply a matter of using your existing code (which might be compatible with both?) and updating an xml file or what, but with the end of life coming for Python 2 and the need for Python 3 add-ons with Kodi 19, it seems like a good idea to work on this at some point.

**Comment by CarlosLopezES** [comment]
+1, Kodi 19 it's coming around the corner, and this plugin is a MUST.

Thanks @cguZZman for your work!!

**Comment by undead9786** [comment]
+1, didn't realize I was in the beta program and got it installed and it's gone.

**Comment by hista** [comment]
+1 too!

**Comment by cguZZman** [comment]
Support for Kodi 19 has been added.
Install the new repository from here: https://github.com/cguZZman/repository.plugins or wait for the official Kodi Repository update.
