### ISSUE TITLE
Kodi is not playing from Google Drive any longer

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#178]
**Describe the bug**
Kodi is not playing from Google Drive any longer. My account is ok, I can play using another device from the same source using the same account. The problem is one Xiaomi Box S running the latest firware/android and Kodi 18.0 (I can't use the newer versions since they all give me the "source too slow error of death" every minute or so during playback). I click to open the movie, either from the Movies interface OR using the Google Drive navigation interface, the spinning blue rings appear and never stop as if the movie is loading but it never plays. I installed Kodi from scratch and tried Google Drive from the Kodi and repo.daro.mx repositories. Same error.

**To Reproduce**

1. Install Kodi 18.0 in Xiaomi Mi Box S running the latest Android
2. Install and setup Google Drive add-on
3. Try to play a movie

**Your debug log file**
https://paste.kodi.tv/enikatevox
There are 47 errors in the logs, most of them related to images that can be loaded. Some can be found below:
```
ERROR: Flush - timed out waiting for renderer to flush
ERROR: Could not find suitable input format: x-directory/normal
```

Thanks for the help.

**Comment by cguZZman** [comment]
I see the addon provided the correct url to Kodi and actually it was able to get the video info:
`22:49:22.847 T:7448    INFO: ffmpeg[1D18]: Input #0, matroska,webm, from 'https://www.googleapis.com/drive/v3/files/1Y-lcyr2pTZ5hXJuR7gh_uE0X3HH4-GbT?alt=media':
`
That's how far the addon can go. By giving Kodi the correct url to play.

I believe we had this conversation before, but again, problems of compatibility between specific boxes and Kodi is out of the scope of this addon.
