### ISSUE TITLE
Struck at retrieving drive information... at 50% in progress

### ISSUE THREAD

**Issue by kait0kid-1412** [cguZZman/plugin.googledrive#180]
Kodi 18.8 on firestick struck at retrieving drive information.. at 50%

**Comment by nadr21a21** [comment]
Hello. I have the same problem and I don’t know what to do. Is there a solution please?
![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)

**Comment by kait0kid-1412** [comment]
> Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)

Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.

**Comment by nadr21a21** [comment]
> > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> 
> Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.

You are right. I have many .. I will try to get out and tell you what happened

**Comment by nadr21a21** [comment]
> > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > 
> > 
> > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> 
> You are right. I have many .. I will try to get out and tell you what happened

I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution

**Comment by kait0kid-1412** [comment]
> > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > 
> > > 
> > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > 
> > 
> > You are right. I have many .. I will try to get out and tell you what happened
> 
> I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution

Attach a debug log file so that cguzzman can solve it.

**Comment by nadr21a21** [comment]
> > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > 
> > > > 
> > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > 
> > > 
> > > You are right. I have many .. I will try to get out and tell you what happened
> > 
> > 
> > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> 
> Attach a debug log file so that cguzzman can solve it.

Hello .. where do I find that? I mean the path, because I cannot copy all these codes thanks

> > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > 
> > > > 
> > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > 
> > > 
> > > You are right. I have many .. I will try to get out and tell you what happened
> > 
> > 
> > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> 
> Attach a debug log file so that cguzzman can solve it.

Thank you . I don’t know the path of the path but took a screenshot but I hope that helps
![Screenshot_٢٠٢٠٠٩١٩-١٦٣٢١٥_Kodi](https://user-images.githubusercontent.com/67961690/93668599-fb375500-fa95-11ea-8266-ff32e9b064b0.jpg)

**Comment by nadr21a21** [comment]
> > > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > > 
> > > > > 
> > > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > > 
> > > > 
> > > > You are right. I have many .. I will try to get out and tell you what happened
> > > 
> > > 
> > > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> > 
> > 
> > Attach a debug log file so that cguzzman can solve it.
> 
> Hello .. where do I find that? I mean the path, because I cannot copy all these codes thanks
> 
> > > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > > 
> > > > > 
> > > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > > 
> > > > 
> > > > You are right. I have many .. I will try to get out and tell you what happened
> > > 
> > > 
> > > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> > 
> > 
> > Attach a debug log file so that cguzzman can solve it.
> 
> Thank you . I don’t know the path of the path but took a screenshot but I hope that helps
> ![Screenshot_٢٠٢٠٠٩١٩-١٦٣٢١٥_Kodi](https://user-images.githubusercontent.com/67961690/93668599-fb375500-fa95-11ea-8266-ff32e9b064b0.jp

> > > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > > 
> > > > > 
> > > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > > 
> > > > 
> > > > You are right. I have many .. I will try to get out and tell you what happened
> > > 
> > > 
> > > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> > 
> > 
> > Attach a debug log file so that cguzzman can solve it.
> 
> Hello .. where do I find that? I mean the path, because I cannot copy all these codes thanks
> 
> > > > > > Hello. I have the same problem and I don’t know what to do. Is there a solution please?
> > > > > > ![٢٠٢٠٠٩١٩_٠٥٠٥٥١](https://user-images.githubusercontent.com/67961690/93656831-f5aa2280-fa35-11ea-9faf-cff1fc2a4622.jpg)
> > > > > 
> > > > > 
> > > > > Your team drives are looping, if you are in many Google groups for same team drive, please try exiting from those. This worked for me earlier.
> > > > 
> > > > 
> > > > You are right. I have many .. I will try to get out and tell you what happened
> > > 
> > > 
> > > I tried it but it didn't work still stuck. Thank you for your time in helping me. I hope to find another solution
> > 
> > 
> > Attach a debug log file so that cguzzman can solve it.
> 
> Thank you . I don’t know the path of the path but took a screenshot but I hope that helps
> ![Screenshot_٢٠٢٠٠٩١٩-١٦٣٢١٥_Kodi](https://user-images.githubusercontent.com/67961690/93668599-fb375500-fa95-11ea-8266-ff32e9b064b0.jpg)

Hi @kait0kid-1412 You have deleted all groups I had 10 and when I told you that I did an experiment I deleted 5 but it didn't work. Now I deleted everyone and the surprise was that he contacted an account and he is working now. I don’t know why this happened. I was using A long time ago without problems but with Google server problems happened to me and that's why I was looking for a solution for a month. Thank you for suggesting that solution. 

Note: I have returned groups and the account is now working
