### ISSUE TITLE
Music via Google Drive on Kodi 

### ISSUE THREAD

**Issue by mg1234567** [cguZZman/plugin.googledrive#181]
You state, "You can export your music too, but kodi won't support it yet. It's a Kodi issue for now." 

Question: What can we as users do to help, encourage, complain, or motivate Kodi / developers to change this? 
Where specifically (website, thread, etc)? 

I ask because I have backed up all my music to Google Drive (shared drive) and would like to be able to play it via Kodi the same way I am able to play videos, movies, tv, etc.

**Comment by cguZZman** [comment]
I believe posting a question in the Music Support forum would be the way to go. https://forum.kodi.tv/forumdisplay.php?fid=263

**Comment by mg1234567** [comment]
Thank you cguZZman, I have posted on Kodi's music forums: 

For continuity: 
https://forum.kodi.tv/showthread.php?tid=357710

If anyone is interested in this and wants to see it implemented, follow the link above. 
My guess is that the more people that chime in, the more likely a developer will begin to work on this.

**Comment by cguZZman** [comment]
Over there you stated that you can import your music library, but the files will not play. 

You should be able to play an audio in Kodi from an strm generated by the addon. Importing those files in the library was the problem.
So can you explain more what is the problem? and post a debug log file and everything

**Comment by mg1234567** [comment]
you are correct.  I have added a second post to the thread as a because I cannot correct / edit the post.  Sorry for the confusion.

**Comment by cguZZman** [comment]
You can edit it. There is a button to edit below each post, together with Replay, Quote or Report.

Now your second post says you cannot create .strm files. 
You should be able to create .strm files with the addon.

**Comment by mg1234567** [comment]
I'm sure you understand so many levels of this issue and are more than well equipped to properly report on it in the kodi forums.  

As I stated in my original post here, I am simply an end user of your wonderful software. 

I hate to ask you to do anything more than you have already done for so many people, but it is clear to me that I am not the correct person to report or explain the issue.  If you have the time or inclination, I would greatly appreciate it if you could properly explain the issue on the Kodi forums. 

I'm more than confident that your considerable weight on this issue would mean quite a bit more than those of any end user.   

If you are not inclined, I understand and will continue to do my best.
