### ISSUE TITLE
Video shortcuts added to my drive doesn't play

### ISSUE THREAD

**Issue by Srini-B** [cguZZman/plugin.googledrive#185]
going to my drive by selecting my profile name, selecting the video which has been added as a shortcut via gdrive website, selecting it loads, and then stops. no error, nothing. The file i was trying to play starts with Superman man of tomorrow

[log file](https://pastebin.com/AztLxH6J)

**Comment by cguZZman** [comment]
thanks for your report. I have the fix ready. Will be released soon.

**Comment by cguZZman** [comment]
fixed in latest version

**Comment by alejandro196711** [comment]
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/8931438/kodi.log)
En mi idioma natal / In my born language

Estoy utilizando la última versión y tengo este mismo problema.
Tengo instalado el add-on en dos smarttv android.  En una funciona bien, pero en la otra sucede este inconveniente. Utilizo la misma cuenta de google en ambos. He revisado las configuraciones de KODI y están iguales en ambos dispositivos. ¿Alguna sugerencia?

Traducción de Google / Google translation

I am using the latest version and I have this same problem.
I have the add-on installed on two android smarttvs. In one it works fine, but in the other this inconvenience occurs. I use the same google account on both. I have checked the KODI settings and they are the same on both devices. Any suggestion?
