### ISSUE TITLE
"shared with me" folder is not visible in sources menu & Shortcut folders are not visible

### ISSUE THREAD

**Issue by aloksaurabh** [cguZZman/plugin.googledrive#186]
**My Last bug report was closed as did not have enough details Reopening with details**
i cannot share the log file as i do not have access to device directories. But i am sure you should be able to replicate using pictures given.

**Business Case**: My friend has shared some content with me on google drive which i want to add to my collection and play.
![image](https://user-images.githubusercontent.com/7407336/94366621-1ab62980-00f7-11eb-95e3-1fa375f5e1b0.png)
i created a shortcut
![image](https://user-images.githubusercontent.com/7407336/94366638-3c171580-00f7-11eb-94a2-fed50457449a.png)

The folder shared is Media

**I can see it in the shared with me folder** which i open the addon. See pictures below.
![image](https://user-images.githubusercontent.com/7407336/94366674-62d54c00-00f7-11eb-9e26-dd1708bc3f90.png)
![image](https://user-images.githubusercontent.com/7407336/94366897-9795d300-00f8-11eb-808f-5015ca7a5585.png)

![image](https://user-images.githubusercontent.com/7407336/94366678-6bc61d80-00f7-11eb-9f85-5dc1cff06154.png)

I can also play the content ( not shown) 

### **Bug 1**
However **shared with me folder is not visible in sources menu**. See pictures below.
![image](https://user-images.githubusercontent.com/7407336/94366700-91ebbd80-00f7-11eb-9506-31a68bdff06b.png)
![image](https://user-images.githubusercontent.com/7407336/94366707-9dd77f80-00f7-11eb-9ab2-cdb6cd9047f9.png)
![image](https://user-images.githubusercontent.com/7407336/94366712-a760e780-00f7-11eb-92dc-a1e7a1daeced.png)
![image](https://user-images.githubusercontent.com/7407336/94367072-c06a9800-00f9-11eb-9577-53197a59da30.png)

### **Bug 2**
The alternative would be to **create a google drive shortcut to a folder named Alok**. 
![image](https://user-images.githubusercontent.com/7407336/94366638-3c171580-00f7-11eb-94a2-fed50457449a.png)
However the **shortcut folders are also not visible**.

**Nether in the video addon** 
![image](https://user-images.githubusercontent.com/7407336/94366897-9795d300-00f8-11eb-808f-5015ca7a5585.png)
![image](https://user-images.githubusercontent.com/7407336/94366902-9fee0e00-00f8-11eb-9e75-b904fe632a67.png)
![image](https://user-images.githubusercontent.com/7407336/94366907-a7151c00-00f8-11eb-92d4-61b2ed5e55ae.png)

**nor in the sources**
![image](https://user-images.githubusercontent.com/7407336/94366860-67e6cb00-00f8-11eb-91c8-fa8ae5f16457.png)
![image](https://user-images.githubusercontent.com/7407336/94366870-7503ba00-00f8-11eb-938b-2a51138550bc.png)

**Comment by cguZZman** [comment]
Same as https://github.com/cguZZman/plugin.googledrive/issues/30
Shortcuts should be visible with the last update.

Source mode is not working anyway. I have not found a reliable mode to get it back. So in the meantime you can navigate your files, but wont be able to play them.
