### ISSUE TITLE
That's a known issue of OpenELEC and the work around is to bypass the ssl verification, which I'm not in favor of. Looks like OpenELEC stopped its development some time ago.

### ISSUE THREAD

**Issue by FPLGraphs** [cguZZman/plugin.googledrive#188]
That's a known issue of OpenELEC and the work around is to bypass the ssl verification, which I'm not in favor of. Looks like OpenELEC stopped its development some time ago.
The issue is fixed in LibreELEC and OSMC. So I believe a better solution is to move to one of them.

_Originally posted by @cguZZman in https://github.com/cguZZman/plugin.googledrive/issue_comments/410399576_

**Comment by FPLGraphs** [comment]
What is the work around for this issue?

**Comment by cguZZman** [comment]
The solution is to upgrade to LibreELEC. There wont be a version of the addon bypassing the ssl verification.
