### ISSUE TITLE
Cannot install new addon or common module via kodi zip file

### ISSUE THREAD

**Issue by droidlyy** [cguZZman/plugin.googledrive#189]
Hi Carlos, thanks for the add-on and all of your efforts. I downloaded script.module.clouddrive.common-1.3.0.zip & 1.3.1.zip, plugin.googledrive-1.4.1.zip & 1.4.2.zip and none will install from kodi using add from zip file. I get errors saying "failed to install due to invalid structure". I downloaded all 4 from your repository.

ideas? advice?

**Comment by cguZZman** [comment]
I recommend you to just install my repo. Follow the instructions here: https://github.com/cguZZman/repository.plugins
