### ISSUE TITLE
account manager object has no load attribute google drive

### ISSUE THREAD

**Issue by screege** [cguZZman/plugin.googledrive#191]
Hi the plugin was working perfectly but today I started to get this message:

account manager object has no load attribute google drive

I uninstalled the plugin reinstalled it and reautheticated it but nothing still same message can anyone help me?

Regards

**Comment by brunosaragiotto** [comment]
@screege post your debug log file.

**Comment by screege** [comment]
How can I create it so I can post it? It only gets this message under android (both nvidia shields) not my windows pc.

Regards

**Comment by screege** [comment]
Sorry now is also doing it under windows pc it asked me to send the error log automatically in Kodi do not know if that is right.

regards

**Comment by screege** [comment]
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/5405653/kodi.log)

**Comment by screege** [comment]
[kodi.old.log](https://github.com/cguZZman/plugin.googledrive/files/5405662/kodi.old.log)

**Comment by cguZZman** [comment]
Your versions are not mixed correctly with the common module. Install the new version from my repo.

**Comment by screege** [comment]
Sorry but I have uninstalled it, tried to install it from the zip,  from the repository and the zip but it is not updating anything I still get v 1.3.4 of the plugin not 1.4.6, is there a way to update it from the repository?

Regards and thank you

**Comment by cguZZman** [comment]
just follow the instructions from the link I just gave you. Install my repo and then just install the addon from it.

**Comment by screege** [comment]
Thank you so much now is working, sorry didn´t read the below part in the link.

regards

**Comment by pras92** [comment]
In case someone's wondering after installing cguZZman's repo plugin, you still have to uninstall your previous GDrive installed from Kodi repo, and do a fresh Gdrive addon install from cguZZman's repo. 

In my case, kodi repo had only v1.3.4 while cguZZman's repo had v 1.4.8 as latest, which solved the original issue.
