### ISSUE TITLE
Google Team Drive - Not Playing Videos

### ISSUE THREAD

**Issue by bluediocs4** [cguZZman/plugin.googledrive#192]
From a past week, Google Team Drive Videos Not playing anymore, we can see the list of files but try to play, keep-on loading and 
closing loading symbol nothing playing.

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/5407883/kodi.log)

**Comment by cguZZman** [comment]
your file has a google ban.

**Comment by bluediocs4** [comment]
kodi 18.9 shared drive working fine. no issues. thnQ bro
