### ISSUE TITLE
Plugin shows me Unknown error  on screen

### ISSUE THREAD

**Issue by fpsoto** [cguZZman/plugin.googledrive#193]
Starting my kodi app in my android tv the log on screen show me "accountmanager" object has  no attirube "load"
please try again

i cannot watch any movie or tv show :(

please if you can review this message.

i have installed the last version of the plugin

**Comment by RogerWeir** [comment]
I also have this problem, same message.

**Comment by cguZZman** [comment]
Get the latest version from my repo. Follow the instructions in https://github.com/cguZZman/repository.plugins to install it.

**Comment by Shacamus** [comment]
Confirm your instructions are working - thanks a lot!.
Is it due to à change in Google API?

**Comment by RogerWeir** [comment]
Installed as above- spot on, working fine now. Thanks.

**Comment by cguZZman** [comment]
No, this is due to the new version incoming into the Kodi repo. Team kodi is updating the common module first, then the main addon. That is causing the error.

**Comment by butts136** [comment]
I got the same problem this morning but with a little bit of search, you helped me but I still have a little problem. Every two minutes or around, I have a notification from the google drive addon and it's write : Unknown error : 0ADez4W1zvjxYU (xxxxxx) but i can watch video anyway. Is there a way to hide these notifications ?

Thanks ;)

**Comment by Wildfire0310** [comment]
Bro, I hope I can explain my problem well, when I enter my cloud through the addon, and try to scan my library, it tells me to wait 60 seconds for the scan to start, however, it does not scan even if I try several times, it only creates the folder but without strm files i have followed your instructions and even deleted the app completely, however it doesn't work
What can I do about it?

**Comment by Wildfire0310** [comment]
> Bro, I hope I can explain my problem well, when I enter my cloud through the addon, and try to scan my library, it tells me to wait 60 seconds for the scan to start, however, it does not scan even if I try several times, it only creates the folder but without strm files i have followed your instructions and even deleted the app completely, however it doesn't work
> What can I do about it?

In addition to the above, the screen shows the following message: Google Drive "Unkwon error: ascii codec cant decode byte 0xc3 in position 3: ordinal not in range (128)

**Comment by cguZZman** [comment]
this is not the thread for those issues.
make sure you have the latest version and if the problem persist, open a new issue and the debug log file is mandatory.
