### ISSUE TITLE
videos won't play

### ISSUE THREAD

**Issue by morsaus** [cguZZman/plugin.googledrive#194]
Currently in our shared drive the videos are not being reproduced.
I really do not know if it is due to any change in google policies regarding the quota or is it some question related to the addon

The question is if they are aware of this situation or is it a peculiarity of our shared drive

**Comment by cguZZman** [comment]
without a log file, there is no way to know. Try the option Check google ban.

**Comment by morsaus** [comment]
Good point. The answer is yes, we are banned. Is there any way to fix this? 24 hours does not seem to be the measure since we have experienced this for many days.

**Comment by cboswald95** [comment]
> Good point. The answer is yes, we are banned. Is there any way to fix this? 24 hours does not seem to be the measure since we have experienced this for many days. @cguZZman

I'm experiencing the same problem, the google ban's remained for 5 or so days now, first occurring a day or so after updating to the current version of the add-on.  In the log attached I tried to use a previous version of the add-on to play a video but that resulted in a different error, when I went back to the current version the playback problem persisted and the add-on seems stuck with a message saying "Google Drive watching changes: Kodi Video Folder -- Processing results, please wait... 0%)  

Eventually this crashes Kodi.  

http://paste.kodi.tv/ofinuxexoh

**Comment by cguZZman** [comment]
a ban is out of the scope of the addon. it does not get resolved by installing and old version.
do not share your videos or account if you want to avoid them

**Comment by cboswald95** [comment]
> a ban is out of the scope of the addon. it does not get resolved by installing and old version.
> do not share your videos or account if you want to avoid them

I don't share my account or videos, I had just heard that constantly scanning the library can cause bans.  Thanks for the info.
