### ISSUE TITLE
origin error

### ISSUE THREAD

**Issue by pctechkid** [cguZZman/plugin.googledrive#195]
**Describe the bug**
- After the recent updates, google drive notification shows 'origin error'

**To Reproduce**
- Randomly appears, but most of the time, after a new change/modify files in google drive, and the addon scans and then attempts to export, this error shows up

**Your debug log file**
https://paste.kodi.tv/ocugolafuv.kodi

**Comment by cguZZman** [comment]
It is estrange how this could even happen. 

The workround would be to stop kodi, then delete the file `export-items.db` in the following folder `Kodi\userdata\addon_data\plugin.googledrive\`, then do your export again.
if it happens again, let me know.

**Comment by cguZZman** [comment]
Also your log file does not have debug information. Make sure next time your turn on the debug mode in kodi.

**Comment by enanno** [comment]
Same error here, I think.
I'm getting this message: **Unknown error 'origin'**
Yesterday, everything was working like a charm.
I'll try to catch a log tomorrow, I'm not able to do it right now.

**Comment by pctechkid** [comment]
**Did exactly what you instructed above and turned on debug mode in Kodi.**
_- Stopped Kodi
- Deleted export-items.db
- Exported again_

**Then this appeared again.**
![image](https://user-images.githubusercontent.com/27243557/97078922-6ee2f980-1622-11eb-8857-45f1ab8d0cc6.png)

**Here is the full log:**
[https://raw.githubusercontent.com/pctechkid/kodi-log/main/kodi.log](url)

**Comment by cguZZman** [comment]
fixed in latest version
