### ISSUE TITLE
Exporting error: codec can't decode byte 0xc3 in position 1 ordinal not in range (128)

### ISSUE THREAD

**Issue by fabiovieitas** [cguZZman/plugin.googledrive#197]
Good afternoon friend. The Google drive update worked in parts. However, I can't create STRM files. It always gives error.
ascii 'codec can't decode byte 0xc3 in position 1 ordinal not in range (128).

This happens whenever I do the STRM. As an example, I made a folder "Series".

Thank you in advance for your attention !!!

https://paste.kodi.tv/wiwatuzano

**Comment by cguZZman** [comment]
Actualy your folder is "Séries", not "Series". It is the special character that is causing the error. I will fix it soon. 
You can change the name of your folder for now if you want to avoid this error.

**Comment by fabiovieitas** [comment]
Thank you very much!!!! Working perfectly. congratulations on your beautiful work.

**Comment by cguZZman** [comment]
fixed in latest version
