### ISSUE TITLE
Unable to open google drive

### ISSUE THREAD

**Issue by mrlongshen** [cguZZman/plugin.googledrive#198]
**Describe the bug**
Unable to open google drive addons. To view video. Im using latest kodi.
![2020-10-23_1-58-12](https://user-images.githubusercontent.com/5020778/96912999-a98b4b80-14d5-11eb-909d-ba1de8d4f009.png)

**To Reproduce**
1. Open addons.
2. Select google drive addons
3. Login to the account
4. Error appears

**Your debug log file**
https://pastebin.com/KDHaBkFy

**Screenshots**
![2020-10-23_1-51-20](https://user-images.githubusercontent.com/5020778/96912950-a09a7a00-14d5-11eb-9b8b-16e44a58f44d.png)

**Comment by cguZZman** [comment]
Take a look here: https://github.com/cguZZman/plugin.googledrive/issues/191
