### ISSUE TITLE
shared drive error

### ISSUE THREAD

**Issue by maxolon01** [cguZZman/plugin.googledrive#199]
**Describe the bug**
Unable to play media from shared drive. able to play from regular google drive. 
**To Reproduce**
able to open files on regular google drive. but when click on medias( video) on shared drive., nothing happens, no error sign
till last week able to play from all drives. After latest update to 1.4.6 this problem appeared.  
im using windows 10, with addon 1.4.6 

**Your debug log file**
https://paste.kodi.tv/hoyitizoju

**Screenshots**

**Comment by bluediocs4** [comment]
Same Here, The Videos Can Play From Google Drive; But Unable To Play From Kodi.

**Comment by cguZZman** [comment]
@maxolon01 you are using an old version of the addon. You can install my repo, and get the latest from there.
