### ISSUE TITLE
unknown error 01901616806404964131

### ISSUE THREAD

**Issue by rella99** [cguZZman/plugin.googledrive#201]
siempre que entro en kodi y aleatoriamente, tambien al reinstalar el puggin salta ese error.

https://paste.kodi.tv/imejetuhob.kodi

**Comment by cguZZman** [comment]
Your kodi is too old, and the version of the addons are not displayed.
Anyway, your debug log file does not show any error coming from the addon, so not really much to do from this end.
I suggest you to update your kodi and make sure you have the latest version of the addon from my repo.
