### ISSUE TITLE
Strm export error

### ISSUE THREAD

**Issue by luck2414** [cguZZman/plugin.googledrive#202]
When I try to export the strm files from my peliculas and series folders, the process starts normally, after waiting for the 60 seconds that the addon marks, the process starts but ends 2 seconds later, checking the export location is the folder but empty without any file

log: https://paste.kodi.tv/mexanemidu

**Comment by cguZZman** [comment]
There was an error trying to create your first folder. 
Make sure you don't have any process, program or window looking or working on the parent export folder so the addon can work without interference.
The addon should try to continue with the export in the next minute anyway. Accordingly with your log, you changed the export configuration before next retry.

**Comment by luck2414** [comment]
Desinstalé kodi completamente y lo reinstalé desde cero instalando sólo el addon y de nuevo conseguí el mismo error, algo que noté fue que después de obtener el error al cerrar kodi y reabrirlo, el proceso comenzó automáticamente y correctamente
