### ISSUE TITLE
Google photos not working

### ISSUE THREAD

**Issue by Sergepecher** [cguZZman/plugin.googledrive#203]
**Describe the bug**
I got an error message unknown error:('the read operation timed out',) 
Please try again
**To Reproduce**
1. Go to 'Google drive add-on in pictures
2. Click on my account
3. Scroll down to Google photos
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by Sergepecher** [comment]
this is the log file

https://bonaparte.duckdns.org/wl/?id=gtGf7H48vPZOiuTexTZbHJBloQZb7nlk

**Comment by cguZZman** [comment]
This is a network issue. SSLError: ('The read operation timed out',)
There are few reasons for that, or google photos api was not available at the time, or your local network had issues. 
Just try again, or with a different device or within a different network.
