### ISSUE TITLE
unknown error showing on top right every minute 

### ISSUE THREAD

**Issue by gavinchong87** [cguZZman/plugin.googledrive#205]
**Describe the bug**
an unknown error following a string of codes "OAKviBN......". It has been nonstop popping up on the top right corner every few second. this issue started after I installed the zip to fix the accountmanager issue.

Please help! Thank you in advance!

**Comment by zeppelin33** [comment]
So I'm not the only1 with that error rite now..
good to know its not just me man

**Comment by cguZZman** [comment]
without a debug log file, no way to know.
