### ISSUE TITLE
'AccountManager' object has no attribute 'load'

### ISSUE THREAD

**Issue by skbaji6** [cguZZman/plugin.googledrive#206]
![16036400058141651766190](https://user-images.githubusercontent.com/14947066/97111569-91017800-1705-11eb-86d8-5b266961565c.jpg)

From last 3 days i am getting this Account manager issue and version is 1.3.4 and when i try to update every time it is getting updated to 1.3.4 only

**Comment by cguZZman** [comment]
You can install the latest version from my repo.
And you need to *always* attach a debug log file. The template to create an issue is there for a reason.
