### ISSUE TITLE
STRM not working

### ISSUE THREAD

**Issue by luck2414** [cguZZman/plugin.googledrive#208]
like i explain in the last post, since the update that introduced the banner of the 60s i have been having a problem with the process of export strm files from a folder of google drive, the bug appears when i add my account to the pluging and a i try to export the strm files, the procees starts normally with the banner that says that the process will start in less than 60 seconds, after the 60 seconds have passed the process starts but it stops suddenly, viewing the path that i choose the folder is created but is empty with out any files, first i thought that this was a problem of my pc (Windows)so i asked to a friend to try in his pc (Macbook) and he also had the exactly same problem, whe tried with different google drive accounts, choosing another path, installing kodi from scrath, we even tried on xbox but the problem persisted

log file of my pc (windows) : https://paste.kodi.tv/orobasijaf
log file of my friend´s pc (macbook): https://paste.kodi.tv/qexoduzace

**Comment by cguZZman** [comment]
It is strange that your folder was created but the log says it was unable to create it. Twice. Maybe is a permission or access problem.

Kodi has a File Manager. Can you test creating a folder in your Lightshot folder using Kodi's File Manager. Also try to copy a file there. All using Kodi.
Let me know

**Comment by luck2414** [comment]
ok, i already did it, and there wasnt any problem with the  process of creating the folder and copying the file.
also my friend tried in his macbook and he hasnt any problem too
just in case ,here is the log file of the process: https://paste.kodi.tv/zayoyuquxu

**Comment by luck2414** [comment]
Update: I asked to two more friends to try to replicate the bug and they had the same problem in their pc’s

**Comment by cguZZman** [comment]
Can you try again letting the export retry for many times? I got the error once, and after some auto retries, files were created. But I'm unable to reproduce it again.
Export functionality will retry again every minute.

**Comment by gavin19** [comment]
I can replicate the issue (Win 10/Kodi 18.9/plugin 1.4.8). Logs present the same errors as have already been posted. I'm also able to create a folder in the same save location and copy/move files into it using the Kodi file manager. The strm folder is owned by me and has full permissions.

Running Kodi as admin makes it work most of the time, but the error still happens on some files. 

I haven't exported a strm in a month or more and that was on Kodi 18.8 and pre the 60s notification. Possibly related to the 18.9 update and not the plugin?

**Comment by cguZZman** [comment]
It's possible that it is related to the 18.9 update. If somebody have sometime and try with versions 18.7 or 18.8 that would be great. 

The thing is that for me, at least, it is working even in 18.9 after the mentioned retries.

**Comment by gavin19** [comment]
Issue is the same on 18.7 and 18.8. Tried both.

    DEBUG: [plugin.googledrive][service-export-1248]: creating folder: D:\strm\Top Gun\
    DEBUG: [plugin.googledrive][service-export-1248]: unable to create folder D:\strm\Top Gun\
    DEBUG: [plugin.googledrive][service-export-1248]: change_type: create_folder_retry

The folder *is* created, but not the strm, even after waiting for several minutes. Folder creation itself can take 10 seconds or so.

Even running as admin doesn't make it work as often as I first thought.

[Here](https://pastebin.com/raw/UV5Yv8tW) is a typical chunk in the log, per export.

**Comment by cguZZman** [comment]
can you try again with the new version of the addon? v1.4.9
let it retry for some time if only the folder is created.
Otherwise post the complete log file again.

**Comment by gavin19** [comment]
I was using 1.4.9 the whole time. I can't explain why but ever since I downgraded to 18.7, upgraded to 18.8, then finally back to 18.9, it always works. I tried 20 strm exports and they all went through without issue. It still takes about 10 seconds per strm but the folder and file(s) are created without retries.

**Comment by cguZZman** [comment]
glad is working now.

it should not take that long. you could open a new issue with the debug log file.
