### ISSUE TITLE
Video time advancing not working on Google Photos

### ISSUE THREAD

**Issue by Megarushing** [cguZZman/plugin.googledrive#209]
**Describe the bug**
When using Google Drive integration it is possible to play videos and skip to time frames not buffered yet, in the google photos integration it is also possible to play videos, but if we try to skip the time, or resume play from a specific timestamp, the video ends as if completed, it is necessary to wait for buffering into that area.

**To Reproduce**
1. Go to 'Pictures' > Picture add-ons > Google Drive > Your Account > Google Photos
2. Find and play any long video
3. Skip to the middle of the video
4. Video closes as if completed

**Comment by cguZZman** [comment]
This is a limitation in the Google Photos API. Downloads with byte range parameter is not supported.
Nothing the addon can do about it.
