### ISSUE TITLE
Blu-ray playback

### ISSUE THREAD

**Issue by Be4stElectrjc** [cguZZman/plugin.googledrive#210]
Hi, is the player called through the Python API supposed to have all the features employed in Kodi core player? Ask this, because the player doesn't start the blu-ray engine when playing *.bdmv. So, it treats these as normal video files, while they aren't.

**Comment by cguZZman** [comment]
The player is the same, but the source of the video is a stream from your google drive.
Now, the answer to the question is no. 
Basically you are trying to play a video content that was not meant to be streamed. Kodi is very flexible to some extent, that is not the case for a blue ray rip. With this format Kodi will search for an specific bdmv file which in case of an stream will not exist.
Just change your video to a stream friendly format and you will be good to go. Something like mkv or mp4.
