### ISSUE TITLE
Videos Can Play On GoogleDrive, But Not Playing On Kodi-GoogleDrive PlugIn

### ISSUE THREAD

**Issue by bluediocs4** [cguZZman/plugin.googledrive#211]
Videos Can Play On GoogleDrive, But Not Playing On Kodi-GoogleDrive PlugIn.

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/5470263/kodi.log)

**Comment by cguZZman** [comment]
This is a google ban. 
You can verify it before reporting the issue by selecting the "Check for Google ban" option in the context menu of your video.
