### ISSUE TITLE
Team drives streaming 

### ISSUE THREAD

**Issue by maxolon01** [cguZZman/plugin.googledrive#212]
Unable to play files from team drives. 
recently faced same problem, updated to the latest 1.4.8 from repo daro. it was fixed but lasted for a few days only. 
no problems playing media from regular google drive account. only team share drives. 

**To Reproduce**
repeated play file from google drive, no problem. but when played file from shared drive, nothing happens.

**Your debug log file**
https://pastebin.com/quA7JQzA

**Comment by cguZZman** [comment]
This is a google ban. 
You can verify it before reporting the issue by selecting the "Check for Google ban" option in the context menu of your video.
