### ISSUE TITLE
Team drive media unable to stream

### ISSUE THREAD

**Issue by maxolon01** [cguZZman/plugin.googledrive#213]
**Describe the bug**
Unable to play media files from team drives. 
however able to play from regular google drive accounts. 
i have posted twice and you have removed it without rectifying the issue. 

**To Reproduce**
click on files from team drive, nothing happens
click on files from regular drive. play normally

**Your debug log file**
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/5498558/kodi.log)

**Comment by anfgomezmo** [comment]
Hello, 

I installed the addon but the team drives folder is not showing. Do I need to do something to see it??
