### ISSUE TITLE
Cant load Music file

### ISSUE THREAD

**Issue by Linkinlt** [cguZZman/plugin.googledrive#214]
it works perfect with movies, but Music

**Comment by cguZZman** [comment]
A more detailed description is needed. Use the template that was presented when creating a new issue.
Make sure a debug log file is included. This is required.

**Comment by Linkinlt** [comment]
As you can see, in my ggdrive, i have tons of song, but when i open it
through kodi, it empty. I love your addon, watch movies from my ggdrive
with no isue.
Thank you so much.
