### ISSUE TITLE
When configuring the movie list with Shared Drive, the video source (4k, 1080p...) and audio source (DTS, Dolby atmos...) are not displayed.

### ISSUE THREAD

**Issue by sjstem** [cguZZman/plugin.googledrive#215]
**Describe the bug**
When configuring the movie list with Shared Drive, the video length is displayed at the lower right, but the video source (4k, 1080p...) and audio source (DTS, Dolby atmos...) are not displayed.
they are normally displayed with a square box in the lower right  with normal drive,

**To Reproduce**
1. Go to '...'  -> When configuring the movie list with Shared Drive, the video source (4k, 1080p...) and audio source (DTS, Dolby atmos...) are not displayed.

**Comment by cguZZman** [comment]
it is also displayed in shared drives.
Not possible to check anything without a debug log file.
