### ISSUE TITLE
Google Photos albums and folder contents correct, but black screen when image clicked or slideshow played

### ISSUE THREAD

**Issue by NJKirchner** [cguZZman/plugin.googledrive#217]
### Description
**Only a black screen shows when trying to view images from Google Photos**

I'm working on a Pi4 B w/ the most recent version of LibreELEC
The plugin was once working, an no notable activity was performed before the plugin stopped showing images.

In an attempt to view my Google Photos on Kodi, I will

1. from main menu click pictures
2. select Pictures Add-ons
3. select the google drive addon
4. select my successfully registered account
5. select google photos
6. ...takes a moment to scan
7. presents me with the active list of albums
8. (I tested this by adding a new one w/ a few pictures; it does show up)
9. I select the new album and see the 10 pictures that have been added to it.

<where things get strange>

Right click an item for picture information
File size noted as 0Bytes
No preview of the image is shown to the left of the image
================

right click and try to download an image to >> [home folder\pictures]
I get an error popup 

**File or folder not found. ake sure is still in your drive.
Please try again**
================

I've tried to clear the cache, no change
I've uninstalled, rebooted, installed, no change
================

I've got the logfile but it's 5MB and has all my private image paths dodged into it. Please ask for specifics from the file if needed
I am seeing specific errors regarding googleusercontent 
ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://lh3.googleusercontent.com/lr/AFBm1_a.......Vwh1UxCE_qDsqZYQ=w100-h100 [I figure this is trying to get a 100 by 100 thumbnail of the image]

 &&
 DEBUG: GetImageHash - unable to stat url https://lh3.googleusercontent.com/lr/AF.....

&&
ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 429

2020-12-06 21:42:18.362 T:2521809776   ERROR: CCurlFile::Open failed with code 429 for https://lh3.googleusercontent.com/lr/AFBm1_YFb0K...

2020-12-06 21:42:18.362 T:2521809776   ERROR: Open - failed to open source <https://lh3.googleusercontent.com/lr/AFBm1_YFb0K0DfbnyNQltjO2...

**Comment by cguZZman** [comment]
Google Photos API does not return a file size, so it will not be displayed in the picture information section.
Download and Slideshow for Google Photos is still not implemented. This is be the same as previous issue https://github.com/cguZZman/plugin.googledrive/issues/85

Closing this issue and keeping the mentioned one open.

**Comment by NJKirchner** [comment]
@cguZZman I can't even click a photo to show an image at this point either. Should we still close this or open a new one?

**Comment by cguZZman** [comment]
Displaying the full image and thumbnails is working in my devices. 
An error 22 is usually an issue with your network configuration. I got those kind of errors when connected to my work's vpn.
Check again with another device and/or another network, and if still happening I would definitively need a full debug log file.
