### ISSUE TITLE
Don't export strm files that were exported already.

### ISSUE THREAD

**Issue by titooo7** [cguZZman/plugin.googledrive#220]
**Is your feature request related to a problem? Please describe.**
My addon settings have the following:

- "Watch for changes in the Cloud Folder": On

- "Before full export, remove previous local files and folders" is disabled
- "Update library after export": Off
- Schedulle full exports: OFF

Every single time I open Kodi I see the message "Googl drive watching changes: ......" and I can see that it's looking at files which strm I already have

**Describe the solution you'd like**

Is this an expected behavior? I thought it was expected to look only after new files. It concerns me because as I have a lot of data it takes hour to peform the operation

**Comment by cguZZman** [comment]
What you are seeing is the processing of the changes reported by google. If google reports a change, the addon have to analyze it, no matter what. Even if it's on a file already exported. Was it a change of name? was a change of parent directory? was it deleted? was ..., etc. etc. it does not matter. it has to do it to keep in sync whatever google reported as a change.
so, yeah, it is expected. if you don't want to see the messages, just disable it. there is an option for that in the settings window.
