### ISSUE TITLE
Problema Reproduccion peliculas gdrive kodi matrix w10

### ISSUE THREAD

**Issue by ferboxplay** [cguZZman/plugin.googledrive#228]
He detectado un problema con kodi 19.0-RC1 (18.9.9109 Matrix en windows 10.
Al reproducir una pelicula con el addon google drive version 1.4.10+matrix.2 solo llega a reproducir el primer fotograma de la pelicula y se detiene por completo . Al intentar detener la reproduccion , kodi se cuelga . Si reproduzco la misma película desde un archivo local no hay ningun problema . ¿A alguien más le pasa? ¿Tiene alguna solución? 
Quiero aprovechar para dar las gracias al creador de este fantastico addon y estaria dispuesto a hacerle una donacion si me proporciona algun enlace para ello.

**Comment by cguZZman** [comment]
Sin el archivo de debug, no hay forma de saber que pasa. Pruebalo en otros dispositivos para ver si pasa lo mismo.
Crea un nuevo issue con todo lo que te pide el template. El template esta ahi por que toda esa info se necesita.

**Comment by ferboxplay** [comment]
https://1drv.ms/u/s!AkEEvAcFQvuln5Ute6b9aw9fiW_aaA?e=qQQ7Oe

Buenas de nuevo , aqui te dejo el archivo . En nvidia shield si trabaja bien desde hace tiempo pero en windows 10 en esta version me da estos problemas . Gracias
