### ISSUE TITLE
Create STRM

### ISSUE THREAD

**Issue by luhanmcs** [cguZZman/plugin.googledrive#230]
I have about 14k of videos, the process of creating "strm" takes many hours to finish.
Would it be possible to use rclone as a resource to obtain the links?
The rclone takes a few minutes to generate a list in "txt" with the links and paths of the videos, just extracting the links from "txt" and creating "strm" through them. 
https://rclone.org/commands/rclone_lsf/
https://rclone.org/commands/rclone_lsjson/
![command rclone](https://user-images.githubusercontent.com/22850716/106581630-d366fc00-6521-11eb-9b55-feb6adc9cc1d.jpg)
![result rclone](https://user-images.githubusercontent.com/22850716/106581633-d4982900-6521-11eb-95d6-5b0dd2b8ec29.jpg)
Thnks great Addon....

**Comment by cguZZman** [comment]
I don't think so. 
The strm file needs to have a link pointing to the addon in kodi, with parameters like the drive and file id. I don't see how rclone could generate it.

**Comment by luhanmcs** [comment]
The rclone can obtain the file ID and can generate a list with the complete data of the files.
While the drive ID can be obtained through the settings of the rclone or the current method of the addon.
The difference with rclone is that it can generate a list of links in a few minutes (16k of videos = 2min) and from the list of IDs, names, location, types and create the STRM.
Sorry for my insistence.
I don't know if that can help or show what I mean.
https://github.com/JDRIVO/gDrive-for-Kodi/blob/master/strm_builder_example.py
https://github.com/xyou365/AutoRclone
