### ISSUE TITLE
No reproduce con google drive en kodi matrix

### ISSUE THREAD

**Issue by ferboxplay** [cguZZman/plugin.googledrive#231]
Tengo un problema . Al reproducir una pelicula desde el google drive solo se visualiza el primer segundo de la pelicula y se para automaticamente dejando la aplicacion de kodi crasheada. Con una pelicula desde el disco duro va perfecto . Tengo windows 10 con un ryzen 5 y una nvidia rtx 3060. 
Dejo un link al archivo  .log 

[https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG](url)
https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG

Por favor , échame una mano que me encanta tu plugin
Gracias

**Comment by cguZZman** [comment]
Parece que es un problema con Kodi matrix. Podrias validar si tienes el mismo error con Leia?

**Comment by ferboxplay** [comment]
Con Leia va perfecto , pero la version matrix me interesa porque es compatible con HDR10 y la version Leia , además me da un problema de colores en las peliculas 4k hdr.  ¿Tienes previsto trabajar sobre la versión Matrix? 
Dejo otro link con el archivo.log  del leia junto con una captura de como se me ven los colores en este kodi .

Archivo log  ----------https://1drv.ms/u/s!AkEEvAcFQvuln5dBUhV8CfG218UQZQ?e=JAG6Gk
Captura -------  https://1drv.ms/u/s!AkEEvAcFQvuln5dC84yt0_VuBmstyA?e=0wSgWQ

**Comment by cguZZman** [comment]
El archivo log de Leia no esta en modo debug. No se ve nada.
 ¿Tienes el advancedsettings modificado en Leia tambien?  ¿Podrias probar en Matrix sin las modificaciones?

Una vez que salga Matrix, todas las actualizaciones o correcciones van a ser solo en Matrix.
El error actual parece ser un problema de Kodi, no del addon. Pero estaria bien identificar exactamente cuando sucede antes de reportarselos.

**Comment by ferboxplay** [comment]
Te mando de nuevo el archivo en modo debug. Lo del advancedsettings era para lo del buffer que está establecido en 3gb o más . 
Lo acabo de activar tambien en Leia.  Espero que saquen pronto la version definitiva de Matrix y que tu addon se complemente perfectamente para poder disfrutar de las peliculas con hdr10. Te adjunto el archivo log y una captura más de otra pelicula 

Archivo LOG  -----   https://1drv.ms/u/s!AkEEvAcFQvuln5dDjup-pJiaflatJQ?e=flHIJF
Captura --------  https://1drv.ms/u/s!AkEEvAcFQvuln5dEM5RfzvvEqtzi2A?e=haAvjL

Gracias y felicidades por tu trabajo

**Comment by cguZZman** [comment]
Entonces podriamos concluir que si es un error en Kodi matrix.
Estaria bien que se los reportes en https://github.com/xbmc/xbmc con los dos archivos de debug, uno de Leia y el otro de Matrix para probarles que en la version anterior funciona sin problemas.

Tambien deberias probar Matrix sin las modificaciones en el advancedsettings, para ver si por casualidad funciona o se comporta diferente.

**Comment by ferboxplay** [comment]
Ya se ha soluciado este problema . Tuve que deshabilitar el http2

**Comment by cguZZman** [comment]
Si puedes poner aqui como se hace, mejor. Por si alguien mas tiene el mismo problema.

**Comment by ferboxplay** [comment]
Hay que editar el archivo Advancedsettings.xml y añadir esta linea en el archivo

<disablehttp2>true</disablehttp2>

Gracias por seguir trabajando con tu fantástico plugin

PD. Este es el hilo donde especifican los desarrolladores detalles mas técnicos
https://github.com/xbmc/xbmc/issues/19175#issuecomment-777771204

**Comment by vipulwairagade** [comment]
@ferboxplay I did not understand the steps to fix this even from the issue and comment link you mentioned. Can you please help me with it .

**Comment by ferboxplay** [comment]
You have to read this whole thread and you will find out the solution. You have to edit the advanced settings.xml file and find the line where the word disable http2 is and write true
