### ISSUE TITLE
Automatic playback of the next episode

### ISSUE THREAD

**Issue by mbriacuni** [cguZZman/plugin.googledrive#232]
I synchronized movies and TV series in the library via .strm files, but once the episode is over, instead of going to the next one, it starts over.

**Comment by cguZZman** [comment]
That is not a functionality of the addon. Check your Kodi playback configuration.

**Comment by mbriacuni** [comment]
I did a test. Apparently the problem occurs if the .strm files are synchronized from an ftp server, but if the same files take them from a system folder safely passes next episode. I understand that the problem is not directly related to the addon, but would you have any advice to fix this?

EDIT: If the video is started from Home-> TV series it has that problem, but if it is started from Home-> Videos-> Files it plays normally.
