### ISSUE TITLE
Display media info for strm files

### ISSUE THREAD

**Issue by dyckia** [cguZZman/plugin.googledrive#233]
I noticed that the media info such as resolution, video/audio codec, etc. is missing for strm files in the Library view. 

It would be great if such media info can be identified and saved locally when scanning the files on Google Drive.

**Comment by cguZZman** [comment]
An strm file can't contain any media information. It has only the link to download the file.
One option is to create an NFO file for your video. That should set the information you want in your library and the addon can download it when creating the strm file.
That's how far the addon can go to help you with that info.
