### ISSUE TITLE
Google Drive Addon not working on Kodi 19.0

### ISSUE THREAD

**Issue by Bizzlesticks** [cguZZman/plugin.googledrive#235]
Hi all, 

It looks like the latest kodi update (19.0 matrix) broke the Google drive plugin version  1.4.10

Is there any way to get it working? 
Thanks for your help!

**Comment by Bizzlesticks** [comment]
Spoke too soon - I can see this has now been fixed. Thanks boss!

**Comment by jd1900** [comment]
How did you fix it?

I still have 1.4.10 in Google Chromecast with TV version of Kodi. I can't find any update.
