### ISSUE TITLE
New Content Search False Positive

### ISSUE THREAD

**Issue by enanno** [cguZZman/plugin.googledrive#236]
**Describe the bug**
Every time I browse my video files from the official Google Drive Android app, the Google Drive addon starts to search for new contents or changes related to the browsed files.

**To Reproduce**
1. Start Kodi on your TV Box or PC.
2. Start Google Drive official app on your Android/iPhone mobile.
3. Browse a folder with videos on Google Drive official app on your mobile and let the thumbnails be generated.
4. After some seconds, the Google Drive addon in Kodi will start to search for new contents or changes (related to the same videos you were browsing on your mobile).
5. So, if you browse very often your video collection from your Google Drive app on your mobile, the addon in Kodi will search for all the videos you were browsing later, as if there existed new content. And this is quite annoying, unnecesary and could help to win a Google ban.

**Your debug log file**
Not debug log because it is not actually a bug, but a strange behaviour.

**Screenshots**
No screenshots.

**Comment by cguZZman** [comment]
Google API is providing the changes in your drive. It does not matter if your change was generated by the official google app or any other type of change. The addon does not know that. If the API says there was a change in a file, the addon has to process it.
You can disable the progress notifications in the addon settings if its annoying.
