### ISSUE TITLE
Google Photos permissions only

### ISSUE THREAD

**Issue by vladm** [cguZZman/plugin.googledrive#237]
Hello - I tried installing the add-on for kodi19 and it requested permissions to access my whole google drive and google photos. I only want it to access my google photos and not the rest of Google Drive 
Is this something that can be tweaked or configured or Google drive API does not support such fine differentiation?

**Comment by cguZZman** [comment]
Short history, no, it will not be possible unless you setup your own login server and get your own api credentials. Login server code is here: https://github.com/cguZZman/drive-login. That way you can specify exactly the permissions that you want.
