### ISSUE TITLE
Kodi freezes when stoping play Kodi 19

### ISSUE THREAD

**Issue by FalconEagleTest** [cguZZman/plugin.googledrive#241]
when i play a movie (mkv) and i stop it after it started, kodi frizzes and needs to shutdown.
what i see in the log if i let it stay frozen after like 10 min all the log got filed up with:
"HandleAction - ignoring action 122, because topmost modal dialog closing animation is running".
problem only on kodi 19.
thanks alot.

**Comment by cguZZman** [comment]
Without the debug log file there is nothing I can do to help.
