### ISSUE TITLE
Support for personal Client ID and Client Secret to bypass quota exceeded issue

### ISSUE THREAD

**Issue by divyam73g** [cguZZman/plugin.googledrive#242]
@cguZZman This feature request is in light of the recent google crack down on media files stored on drive. Just like rclone, if we could use our own client ID for login purposes, that would solve any quota issues which have occurred frequently in the past on the google drive add-on in Kodi.
An easy implementation would be as implemented in MiXplorer (an android file manager client) which allows you to set various drive parameters prior to login.
For reference, please check https://rclone.org/drive/#making-your-own-client-id
http://ddurdle.github.io/repository.ddurdle-testing/plugin.video.gdrive-testing/

**Comment by cguZZman** [comment]
You can use your own client id and secret. The login web app code is here: https://github.com/cguZZman/drive-login and then you can change the configuration in the addon setting to point to your url.

**Comment by divyam73g** [comment]
@cguZZman  thanks for the reply but the instructions are very unclear. Could you please give some more details? Thanks

**Comment by cguZZman** [comment]
There are no steps written down for deploying the login webapp. You can help create them in detail once you get into setting up yours.
In general, the first step is to run the login web app. Take a look at the code. It's a java application (using spring boot). You can compile and create the jar as any spring boot app. Then, there are some configurations you need to do. But once you start the app, it will tell you which one you need. Or you can take a look on the code. 
After you have the login app running, second and final general step is to change the addon setting to point to your login app url (go to the addon settings and you will see it). Currently is pointing to https://drive-login.herokuapp.com/

**Comment by cguZZman** [comment]
Btw, if the only reason for you to create your own login server is to bypass quota exceeded, I'm not sure if using own credentials will help. 
First, you need to know which quota you exceeded. There are only one or two type of shared quotas that are affected by using the shared login url. And if you are exceeding these quotas, that would mean you are misusing or somehow using the addon incorrectly. Download quota and others similar will not be resolved by using another client or secret. Just as information.

**Comment by divyam73g** [comment]
@cguZZman I understand, but since in the past, playing 4k bluray files multiple times (two or three) resulted in quota exceeded errors (error 403). Now that google is pretty stringent about keeping copyrighted material (even though it's for personal consumption and not copyright infringement) my aim was to avoid that by using personal client ID and secret just as we do in rclone. As it grants you more server requests and reduces the probability of user rate limit exceeded errors.
