### ISSUE TITLE
Unknown error: 'ascii' codec can't encode characters in position

### ISSUE THREAD

**Issue by xatier** [cguZZman/plugin.googledrive#243]
**Describe the bug**
It seems like this plugin is not able to fetch the title correctly when opening the videos. The titles display correctly in directory listing, but the player refuses to start due to the encoding issue. I suspect this is due to Python3 upgrade in Kodi, we may need to add some `.encode('utf8')` when feeding the video titles into Kodi player.

**To Reproduce**
1. Go to some drive folders
2. Click on videos that has non ascii titles (e.g. Japanese)
3. See the error in the dialog

**Screenshots**

```
+-- Google drive ----------------------------------------------------------+
| Unknown error:                                                           |
| 'ascii' codec can't encode characters in position xx-xx:                 |
| ordinal not in range(128)                                                |
| Please try again                                                         |
+--------------------------------------------------------------------------+
```

**Comment by cguZZman** [comment]
Without the debug log file there is nothing I can do to help.
