### ISSUE TITLE
Play choosing stream format stop working in Kodi 19

### ISSUE THREAD

**Issue by alfonsomontejo** [cguZZman/plugin.googledrive#245]
"Play choosing stream format" has stopped working on Kodi version 19. It does not matter if it is selected on the file (long press) or by checking the default option in the addon settings. Losing this option prevents many files from playing on slow connections.

Sorry my English. Thanks for your work.

**Comment by cguZZman** [comment]
Open a new issue with all required information.

**Comment by Mujura** [comment]
Thanks for such a kind reply.

**Comment by cguZZman** [comment]
My pleasure.
