### ISSUE TITLE
No reproduce pelicula desde google drive

### ISSUE THREAD

**Issue by ferboxplay** [cguZZman/plugin.googledrive#246]
Buenas tardes , tengo kodi 19 Matrix con windows 10 . Justo esta mañana he estado usando el addon sin problemas pero hoy por la tarde me da un error a la hora de reproducir . No me funciona ni desde windows 10 ni desde el kodi que tengo instalado en la nvidia shield tv , ambos con kodi 19 matrix. Anoche iba sin problema en los dos dispositivos. He desinstalado y vuelto a instalar el addon por si acaso pero nada , sigue igual 
Mando el archivo de registro por si le podeis echar un vistazo 
Muchas gracias

https://1drv.ms/u/s!AkEEvAcFQvuln6Arl5THIxTK9W2CKQ?e=ozNM1p

**Comment by cguZZman** [comment]
Tienes un ban temporal para reproducir.
Puedes confirmarlo con la opcion "Check for Google ban" que aparece en el context menu del archivo en kodi.
