### ISSUE TITLE
No me actualiza automaticamente la colección de películas

### ISSUE THREAD

**Issue by ferboxplay** [cguZZman/plugin.googledrive#248]
Tengo un dispositivo Nvidia Shield Tv y hace poco instalé kodi 19 con vuestro addon de google drive. Siempre me ha funcionado bien con Kodi 18 pero con kodi 19 no me actualiza el contenido nuevo automáticamente cuando añado una película .

Adjunto el archivo  kodi.log.
Gracias

https://1drv.ms/u/s!AkEEvAcFQvuln6Arl5THIxTK9W2CKQ?e=P6p2bT

**Comment by cguZZman** [comment]
Tu archivo log no esta en modo debug.

**Comment by ferboxplay** [comment]
Creo que ya está ¿me lo puedes confirmar?
Te pongo enlace al nuevo
https://1drv.ms/u/s!AkEEvAcFQvuln6IaxehVjr8XpVEmzQ?e=fjXO1G

**Comment by cguZZman** [comment]
No hay ningun export configurado en tu dispositivo. 
Debes exportar un folder y activar las opciones de watch y la de actualizar libraria para que exporte y actualize automaticamente.
