### ISSUE TITLE
Abrupt photo/app closure 

### ISSUE THREAD

**Issue by altrautman** [cguZZman/plugin.googledrive#249]
I am using Kodi on a smart TV to view Google Drive photos. I have downloaded the Google Drive Photo add-on and I am able to access and open photos from my Google Drive, but when I open a photo it will display for about 10 seconds and then it will abruptly close both the photo and the Kodi  application and bring me back to my smart TV home screen. I want to be able to pull the photo up and have it display on the TV for a long time without closing.

**Comment by cguZZman** [comment]
The issue could be many things. Your tv is failing. Not enough memory in your tv for kodi. Your kodi version is failing. etc.
Without the debug log file there is not much I can do.
Open a new issue with all the required information attached.
