### ISSUE TITLE
Problemas de reproducción en addon de kodi

### ISSUE THREAD

**Issue by Srkamber** [cguZZman/plugin.googledrive#250]
**Describe the bug (Required :red_circle:)**
No reproduce addon google drive, fallos espontáneos tanto en calidad original como 1080p. En aplicación de drive si funciona, creo que el problema está en que la opción al abrir en mi gsuite es descarga, mientras que en drive es visto.

**To Reproduce (Required :red_circle:)**
El fallo es aleatorio, archivos si funcionan y otros archivos no, también se observa que en diferentes momentos unos funcionan y otros no

**Your debug log file (Required :red_circle:)**

Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by cguZZman** [comment]
Gracias por el reporte. Pero sin el debug log file no hay nada que pueda revisar. Crea un issue nuevo e incluye el archivo de cuando te esta fallando para poder revisarlo.

**Comment by Srkamber** [comment]
Gracias Carlos, esta ya todo perfecto, sería algo puntual, un fuerte abrazo
y hasta pronto
