### ISSUE TITLE
Google Drive streaming on Android 11 (tab S7, S10 5G, S20) stops at about 20 seconds.

### ISSUE THREAD

**Issue by anraksa** [cguZZman/plugin.googledrive#255]
As mentioned in the title, when playing gdrive media in KODI for all applicable models, it stops around 20 seconds and control is impossible until KODI is closed. (Besides, I have to stop and forcefully quit the same in my PC version. PC OS win10)

So I couldn't attach the log either.

However, it works without problems on the S8, tab S 10.5, and other Android 10 or lower versions.

Could it be a Samsung One UI 3.0 problem or an Android 11 problem, please give me a solution.

Dear Developers, I want to use Google Addons!
Please.

Version 18 and 19.0, 19.1 matrix

2022.01.22 ADD
 - My Shield TV(2017) Experience 9.0(Android 11) is also perfectly streamed on KODI with this content. -

**Comment by SCAPELLI** [comment]
i have the same problem in windows 10

**Comment by SCAPELLI** [comment]
Finally solved it.

Add the following lines in advancedsettings.xml-

        <network>
          <disablehttp2>true</disablehttp2> 
        </network>

Google Drive videos are playing perfectly on Kodi Matrix now.

**Comment by anraksa** [comment]
> Finally solved it.
> 
> Add the following lines in advancedsettings.xml-
> 
> ```
>     <network>
>       <disablehttp2>true</disablehttp2> 
>     </network>
> ```
> 
> Google Drive videos are playing perfectly on Kodi Matrix now.

Dear SCAPELLI,
I just tested it.
It plays so perfectly. There is no problem on Android, I haven't tested it on Windows 10 yet, but I think it will work.

Thank you so much!
I respect you.

Thank you again.

**Comment by ScamCast** [comment]
Same issue here. Thanks for the fix.

**Comment by ghost** [comment]
So many thanks SCAPELLI !

Worked perfectly to solve this other issue #277 opened for the Nvidia Shield since its update to Android 11 

Can you briefly explain what it does exactly and why this was pertinent to Android 11 ?

Edit : also solved for me the same playback issues on Windows 10

**Comment by CarlosLopezES** [comment]
> Finally solved it.
> 
> Add the following lines in advancedsettings.xml-
> 
> ```
>     <network>
>       <disablehttp2>true</disablehttp2> 
>     </network>
> ```
> 
> Google Drive videos are playing perfectly on Kodi Matrix now.

Hi!

Can you share the exact tabs or spaces for the XML file? I've tried to restart after creating the file in the right directory among all other xml files, but until now, it's not working...

Thanks a lot!

Edit: It's working with:

```
<advancedsettings version="1.0">
    <network>
      <disablehttp2>true</disablehttp2> 
    </network>
</advancedsettings>

 ```

**Comment by benoit16** [comment]
To all those who can't use the google drive extension on Kodi
I just want to testify what finally works perfectly for me.
I use :
Kodi 19.3 installed on an android TV.
I had a hard time trying to get Google drive to work on KODI for several months.
People write anything, it's hard to tell the truth from the false.
The advancedsettings.xml file doesn't exist, you have to create it and transfer it to the
**android/data/org.xbmc.kodi/files/.kodi/userdata/advancedsettings.xml**
If you put it somewhere else, it won't work.
The content of the file must be :

<advancedsettings>

    <network>

        <disablehttp2>true</disablehttp2>

    </network>

</advancedsettings>
Hoping to have helped

**Comment by ClassickTech** [comment]
This is not working with new Android 12 TV permissions. Unable to gain access to android/data/org.xbmc.kodi/files/.kodi/userdata/advancedsettings.xml without root
