### ISSUE TITLE
Stream is slow in laptop

### ISSUE THREAD

**Issue by tgfilm** [cguZZman/plugin.googledrive#259]
### THIS IS ONLY HAPPENING IN PC

Streaming is slow in G Drive
Whenever i click the vdeo it loads only 3(min) to 9(max)secs
![Screenshot (28)](https://user-images.githubusercontent.com/87779987/126543956-9cd8bcad-caed-411a-a1cd-6a690334d80c.png)
See it will hang and there is no loading  on that video or any g drive video
resolve the problem

**Comment by cguZZman** [comment]
Without a debug log file, there is nothing I could check.
