### ISSUE TITLE
Can not choose playback stream format on Android device.

### ISSUE THREAD

**Issue by d122082** [cguZZman/plugin.googledrive#262]
**Describe the bug (Required :red_circle:)**
Can not choose playback stream format on Android device.
No matter setting choosed playback format in Setting as ask or not ask format, it will always playback original format from Google Drive
**To Reproduce (Required :red_circle:)**

1. Select Movie file (*.mkv) on Google Drive, it already transfer by Google (If play it in browser, it can choos as least 720p or 1080p)
2. I can see "Loading Stream format" windows, but the Select windows not jump out and it start with original format.

**Your debug log file (Required :red_circle:)**
https://drive.google.com/file/d/1md725MBOF_kP1etHNaww0ywX60He1bNv/view?usp=sharing
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by bufordt13** [comment]
No solution, but wanted to report that I'm having the same issue on my ONN Android TV device.

**Comment by cguZZman** [comment]
Get the latest version from my repository. The issue was already fixed.
