### ISSUE TITLE
Playback freezes after a few seconds

### ISSUE THREAD

**Issue by mbriacuni** [cguZZman/plugin.googledrive#263]
When I start playing any video (both from .strm files and directly from the addon) after a few seconds it freezes and if I try to stop it kodi freezes and I have to close it forcibly.

Kodi is installed on Windows 10. I also tried to completely uninstall Kodi and immediately start the video once logged in and it still crashes. On all the other devices I have tried (1 pc windows, 2 fire sticks and 1 xiaomi stick) it works regularly.

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/7147493/kodi.log)

[video of the problem](https://youtu.be/NNc8hh5Eg8k)

**Comment by tuantu-it-solutions** [comment]
I ham having exactly the same issue. Kodi x64 on Windows 10 crashes with the add-on while my other android boxes works normally.

**Comment by mbriacuni** [comment]
I've tried with x86 version with the same result.

**Comment by luhanmcs** [comment]
I solved this by disabling HTTP2 in advancedsettings.xml
[https://forum.kodi.tv/showthread.php?tid=324784&pid=3053691&highlight=HTTP2#pid3053691](url)

Create an advancedsettings.xml
and add on it
![Sem título](https://user-images.githubusercontent.com/22850716/133126607-6075009f-c1d3-4cb8-b970-e0a7aa6003ef.jpg)

For more information
[https://kodi.wiki/view/Advancedsettings.xml](url)

Ps. my advancedsettings.xml is exactly like this on Kodi 19.1 Matrix.
![0](https://user-images.githubusercontent.com/22850716/133127011-e16106f8-1d1d-4ac8-b2f6-603960dc9846.jpg)

**Comment by mbriacuni** [comment]
Thanks! Now it works perfectly! Although I don't understand why in the other pc with windows 10 there was no problem and in this pc yes.

**Comment by RobertusIT** [comment]
> I solved this by disabling HTTP2 in advancedsettings.xml [https://forum.kodi.tv/showthread.php?tid=324784&pid=3053691&highlight=HTTP2#pid3053691](url)
> 
> Create an advancedsettings.xml and add on it ![Sem título](https://user-images.githubusercontent.com/22850716/133126607-6075009f-c1d3-4cb8-b970-e0a7aa6003ef.jpg)
> 
> For more information [https://kodi.wiki/view/Advancedsettings.xml](url)
> 
> Ps. my advancedsettings.xml is exactly like this on Kodi 19.1 Matrix. ![0](https://user-images.githubusercontent.com/22850716/133127011-e16106f8-1d1d-4ac8-b2f6-603960dc9846.jpg)

19.3 on firestickm, doesn't solve

**Comment by RobertusIT** [comment]
not working on firestick, 19.3

**Comment by Sukehiro777** [comment]
> I solved this by disabling HTTP2 in advancedsettings.xml [https://forum.kodi.tv/showthread.php?tid=324784&pid=3053691&highlight=HTTP2#pid3053691](url)
> 
> Create an advancedsettings.xml and add on it ![Sem título](https://user-images.githubusercontent.com/22850716/133126607-6075009f-c1d3-4cb8-b970-e0a7aa6003ef.jpg)
> 
> For more information [https://kodi.wiki/view/Advancedsettings.xml](url)
> 
> Ps. my advancedsettings.xml is exactly like this on Kodi 19.1 Matrix. ![0](https://user-images.githubusercontent.com/22850716/133127011-e16106f8-1d1d-4ac8-b2f6-603960dc9846.jpg)

Hey Thanks for Helping 
but I have the same problem my Gdrive addon Vedio freeze after 1 sec or doesnt play it goes to infinite loading
I solved this problem by disabling the Http2 in advancedsetting.xml and it worked now video finally plays but a new problem arise that is video doest play smoothly(like its playing on 10 fps or somthing) it wont keep up with the audio(Audio doest lag its fine) and bit buffing also.
please help me to solve this issue Gdrive is a gem for me in kodi.
