### ISSUE TITLE
'Watching changes' on large library takes up most of the system resources on Android device

### ISSUE THREAD

**Issue by InfiniFlix** [cguZZman/plugin.googledrive#264]
Hey there,

First, let me say thanks SO much for your hard work on this addon!!!

I recently started noticing an issue, as my library is now very big, with thousands of videos in it.

When the Google Drive add-on 'watches cloud drive changes' on a particular Export folder, it seems to utterly consume all the system resources of my Android device.  I am using an H96 Pro+ with 3Gb RAM, and an AMLogix S912 chipset.  Not a slow device by any means, but gets totally bogged down when the Google drive is polling for changes.  By this I mean, navigating through menus is excruciatingly slow and it's impossible to get any videos to play.  And if I try to navigate around too much, it eventually runs out of steam and freezes,

However, if I just leave the google Drive to finish 'watching changes' it is fine.  However, since my library is so big, sometimes it takes over 2 days to complete.

@cguZZMan  Is there any way that the add-on can be set to use less resources (specifically CPU and RAM) while it is 'watching Cloud folder for changes'?  Maybe restrict the number of cores or threads it uses or something?

[kodi.log](https://pastebin.com/GLdadMwM) available 

Thanks!
Ken

**Comment by cguZZman** [comment]
I'm not aware of any option to limit the resource consumption in kodi for an addon. If your library is extremely large, probably the best solution would be to setup a headless kodi as a server and make it watch for changes. But the downside is that you would need an extra device 24/7. 
Your log file does not contains any debug info tho. But in any case, not much I can do from the addon side for now.
