### ISSUE TITLE
Google Drive, Unknown error:####### - pops up every minute

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#265]
**Describe the bug (Required :red_circle:)**
Hi, 

  I've getting a pop up every minute saying "Google Drive, Unknown error:#######". This is a brand new installation onça Shield TV 2019 running all latest firmware with updates. Kodi 19.1 with all updates as well.

**To Reproduce (Required :red_circle:)**

1. Install Kodi 19.1 on NVidia Shield 2019
2. Install and setup Google Drive Plugin
3. Create Export .strm
4. Wait the export to finish, update library
5. Reopen Kodi
6. Error message pops up every minute

**Your debug log file (Required :red_circle:)**
http://paste.kodi.tv/hihuwuvusu

**Screenshots**
![Kodi_20210926_002606](https://user-images.githubusercontent.com/31668431/134792826-8bf67791-3f3b-4d94-9eeb-b745364abbe7.png)

Thank you for the help

**Comment by luhanmcs** [comment]
Try update addon googledrive from v1.4.10+matrix.2 to v1.4.11 from repo oficial https://github.com/cguZZman/repository.plugins and re-authorize your googledrive addon with your account and confirm if you have permission to write in destiny folder to export strm.

**Comment by cguZZman** [comment]
Your debug log file doesn't contains any exception. Extract the log file after you got the exception so it's logged.
And as mentioned by @luhanmcs, update to the latest version from my repo before trying again.

**Comment by gsantosoliver** [comment]
> Try update addon googledrive from v1.4.10+matrix.2 to v1.4.11 from repo oficial https://github.com/cguZZman/repository.plugins and re-authorize your googledrive addon with your account and confirm if you have permission to write in destiny folder to export strm.

Hi - I have reinstalled everything from scratch and it worked.

**Comment by gsantosoliver** [comment]
> Your debug log file doesn't contains any exception. Extract the log file after you got the exception so it's logged. And as mentioned by @luhanmcs, update to the latest version from my repo before trying again.

I would be nice to get better error messages so that we could fastly spot what what going on. As I mentioned above, all went back to normal after reinstalling everything.
