### ISSUE TITLE
Drive not update the seen state

### ISSUE THREAD

**Issue by mbriacuni** [cguZZman/plugin.googledrive#266]
When starting a video from the kodi library (via strm file) it never marks if it was viewed once completed, or when it was stopped and then resumed.
Immediately after completing it I see it marked as seen, but instead of the title there is the name of the file, but as soon as I exit and return it is like in the second screenshot.
I tried on both windows and android (all updated to the latest version) and the library is shared via mysql and strm files via ftp server.

**Screenshots**

![Screenshot_3](https://user-images.githubusercontent.com/48255735/137311973-ed982b05-2196-4c1e-8727-1ff6368b6f00.png)
![Screenshot_4](https://user-images.githubusercontent.com/48255735/137312164-aaaa47e3-f02b-4d71-9099-5f60012b481c.png)

**Comment by cguZZman** [comment]
Without a debug log file, there is nothing I can do the check the issue.

**Comment by mbriacuni** [comment]
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/7368408/kodi.log)

Ok, this is the log. Thx
