### ISSUE TITLE
>3GB file not streaming on Kodi 19.2

### ISSUE THREAD

**Issue by 007vivek007** [cguZZman/plugin.googledrive#267]
Ever since I updated my kodi to 19.2, I’m facing issues in streaming big files. When seeking (or randomly sometimes) player stops and returns to the folder/list. Buffering in even >1GB files.

I’m using 200 MBPS fiber cable connection and not facing issues anywhere else except with this add-on. 

I rolled back to kodi 19.1 #and all works fine now! Am I the only one here facing issues on kodi 19.2?

**Comment by 007vivek007** [comment]
Same issues with kodi 19.3 as well! Kodi is crashing as soon as we open any 1080p file >3GB OR sometimes with 2GB as well. Seems like it's not handling high bitrate videos. Same behavior with 4K video files.

Lemme know if you need the log file.

**Comment by cguZZman** [comment]
Just closing all issues related with playback since the addon has nothing to do with it. Kodi is in charge of doing the playback. The addon's job is to pass the video to kodi to be played.
Try opening a issue in kodi repository.
