### ISSUE TITLE
On Andriod TV 11, this plugin hangs kodi.

### ISSUE THREAD

**Issue by aceventura007** [cguZZman/plugin.googledrive#269]
On Google TV operating system  (Andriod TV 11) (Device: Realme google TV stick 4K) this plugin hangs after play command for any google drive file. I am not able to create or edit advancedsettings.xml file due to scoped storage of andriod 11. Even after using x-plore file manager or ES file manager the access to andriod data folder is not available on andriod TV 11 operating system. Since http2 solution is not working due to scoped storage, kindly provide other solutions.

**Comment by ghost** [comment]
Hello,

Are you sure you cannot write to kodi userdata directory using the X-plore app ? I was able to do it with this app on a Nvidia Shield after its update to android 11.
As an alternative, you can create an advancedsettings.xml file with the http2 fix into the Download folder of your android device and then use the file manager inside Kodi to copy it to the userdata folder.
