### ISSUE TITLE
Ability to download 

### ISSUE THREAD

**Issue by jmacul2** [cguZZman/plugin.googledrive#27]
It would be nice to be able to download the original or even the transcoded versions locally.  Unless I am dumb, I don't see an option to do this currently.

**Comment by cguZZman** [comment]
It can be done with Kodi's File manager. Just add Google Drive as a source, then use the Copy option as usual in the file manager. 
I'm planing to add a way for the source mode to dispatch a transcoded version of a video instead of the original. No ETA tho.

**Comment by bnichs5** [comment]
Why not leave it the way it is? Some things I like to watch from the source file and other I like as transcoded, but it gives you the option to choose when click the file name.

**Comment by cguZZman** [comment]
This would be an option for the source mode.
The dialog where you select the original or transcoded version is only in the addon mode which is not planned to be changed.

**Comment by cguZZman** [comment]
Added in latest version
