### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by Greki17** [cguZZman/plugin.googledrive#270]
After the installation the addon don’t open on Kodi Matrix with Xbox One.

The error is just after the addon installation and I tried to reinstall Kodi but not working.

**Comment by ntilikp** [comment]
Same problem here.  I get a Cloud Drive Common Module error and then a "Google Drive failed to install dependency" error when trying to install.  I would upload a log file but unfortunately the Logfile Uploader also fails to open on 19.3 on Xbox One.

**Comment by Greki17** [comment]
> Same problem here. I get a Cloud Drive Common Module error and then a "Google Drive failed to install dependency" error when trying to install. I would upload a log file but unfortunately the Logfile Uploader also fails to open on 19.3 on Xbox One.

Yes, exactly this is the error.

**Comment by a-tesh** [comment]
I can confirm that I've encountered the same issue on Xbox series S.

**Comment by ntilikp** [comment]
@Greki17 @a-tesh Turns out it's an issue with all add-ons on 19.3 for Xbox.  This guide provides a fix: https://www.matthuisman.nz/2021/10/fix-kodi-xbox-addons.html

But you'll probably run into another bug after that one's fixed, with your google drive videos playing for a moment before freezing and making Kodi unresponsive.  That's because 19.3 enables http2 by default.  You'll need to disable that in the advancedsettings.xml file, as seen in this issue: https://github.com/cguZZman/plugin.googledrive/issues/263

**Comment by Greki17** [comment]
> @Greki17 @a-tesh Turns out it's an issue with all add-ons on 19.3 for Xbox. This guide provides a fix: https://www.matthuisman.nz/2021/10/fix-kodi-xbox-addons.html
> 
> But you'll probably run into another bug after that one's fixed, with your google drive videos playing for a moment before freezing and making Kodi unresponsive. That's because 19.3 enables http2 by default. You'll need to disable that in the advancedsettings.xml file, as seen in this issue: #263

I followed the guide and I had a solution for the first problem. Now I’m stuck with the second bug like you said. How to fix it on xbox? I’ don’t know how to disable http2

**Comment by ntilikp** [comment]
@Greki17 I disabled it through this add-on which lets you edit the advanced settings: https://github.com/abratchik/script.unlock.advancedsettings

It's not hosted on a repo that can be added as a Kodi source so you'll need to put the .zip file on a usb stick or use FTP to get it on the xbox.

**Comment by Greki17** [comment]
> @Greki17 I disabled it through this add-on which lets you edit the advanced settings: https://github.com/abratchik/script.unlock.advancedsettings
> 
> It's not hosted on a repo that can be added as a Kodi source so you'll need to put the .zip file on a usb stick or use FTP to get it on the xbox.

Thanks. All problems solved

**Comment by a-tesh** [comment]
@ntilikp Thank you for your help 👍
