### ISSUE TITLE
Kodi 19 freezes and restarts frequently

### ISSUE THREAD

**Issue by InfiniFlix** [cguZZman/plugin.googledrive#271]
**Describe the bug (Required :red_circle:)**

I am consistently having Kodi 19.2 freeze and then restart, this happens 3 - 5 times per day.  I have asked on other forums and shared logs, and they suggest that it may be the cloud drive addon.  So I tested by uninstalling GoogleDrive and went for 3 days without a freeze/reboot.
Reinstalled Google Drive and now the freezes start again.
I have a HUGE library of movies and TV Shows (4000 movies, 2500 tv shows), set in an export to "Watch drive for changes", but I do not have scheduled exports setup.

Happens on:
Kodi 19.1 LibreElec (9.8.7) install on Intel x86
Kodi 19.2 Libreelec (10.0.0) install on Intel x86
Kodi 19.2 and briefly on 19.3 running on Windows 10

**To Reproduce (Required :red_circle:)**

Easily triggered by watching "streams" from other addons (multi source addons mostly, like Venom sorry), then playing a google drive hosted strm file.

**Your debug log file (Required :red_circle:)**

I enabled ALL the debugging options and it crashed.  This is th elog file (it is 50Mb)

https://www.dropbox.com/s/zfgnlt9gu57tvcr/kodi.old.log?dl=0

If you need any further info, I can haplily provide it.

**Comment by InfiniFlix** [comment]
Here is a fresh install of Kodi 19, on 2 different Intel computers, each installing LibreElec 10.0.0.

Everything works, and then as soon as I install GoogleDrive, from the Kodi repository - the device crashes and then starts a reboot loop, and becomes unusable:

Log from Device 1 (Intel x86)
https://www.dropbox.com/s/j03zlv3xah7plbi/kodi.old2.log?dl=0

Log from device 2  (Intel x86 also)
https://www.dropbox.com/s/6sl7liecn76booq/kodi.log?dl=0

Thanks!

**Comment by InfiniFlix** [comment]
OK!  So I think I narrowed down what the issue is, perhaps you could shed some light on it...  It turns out, although I had a fresh install, I still had my old addon_data profile on the new devices.
I installed fresh Google, with no configuration, and it seemed to be stable...
The differences in the 2 profiles are:
My old profile (which was crashing in a loop) had the following files in \userdata\Aaddon_data\plugin.googledrive:
https://www.dropbox.com/s/x862c5u9qdf5r18/files_googledrive.fpg.JPG?dl=0
*Noticeably, it had migrated cfg file.

My old profile had additional lines in the \userdata\Aaddon_data\plugin.googledrive\settings.xml file:
https://www.dropbox.com/s/ix597r8u6pykt03/settings_googledrive.jpg?dl=0

Would any of that cause Google Drive to go crazy and crash Kodi?

As soon as I put those 2 changes back (add the migrated cfg and add the additional 2 lines in the settings file), Kodi dies and becomes unusable...

**Comment by InfiniFlix** [comment]
Hmm...  well that only lasted w short while.  Now it is back to freezing again.

here is a final crash log, if it helps:
https://www.dropbox.com/s/cqwjy7cnz7eusld/kodicrash.log?dl=0

**Comment by cguZZman** [comment]
Just closing all issues related with playback since the addon has nothing to do with it. Kodi is in charge of doing the playback. The addon's job is to pass the video to kodi to be played.
Try opening an issue in kodi github repo.
