### ISSUE TITLE
Kodi 19.3 Android 9 Nvidia Shield - SLOW with lag and or freezes and or crash 

### ISSUE THREAD

**Issue by mg1234567** [cguZZman/plugin.googledrive#273]
Kodi 19.3
Android 9
Nvidia Shield
Version 1.4.10+matrix.2

Because of the size of my kodi install everything is on a usb 3.1 128gb thumb drive.

Serious lag between 5-45 seconds and/or with freeze and/or crash. 

1. Go to 'addons-> google drive -> ' 
2. Click on 'any menu'
3. Scroll down to 'yeah, try & wait'
4. See error or issue: freeze / lag / crash etc.. 
Basically, try to navigate through your google drive and you'll see the lag. 

But, I am able to watch my content.  

Similar to other issues: #272 #271 & #269 
But, these issues are on other operating systems or have other configurations. 

Is this an Android issue? Is this a kodi 19.3 issue? Is this a google drive issue? 

2021-12-05 09:16:25.505 T:22319 DEBUG : [plugin.googledrive][service-export-153499981040]: 'save_export': **32056.44 ms**

021-12-05 09:17:23.135 T:22319   DEBUG <general>: [plugin.googledrive][service-export-153499981040]: 'save_export': 13235.61 ms
2021-12-05 09:17:27.775 T:22319   DEBUG <general>: [plugin.googledrive][service-export-153499981040]: 'save_export': 3058.64 ms

Any suggestions and/or recommendations welcome.

**Comment by RobertusIT** [comment]
same here with firestick, no way to use this plugin, is better mount a folder in ubuntu and share with kodi

**Comment by RedSquirrel87** [comment]
Same here with an amlogic device. Very slow and the full export procedure with random freeze or crash (as a result often some episodes or shows are totally skipped, forcing you to restart the full export again...). But I think this is an issue when you have a very large library on GDrive (mine is about 8TB of hundreds of film and tv shows)

**Comment by mg1234567** [comment]
Readme (on the code tab above) for this addon has been updated to state:

"Use Google Drive as a source. (Not currently working due to changes in the Google Drive API)" 

Seems as if cguzzman is aware of the problem and hopefully working on a solution. 
Hopefully our reporting the issue is also helping.

**Comment by mg1234567** [comment]
Update: 
Nvidia updated to Android 11 early Jan - problem persisted. 
Nvidia beta pushed to device a few days later - same 
Nvidia pushed a system update in late Jan / early Feb. - still with the problem. 

Mid-Feb: full reset & reinstall of Kodi & google drive
**Lag disappeared**. Everything synced without any issues
**BUT**, movies / videos still **freeze** kodi after anywhere between a few seconds to up to 15 minutes. 
Only solution: force exit the program and kill kodi before restarting. 

Worth noting: playing without issues directly from mixplorer (with codec pack)

**_SOLUTION:_**
AFTER FULL RESET & REINSTALL (not restore from backup, which may work, but I didn't do this)
Then I went on to add disablehttp2 code to Advancedsettings.xml 

Created a file in mixplorer called  Advancedsettings.xml 
Location: 
Android/data/org.xbmc.kodi/files/.kodi/userdata/

in that file I added the string: 

```
<advancedsettings version="1.0">
    <network>
      <disablehttp2>true</disablehttp2> 
    </network>
</advancedsettings>
```

Once added, seems as if the addon is up and working again. 

Worth noting: it seems like the nvidia update messed with my files & folder structure to such a degree that it was unable to fix the problems with both kodi & the google drive addon within kodi... 
now, after reset and re-installation (not restore from backup), I am able to once again use the google drive for kodi addon. 

my skin of choice: Jade
https://forum.kodi.tv/showthread.php?tid=366160&page=2
file link as of this post: 
http://www.freespace.com.au/filehosting/418761
Unzip and install 19 skin zip file

**Comment by benoit16** [comment]
Shiel 2017 9.0.1 + Kodo 19.3 + <advancedsettings>

  <network>

    <disablehttp2>true</disablehttp2> 

  </network>

</advancedsettings>
into userdata
BUT DON'T WORK
I really want to put the shield and kodi in the trash

**Comment by mg1234567** [comment]
> Shiel 2017 9.0.1 + Kodo 19.3 +
> 
> ```
> <disablehttp2>true</disablehttp2> 
> ```
> 
> into userdata BUT DON'T WORK I really want to put the shield and kodi in the trash

I too could not get it to work UNTIL I did a hard reset of the device: 
Settings -> Factory Reset (last option all the way down) 

Sorry but your post is less than clear. 
Did you update to the most recent version of shield experience (Android 11)? 
If no, then I can't help you. 
Did you completely reset your system after all the updates? 
If no, then I can't help you. 
Did you then install and kodi & google drive & setup from scratch? 
If no, then I can't help you. 
If once setup from scratch, did you then create the xml file in the proper location with the complete code (not the one line you posted)? 
If no, then I cannot help. 

Sorry, but I could not get this to work for months until I did all  of these things.  I was stuck, thus the original post. 
Please, verify that you have done all of this. 

Android 11 sw version 9.0.1(33.1.0.274)

**Comment by cguZZman** [comment]
Just closing all issues related with playback since the addon has nothing to do with it. Kodi is in charge of doing the playback. The addon's job is to pass the video to kodi to be played.
Start by disabling http2.
