### ISSUE TITLE
Something is deleting the export folders

### ISSUE THREAD

**Issue by enanno** [cguZZman/plugin.googledrive#275]
Since a few days ago, something is deleting my exports folders completely (Movies and TVshows), so that no item in my collection is playable because the .strm file is no longer found, and I have to re-export everything. This is happening randomly across various devices on Android TV and Windows, with Kodi Matrix, each with its own different settings.

Is Google Drive sending a false positive that the source folders has been deleted? Or is the addon misinterpreting some signal? I haven't altered my Google Drive folders in any way in years, except to add new content.

1. Open Kodi
2. Google Drive addon starts watching changes (even if there are no changes made in days)
3. The watching changes process is extremely slow as for the first time
4. Exit Kodi correctly (even if the watching changes process didn't still finish)
5. Browse your local folders to find your export folders have been deleted completly.

Still no a debug log file because this is totally random in each and every device in which I have Google Drive addon installed, and this is happening since a few days ago.

**Comment by cguZZman** [comment]
Once you have a debug log file come back to reopen the issue
