### ISSUE TITLE
kodi source ID is different than my computer, how can i match them in order to add an account

### ISSUE THREAD

**Issue by casoro76** [cguZZman/plugin.googledrive#281]
**Describe the bug (Required :red_circle:)**

**To Reproduce (Required :red_circle:)**

4. See error or issue

**Your debug log file (Required :red_circle:)**

Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by casoro76** [comment]
how can i match kodi source ID and mine

**Comment by cguZZman** [comment]
Your kodi and your device need to be in the same network or wifi.
