### ISSUE TITLE
Not working with last shield update

### ISSUE THREAD

**Issue by orphen92** [cguZZman/plugin.googledrive#282]
After an update of my shield i can't launch any movie with strm file or directly from the gdrive account.

it is possible to have an update for resolve this issue?

It is possible to have an option for not stream from gdrive but download the movie in a temporary folder and launch it without bufering?

We can imagine :
1) i click on the movie
2) a loader comming and the movie is download in a temporary folder localy
3) when the loader is finish the movie start localy
4) when i launch another movie the previous temporary folder is remove and regenerate for it

Sorry for my bad english

**Comment by zer0oes** [comment]
Same problem here, but on Windows 11. 
When I want to launch a movie from my google drive account, it's loading forever and nothing happens.

Also I think orphen92's idea could be great, it could avoid any network or google drive servers issue :) 

Please fix !!

**Comment by zrenca** [comment]
Same issues with latest shield and kodi versions. 
Neither kodi repo nor cguzzman repo's google drive addon works.

Seems like there are 2 seperate issues.
1. unable to load files in JIS
2. playback issue on english name files


1.4.11
attached kodi.log
[kodi (1).log](https://github.com/cguZZman/plugin.googledrive/files/7992246/kodi.1.log)

**Comment by orphen92** [comment]
Maybe its a gdrive issue (change in API)

**Comment by gsantosoliver** [comment]
This is a pretty weird issue. I have a Shield 2019 fully updated (firmware, Kodi, addons etc) and I DO NOT face the issue. 
I have a friend with the same set up and he HAD the same issue.
Another friend with Shield 2017 also fully updated and he also HAD the same issue. 
What they did to fix it? This -> https://github.com/cguZZman/plugin.googledrive/issues/255#issuecomment-864668287 - please go ahead and try it!

Now, I have no idea of the implications on enabling that option in advancedsettings.xml. The reference site (https://kodi.wiki/view/Advancedsettings.xml) says:

> `  <disablehttp2>false</disablehttp2>         <!-- Added in v19- Allows disabling HTTP2 for broken Curl / HTTP2 servers -->`

Maybe @cguZZman could help us understand that and maybe release a fix that would not require us to be dealing with Advancedsettings.xml anymore.

**Comment by zrenca** [comment]
> This is a pretty weird issue. I have a Shield 2019 fully updated (firmware, Kodi, addons etc) and I DO NOT face the issue. I have a friend with the same set up and he HAD the same issue. Another friend with Shield 2017 also fully updated and he also HAD the same issue. What they did to fix it? This -> [#255 (comment)](https://github.com/cguZZman/plugin.googledrive/issues/255#issuecomment-864668287) - please go ahead and try it!
> 
> Now, I have no idea of the implications on enabling that option in advancedsettings.xml. The reference site (https://kodi.wiki/view/Advancedsettings.xml) says:
> 
> > `  <disablehttp2>false</disablehttp2>         <!-- Added in v19- Allows disabling HTTP2 for broken Curl / HTTP2 servers -->`
> 
> Maybe @cguZZman could help us understand that and maybe release a fix that would not require us to be dealing with Advancedsettings.xml anymore.

Solvd by writing the xml file. all videos play fine now lol

**Comment by zer0oes** [comment]
@zrenca how can I access to userdata folder on my Nvidia Shield ?

**Comment by zrenca** [comment]
> @zrenca how can I access to userdata folder on my Nvidia Shield ? 

I use X-plore and created files under the accordance folder.

**Comment by benoit16** [comment]
Since the last update to android 11 on my shield 2017, I have had to deal with a multitude of bugs and malfunctions.
As for Kodi 19.3, impossible to play a video on google drive and the "fix" by the Advancedsettings.xml file did not change anything.
On the other hand, no problem with X-Plore.
I am disgusted.

**Comment by mg1234567** [comment]
https://github.com/cguZZman/plugin.googledrive/issues/273#issuecomment-1039819575

**Comment by cguZZman** [comment]
This is a kodi issue. Nothing to do with the addon. Disabling http2 is the only option for now.
