### ISSUE TITLE
Google drive not opening or logging in

### ISSUE THREAD

**Issue by shekhar771** [cguZZman/plugin.googledrive#284]
Google drive is not opening or adding an account with error errno 101 network is unreachable.
Other applications are working so not really network issue .
Clicking on my drive its keep on loading and when adding new account it keeps retrying 4 time

https://paste.kodi.tv/golovuduco.kodi

**Comment by cguZZman** [comment]
It is network issue, either kodi is blocked to access the internet or a more generic issue. Nothing to do with the addon.
