### ISSUE TITLE
Embedded subtitles only working in original resolution

### ISSUE THREAD

**Issue by Axanderism** [cguZZman/plugin.googledrive#288]
**Describe the bug (Required :red_circle:)**

A video file with embedded subtitles only makes them available to Kodi in original resolution. Stepping the resolution down loses the subtitles

**To Reproduce (Required :red_circle:)**

1. Find a file with embedded subtitles in original resolution. 
2. Choose a lower resolution (either as default or through the menu option). Subtitles not present for selection when played.

**Comment by Axanderism** [comment]
And now the option to choose stream resolution has stopped working completely? The request is ignored and the default plays.

It appears that might be down to upgrading to Kodi 19 in the hope of things working better. Instead:

*** the request to choose stream resolution is ignored 100% of the time.
*** manually setting the resolution is also ignored, and the default resolution plays every time (which always freezes after a few minutes) 
*** the setting to turn on subtitles is reset each time even when it is set as the default for all media.

Really wish I hadn't updated now!

Edit: updating to the latest version from the repo fixed the resolution issues but not any of the subtitle problems.

**Comment by cguZZman** [comment]
This is expected. Only the original file has the subtitle embedded. Transcoding the video loses the subtitle because it's a new file generated by google where only the image and sound is transcoded. Nothing else.
