### ISSUE TITLE
Video shortcuts doesn't play

### ISSUE THREAD

**Issue by alejandro196711** [cguZZman/plugin.googledrive#289]
**Describe the bug (Required :red_circle:)**

En mi idioma natal / In my born language

Estoy utilizando la última versión y tengo el mismo problema que se reportó aquí: https://github.com/cguZZman/plugin.googledrive/issues/185#issue-709552240.
Tengo instalado el add-on en dos smarttv android. En una funciona bien, pero en la otra sucede este inconveniente. Utilizo la misma cuenta de google en ambos. He revisado las configuraciones de KODI y están iguales en ambos dispositivos. ¿Alguna sugerencia?

I am using the latest version and have the same problem as reported here: https://github.com/cguZZman/plugin.googledrive/issues/185#issue-709552240.
I have the add-on installed on two android smarttvs. In one it works fine, but in the other this inconvenience occurs. I use the same google account on both. I have checked the KODI settings and they are the same on both devices. Any suggestion?

**Your debug log file (Required :red_circle:)**

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/8948770/kodi.log)

**Comment by alejandro196711** [comment]
[kodi living.log](https://github.com/cguZZman/plugin.googledrive/files/9128366/kodi.living.log)

Agrego este otro log. 

Investigando más veo que el error que devuelve google es "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

¿Alguna sugerencia?
==================

I add this other log.

On further investigation I see that the error returned by google is "Daily limit for unauthenticated use exceeded. Continued use requires registration".

Any suggestion?

**Comment by cguZZman** [comment]
Google le puso un ban al archivo. Es muy probable que sea uno compartido. Si no es asi, necesito un debug log file donde se mire toda la navegacion hacia el archivo y luego cuando se da play. Dejame saber y reabro el issue.
