### ISSUE TITLE
Kodi app doesn't get full folder lists

### ISSUE THREAD

**Issue by Axanderism** [cguZZman/plugin.googledrive#292]
**Describe the bug (Required :red_circle:)**

The files I see in my Kodi Drive addon in e.g the Shared With Me or Starred folders are a reduced subset of what I see in my actual Google Drive app. Lots of files are missing in the addon, and there is no consistent pattern as to why anything is absent (e.g. a group of files in the Shared folder on the app don't show up in Shared in the addon. When I then added them all to Starred in the app to access them in the addon that way, only one out of 10 appeared in Starred in the addon.) 

**To Reproduce (Required :red_circle:)**

I have no idea if this is happening or will happen to anyone else, but it has been happening for years. Previously, I could add a Shared file to Starred and access it that way, but even that no longer works. 

**Your debug log file (Required :red_circle:)**

Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by cguZZman** [comment]
The required debug log file is missing.
