### ISSUE TITLE
One or more items cannot be played, check the log file for details

### ISSUE THREAD

**Issue by 1982606762** [cguZZman/plugin.googledrive#296]
**Describe the bug (Required :red_circle:)**
When trying to play the video in google drive it failed and pop up with this error:"One or more items cannot be played, check the log file for details"
**To Reproduce (Required :red_circle:)**

4. See error or issue

**Your debug log file (Required :red_circle:)**
https://i.imgur.com/CoXFqSI.png
**Screenshots**

**Comment by cguZZman** [comment]
I need a full debug log file. No images. You need to enable the debug first.
Also try disabling the http2 first.
