### ISSUE TITLE
> I solved this by disabling HTTP2 in advancedsettings.xml [https://forum.kodi.tv/showthread.php?tid=324784&pid=3053691&highlight=HTTP2#pid3053691](url)

### ISSUE THREAD

**Issue by Sukehiro777** [cguZZman/plugin.googledrive#298]
> I solved this by disabling HTTP2 in advancedsettings.xml [https://forum.kodi.tv/showthread.php?tid=324784&pid=3053691&highlight=HTTP2#pid3053691](url)
> 
> Create an advancedsettings.xml and add on it ![Sem título](https://user-images.githubusercontent.com/22850716/133126607-6075009f-c1d3-4cb8-b970-e0a7aa6003ef.jpg)
> 
> For more information [https://kodi.wiki/view/Advancedsettings.xml](url)
> 
> Ps. my advancedsettings.xml is exactly like this on Kodi 19.1 Matrix. ![0](https://user-images.githubusercontent.com/22850716/133127011-e16106f8-1d1d-4ac8-b2f6-603960dc9846.jpg)

Hey Thanks for Helping 
but I have the same problem my Gdrive addon Vedio freeze after 1 sec or doesnt play it goes to infinite loading
I solved this problem by disabling the Http2 in advancedsetting.xml and it worked now video finally plays but a new problem arise that is video doest play smoothly(like its playing on 10 fps or somthing) it wont keep up with the audio(Audio doest lag its fine) and bit buffing also.
please help me to solve this issue Gdrive is a gem for me in kodi.

_Originally posted by @Sukehiro777 in https://github.com/cguZZman/plugin.googledrive/issues/263#issuecomment-1262414006_

**Comment by cguZZman** [comment]
There is nothing I can do here. The addon has nothing to do with the playback. It's either your internet connection or some kodi configuration/issue. Try to read the debug log file and check for any issue there.
