### ISSUE TITLE
The server is temporary unavailable

### ISSUE THREAD

**Issue by andreus1610** [cguZZman/plugin.googledrive#303]
When opening any video I get the error: "The server is temporary unavailable for this operation.
Please try again later".
I checked drive-login.herokuapp.com site and it returns Application error

**Comment by dvasukodi** [comment]
Hi,

Same Issue For Me, Can't add google drive also. same Error.

**Comment by armanplex** [comment]
Same issue here

**Comment by cguZZman** [comment]
Heroku removed the free tier server service. I'm looking for a new service. It will be down in the meantime.

**Comment by cguZZman** [comment]
Read my full response here: https://forum.kodi.tv/showthread.php?tid=324784&pid=3120043#pid3120043

**For now on, the server will be up as long as the community donates and help with the cost of the hosting.** If you are using the addon, don't be shy - any amount will help.
