### ISSUE TITLE
Problema autentificacion google drive 

### ISSUE THREAD

**Issue by Srkamber** [cguZZman/plugin.googledrive#304]
No funciona el addon google drive

**Comment by cguZZman** [comment]
Heroku removed the free tier server service. I'm looking for a new service. It will be down in the meantime.

**Comment by Srkamber** [comment]
Si necesitas que hagamos la comunidad una donación por PayPal dímelo, para poder seguir manteniendo el addon

**Comment by Srkamber** [comment]
Acabo de encontrar una alternativa  a Heroku, se llama 
 Back4app y tiene un plan gratuito, no se si te valdría, un saludo Carlos!

**Comment by cguZZman** [comment]
Read my full response here: https://forum.kodi.tv/showthread.php?tid=324784&pid=3120043#pid3120043

**For now on, the server will be up as long as the community donates and help with the cost of the hosting.** If you are using the addon, don't be shy - any amount will help.****
