### ISSUE TITLE
Shield TV does not create .strm files.

### ISSUE THREAD

**Issue by anraksa** [cguZZman/plugin.googledrive#306]
I use Shield TV and Google shared drive well, but at some point in Kodi, I realized that the number of movies in the library was insufficient and tried to update it.
Even after updating, it didn't open.

However, the number of libraries and the number of movies I have did not match, so I exported the strm file from Google Drive again, initialized it, and loaded it again, but only a folder was created and no .strm file was created, so all the movies did not appear in the library.

I tried deleting and reinstalling KODI and the .strm file is no longer created.

My galaxy s10 5G and galaxy tab s7 it still works fine and the library updates are fine.

If you know how to fix this please let me know.
Be always happy.

KODI 20. Nexus Version.

**Comment by cguZZman** [comment]
I would need a debug log file to take a look
