### ISSUE TITLE
Koki 19.0 en adelante

### ISSUE THREAD

**Issue by Jonathanv0228** [cguZZman/plugin.googledrive#307]
Saludos, espero todo este bien, soy usuario de kodi, y el motivo por el cual escribo es de ver si se puede y esta en sus posibilidades de corregir un pequeñito problema que tiene el plugins de google drive con kodi 19 en adelante, y es que en versiones anteriores cuando se reproduce un video me daba la opción de elegir la calidad del archivo, en países como el mío esto va bien ya que no tiene conexiones rápidas, pero ya en kodi 19 el plugin no me da esa opción, y el archivo se reproduce original y por tener conexión lenta se me para el video, existe posibilidad de resolver ese detalle. Muchas gracias y perdón. Que tengan buen día

**Comment by cguZZman** [comment]
Necesito el debug log file para poder revisarlo.

**Comment by Jonathanv0228** [comment]
hola carlos aqui te dejo el archivo
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/10539968/kodi.log)

**Comment by Jonathanv0228** [comment]
Hey bro saludos, pudiste ver mi archivo y ver si se puede solucionar ?

**Comment by Jonathanv0228** [comment]
hey brooo saludoss
