### ISSUE TITLE
STRM Resume Issue  from the Dashboard - In progress Movies Section

### ISSUE THREAD

**Issue by andreus1610** [cguZZman/plugin.googledrive#308]
STRM doesn't resume from the Dashboard - In progress Movies Section
but it works if I go into Movie and open the movie from there

here is a video example: https://streamable.com/511kk6

Do you know a way to fix?

**Comment by cguZZman** [comment]
I don't and I would need a debug log file to take a look

**Comment by andreus1610** [comment]
Here is the debug log. There are two of them:
- one that opens the video correctly at the resume point (played from the movie section),
[kodi-reusme-ok-movie_section.log](https://github.com/cguZZman/plugin.googledrive/files/10493598/kodi-reusme-ok-movie_section.log)

- and the other with the issue that it resets the position to the beginning (played from the initial home)
[kodi-resume-issue-initial_home_section.log](https://github.com/cguZZman/plugin.googledrive/files/10493597/kodi-resume-issue-initial_home_section.log)

Thanks
