### ISSUE TITLE
Cannot access Google photos

### ISSUE THREAD

**Issue by matejmosko** [cguZZman/plugin.googledrive#31]
Goohle drive plugin works mostly as expected, but I cannot access google photos. 
![1535886863341387076776](https://user-images.githubusercontent.com/1838963/44955351-256b4980-aeb2-11e8-9f37-841626c33904.jpg)

Kodi 18, libreelec here

**Comment by cguZZman** [comment]
Please post the debug log so I can take a look on this.

**Comment by cguZZman** [comment]
Fixed in version 1.2.7.  Available in my repository.

**Comment by matejmosko** [comment]
Thx, I will have a look. I was on a vacation without access to my kodi.

**Comment by matejmosko** [comment]
Hi, the first error screen is gone. But there is a new one. [This is a log](http://paste.kodi.tv/umarodusix)

![img_20180912_085533](https://user-images.githubusercontent.com/1838963/45407416-a8865f80-b669-11e8-83c6-499071452161.jpg)

**Comment by cguZZman** [comment]
I just updated a new version, 1.2.9. Let me know if that fix the issue.

**Comment by cguZZman** [comment]
I just uploaded a new version, 1.2.9. Let me know if that fix the issue.

**Comment by cguZZman** [comment]
Check the new version. Should fix the order by date. Let me know.
