### ISSUE TITLE
RESOLVED Error on Nexux 20

### ISSUE THREAD

**Issue by ColibriOS** [cguZZman/plugin.googledrive#310]
[script.module.clouddrive.common-1.3.9+fix-nexux.zip](https://github.com/cguZZman/plugin.googledrive/files/10465509/script.module.clouddrive.common-1.3.9%2Bfix-nexux.zip)
on Nexus 20 Google Drive this error is thrown.
unknown error:
module 'inspect' has no attribute 'getargspec
Please try again. 

**RESOLVED**
I resolved the error by editing this in the script.module.clounddrive.common patching the inspect module in its tasks.py file.  Here's an example that works for me in Python 3.11:
```
import inspect

if not hasattr(inspect, 'getargspec'):
    inspect.getargspec = inspect.getfullargspec

from invoke import task

@task
def say_hello(c):
    print("Hello, World!")
```
[https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106](url)

**Comment by ColibriOS** [comment]
I will reopen it for the record and see the dilution for the moment waiting for Guzmán to implement it in the future in the addon

**Comment by xavierisanoob** [comment]
I couldn't find any tasks.py in the .zip file

**Comment by xavierisanoob** [comment]
> [script.module.clouddrive.common-1.3.9+fix-nexux.zip](https://github.com/cguZZman/plugin.googledrive/files/10465509/script.module.clouddrive.common-1.3.9%2Bfix-nexux.zip) on Nexus 20 Google Drive this error is thrown. unknown error: module 'inspect' has no attribute 'getargspec Please try again.
> 
> **RESOLVED** I resolved the error by editing this in the script.module.clounddrive.common patching the inspect module in its tasks.py file. Here's an example that works for me in Python 3.11:
> 
> ```
> import inspect
> 
> if not hasattr(inspect, 'getargspec'):
>     inspect.getargspec = inspect.getfullargspec
> 
> from invoke import task
> 
> @task
> def say_hello(c):
>     print("Hello, World!")
> ```
> 
> [https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106](url)

installing this zip would fix it? or do I need to do something else?
as I said in the previous comment, I couldn't find any tasks.py in the .zip you provided.

**Comment by ColibriOS** [comment]
> > [script.module.clouddrive.common-1.3.9+fix-nexux.zip](https://github.com/cguZZman/plugin.googledrive/files/10465509/script.module.clouddrive.common-1.3.9%2Bfix-nexux.zip) en Nexus 20 Google Drive se produce este error. error desconocido: el módulo 'inspeccionar' no tiene el atributo 'getargspec Inténtelo de nuevo.
> > **RESUELTO** Resolví el error editando esto en script.module.clounddrive.common parcheando el módulo de inspección en su archivo tasks.py. Aquí hay un ejemplo que me funciona en Python 3.11:
> > ```
> > import inspect
> > 
> > if not hasattr(inspect, 'getargspec'):
> >     inspect.getargspec = inspect.getfullargspec
> > 
> > from invoke import task
> > 
> > @task
> > def say_hello(c):
> >     print("Hello, World!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106](url)
> 
> instalar este zip lo arreglaría? o tengo que hacer algo mas? como dije en el comentario anterior, no pude encontrar tareas.py en el .zip que proporcionó.

this zip is edited and it solved my problem, please install it and check if it works for you too

**Comment by alarno** [comment]
Hi, it looks you found a solution, but what about the people like me that have kodi in a google tv installation? Maybe you should release a new version. By the way, CONGRATS! I use your piece of code everyday!!!

**Comment by janglapuk** [comment]
> Hi, it looks you found a solution, but what about the people like me that have kodi in a google tv installation? Maybe you should release a new version. By the way, CONGRATS! I use your piece of code everyday!!!

Officialy, this issue already fixed from related repos. Look at the merged PRs:

- https://github.com/cguZZman/plugin.googledrive/commit/61faecc3348972b30698167d47354b23d4fd2b37
- https://github.com/cguZZman/script.module.clouddrive.common/commit/10bad39ff0c52cee1cab074b20b635a92a066841
- https://github.com/cguZZman/script.module.clouddrive.common/commit/c9a5f714819b42230bad8480324036c517d58ca3

The current problem is the addon hasn't been officially released yet at [repository.plugins](https://github.com/cguZZman/repository.plugins) for Nexus updates, you will not get updates on Kodi until @cguZZman  updates it.

Someone has already opened an issue (https://github.com/cguZZman/repository.plugins/issues/17) regarding this problem, we hope @cguZZman will make a release soon.

Just wait for an official update or create your own ZIP.

**Comment by ColibriOS** [comment]
> Hola, parece que encontraste una solución, pero ¿qué pasa con las personas como yo que tienen kodi en una instalación de google tv? Tal vez deberías lanzar una nueva versión. Por cierto, ¡ENHORABUENA! ¡Uso tu pieza de código todos los días!

download the attached zip and install it as a zip through Kodi this works for any android TV, and certified android TV.

**Comment by dvasukodi** [comment]
unknown error:
module 'inspect' has no attribute 'getargspec
Please try again.

**Comment by dvasukodi** [comment]
> 

plz provide zip

**Comment by janglapuk** [comment]
> > 
> 
> plz provide zip

Look at https://github.com/cguZZman/plugin.googledrive/issues/302#issuecomment-1398661109

**Comment by janglapuk** [comment]
The update for Kodi Nexus has already been released, make sure to update the addons on your Kodi.

https://github.com/cguZZman/repository.plugins/commit/6dee6dd5ed9f35ef66638b54e22d09c754beaf69

This issue should be closed now. Thanks for @cguZZman!

**Comment by thelastfantasy** [comment]
Try to install from your 3.0.0 repo for Kodi 20 but got this error message.
`The dependency on script.module.clouddrive.common version 1.4.0 could not be satisfied`
![PXL_20230121_130306794](https://user-images.githubusercontent.com/6077584/213868058-12d74b5a-3f1c-406d-814b-09efcd94c258.jpg)

**Comment by DeHickok** [comment]
Still having same issue for (Sony) Android TV (after reinstalling KODI 20 nexus and this addon):"unknown error:
module 'inspect' has no attribute 'getargspec
Please try again." 
so maybe this topic should stay open for a little more...
