### ISSUE TITLE
Update plugin, not supporting in kodi matrix 20.0

### ISSUE THREAD

**Issue by Mangalambika** [cguZZman/plugin.googledrive#312]
**Describe the bug (Required :red_circle:)**

**To Reproduce (Required :red_circle:)**

4. See error or issue
![IMG_20230124_142648](https://user-images.githubusercontent.com/121717350/214249643-a73935c6-5a3e-4847-bbaa-b1ab340db02a.jpg)
Getting this error while trying to open a drive account in this plugin, saw in reddit, many having this same error, try to resolve dude, thankyou..
**Your debug log file (Required :red_circle:)**

Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by Marlinruno** [comment]
![IMG_20230124_142648](https://user-images.githubusercontent.com/121717350/214250034-be54226e-b5b7-4561-99b2-d5d318145a9f.jpg)

**Comment by andreus1610** [comment]
Hi, for streaming videos in original format it works on Nexus. 
Make sure you have the latest versions installed: Google Drive 1.5.0 and CloudDrive Common Module 1.4.0
You can find them on the cguZZman's repository

Follow this guide to add the repository:
https://github.com/cguZZman/repository.plugins
