### ISSUE TITLE
The dependency on script.module.clouddrive.common version 1.4.0 could not be satisfied

### ISSUE THREAD

**Issue by colemar** [cguZZman/plugin.googledrive#316]
I am on mobile device thus cannot type much.
Issue is on Android TV with Kodi 20.
Please see linked [video](https://drive.google.com/file/d/1fEo8s9M62Z8T8O-MPcgfWsVneeCNAiYt/view?usp=drivesdk) .
https://drive.google.com/file/d/1fEo8s9M62Z8T8O-MPcgfWsVneeCNAiYt/view?usp=drivesdk

**Comment by andreus1610** [comment]
It did the same for me, It happened to me too, but then I fixed it.
Uninstall and reinstall, and check you have the latest versions installed: Google Drive 1.5.0 and CloudDrive Common Module 1.4.0
You can find them on the cguZZman's repository.

If it still doesn't work, physically delete the "plugin.googledrive" and "script.module.clouddrive.common" folders inside .kodi\addons and inside the addon_data folder of the profile

**Comment by colemar** [comment]
I reproduced the same issue on Windows 10 x64, and then solved it as follows.
Finally I found that Cloud Drive Common Module 1.4.0 (script.module.clouddrive.common) must be installed (somewhat manually) using the [Dependencies] button before attempting to install Google Drive 1.5.0, because the latter does not auto-pull the former.
The procedure is not straightforward though, hence I will explain it below for everyone's benefit.
I believe that Kodi Add-on repository gets in the way because it has an older version of the plugins, therefore always use the [Versions] button and pay attention to version numbers.

Assuming that cguZZman's repository version 3.0.0 is already installed (this is easy, instructions are [here](https://github.com/cguZZman/repository.plugins)), the steps are:

![image](https://user-images.githubusercontent.com/3066000/215268799-d470d699-b1e5-49e5-941e-b80178efcb6b.png)
![image](https://user-images.githubusercontent.com/3066000/215268820-a197b939-d432-460b-a2e8-da18e71e0bab.png)
![image](https://user-images.githubusercontent.com/3066000/215269700-9055526b-806e-470c-a84e-5ce2e18a8a79.png)
![image](https://user-images.githubusercontent.com/3066000/215269721-b82456a6-7b4b-4eca-b5ef-070c6c453fd4.png)

![image](https://user-images.githubusercontent.com/3066000/215268856-cab54847-ce8b-43ee-aed0-8d717af9f2d4.png)
![image](https://user-images.githubusercontent.com/3066000/215268868-3d26368e-9fec-437c-b1a7-2a36d3e9af33.png)
![image](https://user-images.githubusercontent.com/3066000/215268915-dd399fa7-3fc8-44d0-8016-abadbce64f1f.png)
![image](https://user-images.githubusercontent.com/3066000/215268937-9375d7f0-5aaf-4184-bbcf-7d6ecaa6531c.png)
![image](https://user-images.githubusercontent.com/3066000/215268985-0cfe6157-4441-4023-99a7-7d7ad58d1772.png)
![image](https://user-images.githubusercontent.com/3066000/215269004-66310dcf-bcba-4f20-8438-760f7c5d0584.png)
![image](https://user-images.githubusercontent.com/3066000/215269093-887ca373-8b44-4c1c-b216-84dfda0e06cd.png)
![image](https://user-images.githubusercontent.com/3066000/215269102-260b61f5-4491-4d85-9da9-3f5e8e345336.png)
![image](https://user-images.githubusercontent.com/3066000/215269116-6de97d50-fc21-4f91-8d87-49d93df1407f.png)

I hope Carlos Guzman links this issue in https://github.com/cguZZman/plugin.googledrive

**Comment by cguZZman** [comment]
Kodi doesn't update addons from 3rd party repositories unless you explicitly allow it.

Just go to Setting > System > Add-ons, and then option "Update official add-ons from" select "Any repositories"
