### ISSUE TITLE
Undeletable Folders

### ISSUE THREAD

**Issue by forsomefun2** [cguZZman/plugin.googledrive#32]
This isn't the biggest deal for me at the moment. Since I don't plan on moving my folder soon.
The shows are 
Hunter X Hunter
Attack on Titan

But in general I've notice that sometimes these strm programs are creating folders that can not be deleted. 

From my research it seems like maybe it is adding something to the name that makes it invalid/impossible to creare for windows explorer, but since it was created with another program it exist

**Comment by cguZZman** [comment]
So the addon exported the strm files, and then you tried to delete the folder, and it didn't let you, correct? 
It's not related with the addon if that's the issue.
Was kodi open? Or did you open any strm file with another program? is it network shared?
Anyway, there are tools that can help you identify the program locking a file which prevents the folder to be deleted.
Not an addon issue tho.

**Comment by forsomefun2** [comment]
This is what I have while running dir /x

![image](https://user-images.githubusercontent.com/25670034/45582603-8878bb00-b878-11e8-8215-b0e84eb40dd5.png)  

Second Delete files Kodi is not running process closed in process manager
![image](https://user-images.githubusercontent.com/25670034/45582641-15237900-b879-11e8-954d-191ddde02cd5.png)

This is what I have after creating only the attack on titan folder
![image](https://user-images.githubusercontent.com/25670034/45583030-0f7d6180-b880-11e8-8df6-b1b88e82c14a.png)


It is impossible to delete until
rd /s /q /path 

or 
del /path

is ran
