### ISSUE TITLE
Video not playing on Nvidia shield

### ISSUE THREAD

**Issue by subexx** [cguZZman/plugin.googledrive#321]
None of my videos playing on the addon. No error. It's just stuck. Tried on two nvidia shield pro's with same result.Bit it works on firestick as well as Google tv.

**Comment by subexx** [comment]
Solved

**Comment by titooo7** [comment]
> None of my videos playing on the addon. No error. It's just stuck. Tried on two nvidia shield pro's with same result.Bit it works on firestick as well as Google tv.

Same for me. It used to work back in the day. How did you solve it?

**Comment by subexx** [comment]
It started working after disabling http2. 
```
#  /storage/.kodi/userdata/advancedsettings.xml
  <network>
    <disablehttp2>1</disablehttp2>
  </network>
```
