### ISSUE TITLE
Screen is loading and loading and loading 

### ISSUE THREAD

**Issue by Mangalambika** [cguZZman/plugin.googledrive#335]
**Describe the bug (🔴)**

A clear and concise description of what the bug is : For me when trying to play a video it starts to load with the loading circle and it's happening forever no further improvement donno what could have happened, having a Android 12 tv os in mi box, kodi 20.2, installed your repository to my kodi from zip file for 20+ kodi users 

**To Reproduce (🔴)**

1. Go to 'open an account (my drive) containing data like video photos etc.. from where usually users navigate to see their files in it '
2. Click on 'a video or any other files to open'
4. 'For me when trying to play a video it starts to load with the loading circle and it's happening forever no further improvement donno what could have happened'

**Your debug log file (Required :red_circle:)**

Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by Tanmayshetty** [comment]
Check the pinned issue and the fix comment here 

https://github.com/cguZZman/plugin.googledrive/issues/255#issuecomment-1076477307

I suggest using the below Kodi addon to make the changes on the TV

https://github.com/abratchik/script.unlock.advancedsettings

Need to add the following XML content inside *advancedsettings.xml* file

``` 
<advancedsettings version="1.0">
    <network>
      <disablehttp2>true</disablehttp2> 
    </network>
</advancedsettings>
```

**Comment by ClassickTech** [comment]
> Check the pinned issue and the fix comment here
> 
> [#255 (comment)](https://github.com/cguZZman/plugin.googledrive/issues/255#issuecomment-1076477307)
> 
> I suggest using the below Kodi addon to make the changes on the TV
> 
> https://github.com/abratchik/script.unlock.advancedsettings
> 
> Need to add the following XML content inside _advancedsettings.xml_ file
> 
> ```
> <advancedsettings version="1.0">
>     <network>
>       <disablehttp2>true</disablehttp2> 
>     </network>
> </advancedsettings>
> ```

I am having the same issue on Android TV 12. Step 2 in this link https://github.com/abratchik/script.unlock.advancedsettings says to "Navigate to System/Add-ons/Install from the zip file and specify the file downloaded on the previous step." but I don't see "install from zip" anywhere. Please advise. Thanks
