### ISSUE TITLE
Loading and Loading but not playing

### ISSUE THREAD

**Issue by ClassickTech** [cguZZman/plugin.googledrive#338]
Videos just stopped playing the other day and now they just get stuck on the loading symbol.

I am on Onn UHD 2023 box with Android TV 12. I was told to go to  android/data/org.xbmc.kodi/files/.kodi/userdata/advancedsettings.xml and add: 

`<advancedsettings version="1.0">
    <network>
      <disablehttp2>true</disablehttp2> 
    </network>
</advancedsettings>`

But that location is not accessible on Android TV 12 (with it's new stupid permissions) without root.

So I decided to sideload the repository.abratchik-1.0.2.zip from https://github.com/abratchik/script.unlock.advancedsettings. I am able to go to Network > and check next to disablehttp2 but the setting never sticks (see pic). Any help with this?
![PXL_20231217_184250105](https://github.com/cguZZman/plugin.googledrive/assets/90914116/80dcdc9a-84d9-44ba-90ab-77b1e78c33f7)

**Comment by kamillopl** [comment]
Isn't it possible to make changes directly in the Google Drive addon? I have same issue on Google Chromecast HD, I can't create advancedsettings.xml file because I have no permissions.

**Comment by ClassickTech** [comment]
No one has seem to come up with a fix for google and it's stupid permission update

> Isn't it possible to make changes directly in the Google Drive addon? I have same issue on Google Chromecast HD, I can't create advancedsettings.xml file because I have no permissions.

**Comment by kamillopl** [comment]
@ClassickTech I found a solution on Reddit. It's very easy. Just use built-in File manager from Kodi. Yes, it's the whole thing.
Kodi have permissions to write on its own directory, so all what anybody intrested have to do is download advancedsettings.xml file on Android TV, put it in e.g. Downloads folder, run Kodi, go to File manager, on the left navigate to Downloads folder, on the right choose Profile directory, then go back to the left, choose advancedsettings.xml file, hold OK or press OPTIONS button on the remote, click copy. If file is copied now you have to restart Kodi and it will work.

It's a pity that I found a solution when there is the problem with account authentication, but if you already have verified account on different Kodi instance, then you can just copy _accounts.db_ file to _Profile directory/addon_data/plugin.googledrive_ and you will have your accounts added and verified.

**Comment by ClassickTech** [comment]
@kamillopl Yes figured it out shortly after I posted. I just forgot to come back here with the answer. Glad you got it sorted out.
