### ISSUE TITLE
Google photos is in extremely low resolution

### ISSUE THREAD

**Issue by mgilden** [cguZZman/plugin.googledrive#34]
When using photos, images appear lower resolution that usual. When I get information on a particular file (using C on the keyboard), it has been reduced to something like 500pixels- Not crisp or clear at all compared to my laptop on the same TV monitor.  Is it pulling large thumbnails? How do I get the larger higher resolution images?

**Comment by cguZZman** [comment]
Fixed now with version 1.2.12
