### ISSUE TITLE
This application is blocked (Esta aplicación está bloqueada) issue

### ISSUE THREAD

**Issue by pordeciralgo** [cguZZman/plugin.googledrive#341]
I believe it's not really a bug but a change from Google's side.

When trying to grant permissions from the Google account, a "This application is blocked" error appears and it's not possible to continue with the process.

![Esta aplicacion está bloqueada 23 18 51_74ca023a](https://github.com/cguZZman/plugin.googledrive/assets/23632754/5fedae2a-bd28-4b9c-99fd-402acb60a956)

**Comment by yusuoke** [comment]
I'm having trouble too. Will it be possible to use it in the future?

**Comment by adrianm86** [comment]
I'm having the same case of error blocking. Any solution?

**Comment by TheGhostboi64** [comment]
I’m also having the same thing. Hopefully a fix will be released!

**Comment by iamat8080** [comment]
https://youtu.be/zwYaNJFknEw?si=o8oQxM_zk0heiJz1

**Comment by hrshlmhjn** [comment]
This video not working

**Comment by jmg999** [comment]
@iamat8080 
> https://youtu.be/zwYaNJFknEw?si=o8oQxM_zk0heiJz1

Could you please explain where to use the created app password? I was able to create it, but I have no idea where to input it. Thank you.

**Comment by iamat8080** [comment]
@jmg999 @hrshlmhjn 
There is mixplore app you can use to login gdrive and play videos just add storage and select gdrive

**Comment by jmg999** [comment]
@iamat8080 Thank you for your response.  I assume that you meant "MiXplorer," yes?  That gets installed directly on, in my case, the Firestick, and not within Kodi, correct?

**Comment by iamat8080** [comment]
Yes not within Kodi you can use bubbleupnp app for firestick have gdrive and other cloud access on few click remote play
@jmg999

**Comment by jmg999** [comment]
@iamat8080 Do I need to use the BubbleUPnP app in order to install MiXplorer, or can I use MiXplorer on its own?

**Comment by Varun23102002** [comment]
Please guys comment the alternative way to play Google drive video files in phone and Tv

**Comment by iamat8080** [comment]
@jmg999 both are different apps 
For same purpose 
Gdriver or another cloud to tv

**Comment by hrshlmhjn** [comment]
@iamat8080 , bubbleUpnp resolves the issue , I can stream videos on my android , can you suggest any other app which can be installed on fire tv directly where I will connect Gdrive. Bubbleupnp does not support fire tv yet.

**Comment by iamat8080** [comment]
I guess it does support firetv stick check in settings and mixplore can do
the trick too

**Comment by Varun23102002** [comment]
![Screenshot_20240421_215854](https://github.com/cguZZman/plugin.googledrive/assets/99336510/60974b9f-6660-4e86-ba62-dda4c134ea1e)
Use this player work on both tv and phone

**Comment by alarno** [comment]
Same here!

**Comment by jmg999** [comment]
@iamat8080 Thank you greatly for the information.  I'll give MiXplorer a try first.  I was hoping to install something directly into Kodi that would access Google Drive, but it's not the end of the world to have to install directly to the Firestick.  For others asking, here's a YouTube video I found to install MiXplorer directly to the Firestick: https://www.youtube.com/watch?v=n80DhoqWMvM

**Comment by alarno** [comment]
> I believe it's not really a bug but a change from Google's side.
> 
> When trying to grant permissions from the Google account, a "This application is blocked" error appears and it's not possible to continue with the process.
> 
> ![Esta aplicacion está bloqueada 23 18 51_74ca023a](https://private-user-images.githubusercontent.com/23632754/322148159-5fedae2a-bd28-4b9c-99fd-402acb60a956.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Mjg1MDgsIm5iZiI6MTcxMzcyODIwOCwicGF0aCI6Ii8yMzYzMjc1NC8zMjIxNDgxNTktNWZlZGFlMmEtYmQyOC00YjljLTk5ZmQtNDAyYWNiNjBhOTU2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE5MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNTI2NTM0YmU4YTY2NzJjMTZlMmY1M2FmMTEyOThkMWZhNDNkMTZlNmQ5ZTZiNjIyZTBjNTgwMjcxNzg5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h7NGZjcQ-48PUdYNB9Vw1j7H--rmw9-RqEO_mcDfFDU)

Anything to solve it? did you find any solution?

**Comment by alarno** [comment]
> @iamat8080 Thank you greatly for the information. I'll give MiXplorer a try first. I was hoping to install something directly into Kodi that would access Google Drive, but it's not the end of the world to have to install directly to the Firestick. For others asking, here's a YouTube video I found to install MiXplorer directly to the Firestick: https://www.youtube.com/watch?v=n80DhoqWMvM

Don't waste your time, I tried MiXplorer and it is not like kodi, it is a sistem to manage files, but you cannot play like kodi...I will investigate more options, and come back if anything works!

**Comment by cguZZman** [comment]
Hi all,
I checked my email and Google sent me one saying the application violates the "[AUP-3: Always ask permission](https://developers.google.com/photos/library/guides/acceptable-use#permission)" policy. :man_shrugging:

I will try to resolve it. It could take some time.

I will close this issue and keep open https://github.com/cguZZman/plugin.googledrive/issues/342 to track the progress
