### ISSUE TITLE
Default video resolution setting

### ISSUE THREAD

**Issue by chorong761** [cguZZman/plugin.googledrive#36]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to play the original video stream is to enable the selection option but that is kind of annoying since I would have to choose everytime.

**Describe the solution you'd like**
Have an option to set the default stream e.g. original stream

**Comment by cguZZman** [comment]
By default the original stream format is played. Just uncheck the option to always ask for the format

**Comment by cguZZman** [comment]
If you have the option unchecked and the video is not playing, create bug report including your debug log file.

**Comment by cboswald95** [comment]
> By default the original stream format is played. Just uncheck the option to always ask for the format

Is there a way to set the default to another quality? Like google transcode's 1080p? Alternatively a way to select the quality when necessary, like with a context menu option, would be a great addition.  It was available in the other gdrive addon so hopefully it wouldn't be too difficult to implement, and it'd make the experience of using it a lot more fluid.

**Comment by cguZZman** [comment]
Not implemented yet, but it's in the list of enhancements. No ETA.

**Comment by cboswald95** [comment]
Cool, just happy to hear this addon is still being actively developed
