### ISSUE TITLE
nfo file downloading possible?

### ISSUE THREAD

**Issue by jmez11** [cguZZman/plugin.googledrive#37]
All of my media has kodi nfo files.  It would be great if your plugin could download those when it is creating folders/strms.  It would help as kodi doesn't always match correctly, and my nfo files are set up correctly.

So, when scraping through a directory's contents:
If there is a file named tvshow.nfo, copy it into the strm location.

When creating a strm file:
See if there is a file named `<video>`.nfo.  If there is, copy it to the strm location

When deleting a strm file:
If there is a matching `<video>`.nfo, delete it.

Monitor the for changes in the nfo files and update any downloaded nfos.

**Comment by setzke** [comment]
Yes please add support for grabbing either [same name as movie].nfo or movie.nfo when grabbing strm files.  I'd love for Kodi to be able to tell me the quality of my movies.

**Comment by z3us** [comment]
I support this too

**Comment by xybydy** [comment]
@cguZZman this is closed
