### ISSUE TITLE
stream resolution in menu

### ISSUE THREAD

**Issue by 4luk** [cguZZman/plugin.googledrive#38]
Hey @cguZZMan thanks again for great addon!
Was thing of a improvement if you get a chance
So I unchecked "always ask for the stream format before play" because I always just choose original format. but some times when my internet is slow I need to play in a lower resolution. So I have to go through the menu and check the "always ask for the stream format before play" which is a bit of a pain. just wondering is it possible to add a option in the long press menu on a movie/show where it says "play" "information" "marked as watched" etc with the new option "choose resolution"
Thanks again

**Comment by cguZZman** [comment]
Option added in latest version.
