### ISSUE TITLE
Google Photos integration

### ISSUE THREAD

**Issue by egi78** [cguZZman/plugin.googledrive#39]
Hi cguZZman,
in the description of the addon is written "Google Photos support" but once installed when I come into my google account I only see my "Google Drive" and not also "Google Photos" where is stored all my photo library. Where is the same of https://photos.google.com/ in this addon?
Thanks

**Comment by cguZZman** [comment]
Go to:
- Add-ons
- Picture add-ons
- Google Drive
- <Your account>
- Google Photos

It's very important you enter the addon thru the Picture add-ons option, otherwise you won't see the Google Photos menu.

**Comment by egi78** [comment]
thanks Carlos, I' did as you suggested and now it works fine!
but, in my Google Photos library I saved, mixed in each album, relevant photos and also videos and I can see both if I browse Google Photos by web; through your addon in Kodi I only see photos contained in each album and not the related videos... how can I browse and see also the videos contained in each album, together?
Finally, one detail. How can I sort the albums by date from the most recent? (I have more than 40 albums and it's not very useful scroll down all the albums to go the most recent.
If the features above are not actually implemented, do you think you will make them available in the next  issue?
Very thanks, good work!

**Comment by sticker592** [comment]
This didn't work for me. Are the steps different now that photos and drive don't sync anymore starting today?
