### ISSUE TITLE
I can't see photos

### ISSUE THREAD

**Issue by iwanttobefreak** [cguZZman/plugin.googledrive#4]
Hello.
I can't see jpg photos. I can browse folder into my drive but I can't see any photo.
Thanks

**Comment by cguZZman** [comment]
Did you open the addon thru the correct menu?
If you want to see photos, you have to enter thru the Pictures > Pictures add-ons option. This will filter your files to display pictures only.
If you want music, you have to do it thru the Music option.
Let me kwow

**Comment by iwanttobefreak** [comment]
Excuse, it's ok.
Through menu pictures I can see the photos.
Thanks!!!!
