### ISSUE TITLE
video in "Google Photos" albums and album sorting

### ISSUE THREAD

**Issue by egi78** [cguZZman/plugin.googledrive#40]
In my Google Photos library I saved, mixed in each album, relevant photos and also videos and I can see both if I browse Google Photos by web; through your addon in Kodi I only see photos contained in each album and not the related videos... how can I browse and see also the videos contained in each album, together?
Finally, one detail. How can I sort the albums by date from the most recent? (I have more than 40 albums and it's not very useful scroll down all the albums to go the most recent.
If the features above are not actually implemented, do you think you will make them available in the next issue?
Very thanks, good work!

**Comment by user135711** [comment]
Set google drive to display google photos, then drag the folder into your google drive. (It is still stored in photos but organized to display now in drive

**Comment by Dreamer-4pda** [comment]
Maybe have easy way to play video from albums?

**Comment by macamba** [comment]
Hi all,
This issue was opened more than 1 year ago, user135711 gave one solution but it doesn't work since July because gdrive and Google photos was separated definitely so will be this solved soon?

Regards

**Comment by cguZZman** [comment]
Videos can be played in Google Photos section now. 
Will do the sorting fix later.

**Comment by farhanito** [comment]
> Videos can be played in Google Photos section now.
> Will do the sorting fix later.

Pardon me, i still can't see videos in Google photos.

Accessing GoogleDrive addon through Video Add-on, there's no Google Photos section..

Accessing GoogleDrive addon through Picture Add-on, only image files listed.

Thanks

**Comment by cguZZman** [comment]
attach your debug log file

**Comment by farhanito** [comment]
Here's my debug log 

https://paste.kodi.tv/pixidonuzi

I opened a folder (album) that contains only videos.

**Comment by cguZZman** [comment]
Videos should be visible in latest version from my repo.
Albums do not have a creation or any date to be able to sort them. So it is not possible for the moment as is with current google photos api.
