### ISSUE TITLE
Unable to set .strm export destination on Windows

### ISSUE THREAD

**Issue by dabinn** [cguZZman/plugin.googledrive#44]
**Describe the bug**
The file path of 'Select destination folder' dialog is un-selectable on Windows.
The default is android style path '/storage/emulated/0/Androiod/data/org.xbmc.kodi'

**To Reproduce**
1. Any folder
2. Click "Export to .strm files..."
3. 'Select destination folder' dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/21699064/49024925-7ea6f880-f1d5-11e8-9a02-ed15721e9a90.png)

**Comment by dabinn** [comment]
Sorry, my bad.
The issue is caused by myself, I copied a sources.xml from other Android device.

**Comment by cguZZman** [comment]
No problem. I'll close this issue then.
