### ISSUE TITLE
HTTP proxy support for playback

### ISSUE THREAD

**Issue by k9ketan** [cguZZman/plugin.googledrive#47]
Currently the addon does not support playback on an http proxy, even though it is able to scan the library on the proxy set on Kodi.

So, would be great if it somehow can be integrated, as people who are within restricted networks within college campuses or workplaces are unable to use the addon.

**Comment by cguZZman** [comment]
this is a kodi configuration. check https://kodi.wiki/view/Settings/System/Internet_access
