### ISSUE TITLE
Support for Service Account

### ISSUE THREAD

**Issue by ryanjerskine** [cguZZman/plugin.googledrive#48]
Would it be possible to support a service account? I would prefer to share a 'Media' folder as a readonly with a service account and then add that to Kodi.

**Comment by cguZZman** [comment]
It should be. I see they have OAuth support. I don't have a service account though, so a PR is welcome.

**Comment by cguZZman** [comment]
since service accounts are special accounts, until somebody shares one, won't be able to try an implementation.
