### ISSUE TITLE
create a routine that exports STRM's every X time

### ISSUE THREAD

**Issue by cguZZman** [cguZZman/plugin.googledrive#5]
https://forum.kodi.tv/showthread.php?tid=324784&pid=2687471#pid2687471

**Comment by raycekar** [comment]
I want to add in a possible export STRM's on startup with the option to sync library after it has finished.  So every time you start it, will get the latest and greatest.

**Comment by cguZZman** [comment]
Good idea. I'll add that option in the current change.

**Comment by cguZZman** [comment]
Implemented in latest version.

**Comment by qazero** [comment]
Would it be possible to do this on a predefined configurable interval instead of only on start? This would be better for users using HTPCs that don't close Kodi.

**Comment by raycekar** [comment]
@qazero yes, go and export the folder you like and a configuration menu will come up.  I believe if you check the last option, you can add when to run the export.
