### ISSUE TITLE
Audio tracks assigned automatically like the subtitles

### ISSUE THREAD

**Issue by AlgusDark** [cguZZman/plugin.googledrive#52]
**Is your feature request related to a problem? Please describe.**
Would be nice to have tracks assigned automatically like the subtitles

**Describe the solution you'd like**
I've read that it's possible to stream extra audio-track directly with kodi. For the moment, googledrive plugin reads STR files... solution should read additions audio tracks and give them as source to kodi

**Describe alternatives you've considered**
Creating an m3u with track audio.

**Additional context**
I've never done anything with python, but I'll read the code to see how STR are found and loaded in kodi. If you can point me lines, would be cool.

**Comment by cguZZman** [comment]
Subtitles are assigned to a ListItem here: https://github.com/cguZZman/script.module.clouddrive.common/blob/97fd4d9a69a980c011693e2acc87f171252faaaa/clouddrive/common/ui/addon.py#L655

Try to collect more information on how an extra audio-track can be added to a ListItem or to the Player and we can check the feasibility of this enhancement.

**Comment by cguZZman** [comment]
closing this issue due to no response. 
audio tracks can be selected in kodi once playing if the video has multiple audio tracks
