### ISSUE TITLE
Too slow source error message on Nvidia Shield TV

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#54]
**Describe the bug**
I have 2 devices running this add-on:

1. OnePlus 6 with lastest Android 9 and latest Kodi and latest add-on version.
2. Shield TV 2017 with all the latest Android/Firmware running the latest Kodi and latest add-on version. This is my main media player - it is the main movie player in my Home Theater. 

I use the same userid to connect the GDrive add-on o both devices. 

I have both connected to the same Asus Rog Rapture Router - the smartphone using AC Wireless Network and Shield TV with Gigabit cable. The router is connected to the ISP ONT. 

Currently I've got 200mbps down 100 mbps up connection to the internet.

I run any video on the Smartphone without any problem, any delay/stop. Things just works great there! 
  On the Shield TV I got the "Slow connection to play/stream" error every other 3 minutes or so! I can't even use it anymore.

What can I do to make the Shield TV problem go away?! 

**To Reproduce**
1. Setup the GDrive Add-on from the Kodi Official Repository on Kodi Leia (18.1) in the Nvidia Shield TV running the latest firmware version.
2. Play any 4K video from the GDrive movie source you have just set up. 
3. After a couple of minutes the video freezes and you get a cache icon with a loading percentage icon that never goes goes beyond 0%

**Your debug log file**
1. Here is the log using Aura skin and wireless (I thought it may have been the cable, don't know - just want to use the same wireless AC as the smartphone to test) connection to the internet: https://paste.kodi.tv/nekuyihono.kodi
 
2. Here is the log after changing the skin to the default one and connecting Shield again to the router using the cable: https://paste.kodi.tv/wasuvomubo.kodi
 
3. And here is the log from my phone - I played the same movie for about 25 minutes without having ANY issues: okoxepajap.kodi (paste)
https://paste.kodi.tv/okoxepajap.kodi
 
4. Here is the media information of the movie I used to reproduce the error:  https://paste.kodi.tv/yovapogigo

**Screenshots**
To add later in case it is required - maybe

**Comment by cguZZman** [comment]
I really appreciate your detailed explanation. 
As I commented before, the slow source error is a problem with your internet connection or a problem with your device. So in this case seems like an issue with your Shield TV.
All the addon does is to get the correct URL from google and pass it to kodi to be played. Kodi then plays it directly from google's servers.
It looks like the shield tv is not being capable of play your 4K video file.
Have you tried playing the video file with a lower stream format? I'm pretty sure the error will be gone.

**Comment by cguZZman** [comment]
I'm closing this issue since is out of the scope of the addon. But if you want, keep us posted about your issue so others can have the information.

**Comment by VsnGamer** [comment]
@cguZZman For me the problem appeared out of nothing(without config changes, etc, just one day its working well and the next day it didn't) thats why I thought google or kodi changed something on their end.
Thanks for looking into this.

**Comment by gsantosoliver** [comment]
> I really appreciate your detailed explanation.
> As I commented before, the slow source error is a problem with your internet connection or a problem with your device. So in this case seems like an issue with your Shield TV.
> All the addon does is to get the correct URL from google and pass it to kodi to be played. Kodi then plays it directly from google's servers.
> It looks like the shield tv is not being capable of play your 4K video file.
> Have you tried playing the video file with a lower stream format? I'm pretty sure the error will be gone.

Hi @cguZZman 
Thanks for the response! 

About the possible root causes of the problem I am facing accordingly the your comment above: my internet connection or my Shield TV. Please considerer the 2 use cases/scenarios below:
1. I can play ANY movie (including the one that I used for this testing) when I use my local NSF server as source. There is no slowness at all, it all runs smooth as expected. So we can tick off the "shield tv is not being capable of play 4k video file" form the list :)
2. As proven in my opening remarks, I use another device connected to the same network (my phone) router and using the same ISP without any problem. To be honest, nertworking-wise I thought I could have a problem on my phone since it is not connected using cable to the router. 

Would you agree it can not be neither the Shield TV or the ISP the cause of the problem since at least one of the two scenarios above must necessarily failed if that was true? :)

I've noticed you had addressed similar problem before by adding some cache management to the plugin as this comment https://github.com/cguZZman/plugin.googledrive/issues/8#issuecomment-415868549 intends - would this be related? 

Thank you for your help and support - I really appreciate it!

**Comment by gsantosoliver** [comment]
@cguZZman Oh, one more really important thing to consider: the Kodi version itself (or some incompatible thing between the add-on, dependencies wih the new Kodi version). Check this out:

1. I have unstalled Kodi 18.1 completely from Shield TV and reinstalled from scratch. The only add-on I had running was the GDrive and its dependencies, the problem happened.

2. I removed Kodi 18.1 again and installed the version 18. Installed the plugin, set it up and ran the same movie. It worked: 12 minutes without getting stuck.

Here is the log one running it on v18 without any problem: https://paste.kodi.tv/anecovuluj.kodi 

Would you please check?

Thanks

**Comment by SoulRipper888** [comment]
Hello, I have the same problem on my Shield TV 2017 devices since I updated to Kodi 18.x. **Never** had this before.
Device 1: 1000mbps down / 500mbps up (cable connection to the router)
Device 2: 100mbps down / 10mbps up (cable connection to the router)
At the moment, the workaround is to go back to Kodi 17.x
Best regards.

**Comment by cguZZman** [comment]
Looks like it could be a Kodi issue then. As I said before, the addon does not play any file. It just pass the URL to Kodi so it can play it.

**Comment by SoulRipper888** [comment]
> Looks like it could be a Kodi issue then. As I said before, the addon does not play any file. It just pass the URL to Kodi so it can play it.

Yes, I'm sure that's a Kodi issue. I have the same problem with other addons & Kodi 18+.

**Comment by gsantosoliver** [comment]
@cguZzman would you please tell me exactly how I can play a movie file through a URL without using the plug in? I want to verify whether or not Kodi will play it since I believe the problem can also be on one of the libraries that you use to support Google Drive since playing the same content from another source (like a NAS running nfs or smb) in Kodi 18+ works just fine.

**Comment by gsantosoliver** [comment]
Issue has been fixed on Kodi 18.4 ;)

**Comment by cguZZman** [comment]
Glad to know. :)
