### ISSUE TITLE
Library does not auto-update upon new content on the Cloud when using .strm exported files

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#56]
**Describe the bug**
The export to .strm features two options to that say "Update library after export" and  "Watch for changes in Cloud". My expectation is that. if both options are marked, a new folder/file added to the source in the Cloud (GDrive) will trigger the process to export the .strm and update the library. The problem is that it won't happen until I navigate manually to the folder which is updated using the Google Drive add-on, open the "Google Drive - Export to .strm file..." interface and click on Save and Run button.  
**Important information:** the issue happens when the content is in a team drive. I tested with content located in the "Shared with me" location and it worked as expected.

**To Reproduce**
1. Using the "Google Drive" add-on to navigate to the folder you that contains your movie content.
2. Open the option export to .strm files...
3. Set it up the "Destination" location (take note of that) and check the options "Update library after export" and  "Watch for changes in Cloud" and click on Save and Run
5. Wait for the export process to finish
4. Setup a new Movie Source using the path to the exported folder on step 3, make sure you set the correct content type (Movie) and set ip to the scan and add to library. Wait for the process to finish.
5. At this time, all your Movies should be in the Movies menu.
6. Add a new Movie to the Cloud. Make sure it is accessible to the plug-in by navigating to the folders until you can find it (I even played it - the movie I used to test is the Philadelphia). 
7. At this point the expectation was that the movie would appear in the Movies section, however it does not happen I navigate manually to the folder which is updated using the Google Drive add-on, open the "Google Drive - Export to .strm file..." interface and click on Save and Run button.  
8. Only after the manual intervention the new Movie (I used Philadelphia) appeared. 

**Your debug log file**
Here is the log file (I had to attach it since the paste feature in kodi domain has a limit): 
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/2948403/kodi.log)

**Screenshots**

**Comment by cguZZman** [comment]
Was your movie Philadelphia added inside the folder that you exported?

**Comment by gsantosoliver** [comment]
> Was your movie Philadelphia added inside the folder that you exported?

Hi @cguZZman - no, that folder was not included in the first manual export - it did not even existed in the source folder in GDrive. I wanted to make a real life test and added it after the first export and waited/expected it to be picked up by an automated process as the options "Update library after export" and "Watch for changes in Cloud" suggest it is available. :)

**Comment by cguZZman** [comment]
If you added your movie inside the folder that was exported first, it should be picked up and exported automatically. That's the whole point of the functionality.
I'll validate you log file later.

**Comment by gsantosoliver** [comment]
> If you added your movie inside the folder that was exported first, it should be picked up and exported automatically. That's the whole point of the functionality.
> I'll validate you log file later.

@cguZZman ok, let me add here the expectation (maybe it is not what it does): after setting up the .strm files export and run it for the first time, if the option "Watch for changes in Cloud" is activated it would pick up automatically (without the need to run the export again) any new folder that is added in the Google Drive source and refresh the exported folders. At the end of this process, if "Update library after export" is enabled, it would kick off the movie scrapping process.

The idea is that, if all is setup properly, new content will appear automatically in the Movies section. 

Does it make sense?

**Comment by cguZZman** [comment]
I think we are talking in circles here, but yeah, that's the intended functionality when those 2 options are activated.
I just need to clarify that when you say "any new folder that is added in the Google Drive source", it should mean any new folder that is added inside the google drive folder that you already exported (and therefore watching).
If you add a new folder/movie anywhere in your entire Google Drive apart from the one you are watching, for example in your root folder or any other folder, it won't work. You are watching an specific folder and only modifications to that folder or its content will be taken and automatically replicated in your local drive.

**Comment by gsantosoliver** [comment]
> I just need to clarify that when you say "any new folder that is added in the Google Drive source", it should mean any new folder that is added inside the google drive folder that you already exported (and therefore watching).

That's exactly the case! The new content added is a subfolder of the folder already set in the .strm exports....

> If you add a new folder/movie anywhere in your entire Google Drive apart from the one you are watching, for example in your root folder or any other folder, it won't work. You are watching an specific folder and only modifications to that folder or its content will be taken and automatically replicated in your local drive.

Oh yeah, we are on the same page here.

**Comment by gsantosoliver** [comment]
@cguZZman - important information abut this issue I've noticed today: it only happened to me when the content is a team drive. It works properly when the data source is in the "Shared with me" folder.  Let me know if you need the log from a working use case.

**Comment by gsantosoliver** [comment]
> @cguZZman - important information abut this issue I've noticed today: it only happened to me when the content is a team drive. It works properly when the data source is in the "Shared with me" folder. Let me know if you need the log from a working use case.

Any updates on this one?

**Comment by cguZZman** [comment]
Not yet. I'll post a comment once I validate it.

**Comment by Animizio** [comment]
Long time ago guys... Any news? :)

**Comment by RascaL-O** [comment]
Same happening to me as well sadly. Was looking for workaround until I saw this issue wasn't just for me and been around for more than a year. I hope there's an update about this :)

**Comment by camo200sx** [comment]
Any word on this? I am using a team drive also and the files do not update automatically

**Comment by RascaL-O** [comment]
> Any word on this? I am using a team drive also and the files do not update automatically

Hi as per the latest version developer released more than a month and half ago, this issue has been resolved. You just need to add the repository of the @cguZZman into kodi and update it from there.

**Comment by camo200sx** [comment]
Excellent. Thanks pal. I did notice that having set a schedule to export etc at midnight daily, the next day items have shown up :)
I'll check I have the latest
Thanks again

**Comment by cguZZman** [comment]
fixed in last version
