### ISSUE TITLE
Add Support to Bluray Folders when using export strm files

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#58]
**Describe the bug**
  I have one Bluray folder in my movie source that is messing up the Movies library after the scraper runs. The problem is that Kodi is displaying all kids of crazy stuff after the movie scrapper runs:
- Lots of movies called 'The Last Playlist'
- Movie called 'The Certificate'
- Another called 'Kung Fu Hustle'
- Lots of movies called 'The Stream'

**To Reproduce**
1. Make sure you have the Google Drive add-on setup properly with an account that has at least one Bluray Movie Folder with the structure as follows:
```
 The.Devil.Wears.Prada.2006.1080p
 - BDMV
 - CERTIFICATE
 - SLYVM
```
2. Make sure you are using the Export to .strm files feature that included the Bluray movie folder on step 1  and you have exported it already.
3. Make sure you have a Movie source setup to use the folder structure exported on step 2
4. Run the movie scraper feature when setting up the movie source, wait for it to complete and go check the Movie section and check for Movie titles such as  'The Certificate',  'Kung Fu Hustle', 'The Stream', 'The Backup Plan' etc....

**Your debug log file**
Here is the log file (its so big that https://paste.kodi.tv/ could not handle it): https://goo.gl/mJLGmf 

**Screenshots**
![Screenshot_20190312-002904](https://user-images.githubusercontent.com/31668431/54173248-f1c03c00-445f-11e9-9fa1-32f64dbe211c.jpg)
![Screenshot_20190312-002912](https://user-images.githubusercontent.com/31668431/54173277-08ff2980-4460-11e9-9e4c-0abdbb801ee9.jpg)
![Screenshot_20190312-002920](https://user-images.githubusercontent.com/31668431/54173285-10bece00-4460-11e9-95cd-4a0fe59f77b9.jpg)
![Screenshot_20190312-002924](https://user-images.githubusercontent.com/31668431/54173292-161c1880-4460-11e9-80c4-8472a6d98c7f.jpg)
![Screenshot_20190312-002939](https://user-images.githubusercontent.com/31668431/54173293-161c1880-4460-11e9-920a-7ba7be576156.jpg)

**Additional Information**
A Tem-Kodi Member whose id is Karellen (https://forum.kodi.tv/member.php?action=profile&uid=379004) has made the following observations that may help solve the issue:
1. https://forum.kodi.tv/showthread.php?tid=341905&pid=2832788#pid2832788
> That it is not a true Bluray rip.
> 
> There should be the following file...
> The.Devil.Wears.Prada.2006.1080p/BDMV/**index.bdmv**
> 
> Instead you have...
> The.Devil.Wears.Prada.2006.1080p/BDMV/**index.bdmv.strm**
> 
> As Kodi cannot find the correct file, it does not recognise this as a bluray folder and instead is just trying to scrape all the video files in the structure. You will have to figure out how you made that error.

2. https://forum.kodi.tv/showthread.php?tid=341905&pid=2832815#pid2832815
I asked
> Do you think this is something I need to figure out with the Google Drive add-on's developer instead?

He said:
>I would guess yes, ask the add-on developer how to prevent that modification.

Let me know if further information is needed.

**Comment by cguZZman** [comment]
Thanks for the report. I'll add this to the list for futures fixes. 
Don't hold your breath tho. Not a lot of time available right now.
If anyone wants to submit a PR, it'll be welcome.

**Comment by gsantosoliver** [comment]
> Thanks for the report. I'll add this to the list for futures fixes.
> Don't hold your breath tho. Not a lot of time available right now.
> If anyone wants to submit a PR, it'll be welcome.

Thank you for the reply and support. I have created the Feature Request #60 - please check and let me know if further details are required.

**Comment by gsantosoliver** [comment]
> If anyone wants to submit a PR, it'll be welcome.

Oh, I may have misunderstood you - what is a **PR**?

**Comment by gorman42** [comment]
Pull request. It means somebody writes the code needed and asks the mantainer of this repository to add that code to the add-on code.

**Comment by gsantosoliver** [comment]
> Pull request. It means somebody writes the code needed and asks the mantainer of this repository to add that code to the add-on code.

Oh, I wish I had the expertise and or skills to collaborate that way. I can volunteer to run tests/QA though! ;)

**Comment by cguZZman** [comment]
is the index.bdmv a big file? or smallish metadata file?

**Comment by cguZZman** [comment]
After researching the Kodi sources, bluray files needs to be local and with specific names. There is no way to make it work with strm files. The easy solution is to convert your bluray rip to any stream format.
