### ISSUE TITLE
create addons compatible with Jarvis

### ISSUE THREAD

**Issue by cguZZman** [cguZZman/plugin.googledrive#6]
https://forum.kodi.tv/showthread.php?tid=324784&pid=2689420#pid2689420

**Comment by cguZZman** [comment]
I just realized maintaining another version would be too much trouble.
Anybody willing to use it in Jarvis needs to do the installation manually.
Change the "xbmc.python" value in the addon.xml file to 2.24.0 (instead of 2.25.0) in both zips: the module script.module.clouddrive.common and in the plugin.googledrive zip and it should be good to go.

**Comment by amlopin** [comment]
Good morning,

I have followed your instruction to install your plugin in Jarvis and I got this error when the plugin is loading the items after clicking in My disk

Unknown error: ´module´object has no attribute ´parse´ Please try again.

Any help please?
Many thanks
