### ISSUE TITLE
Add Support to Bluray Folders when using export strm files 

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#60]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to the issue #58 

**Describe the solution you'd like**
As I user I would like to see in my bluray folders correctly displaed in the Movies interface 

**Describe alternatives you've considered**
The alternative up to now is to exclude the Bluray folder from the source to not to mess up the Movies interface - that is not good since the other way to get to that content type is not so intuitive as clicking on the Movie picture/fanart

**Additional context**
Screenshots of the problem can also be found on #58

**Comment by cguZZman** [comment]
We need only one issue in the list for the same problem. I'll close this one and keep the original.
