### ISSUE TITLE
Save playback progress not working properly with Kodi DSPlayer

### ISSUE THREAD

**Issue by gorman42** [cguZZman/plugin.googledrive#61]
**Describe the bug**
I know Kodi DSPlayer is an alternative branch, so I'll understand if the developer will decide to ignore this. It currently plays a vital role in being the only solution for Windows Kodi users wanting to playback HDR content with proper HDR passthrough.

I am seeing "intermittent" behavior with saving the playback progress. Some files save it, some files don't. I have seen this happen in the same Kodi session, with the same file.

When playback progress is not saved, I see this in logs:

```

12:51:16.645 T:25500   DEBUG: [plugin.googledrive][MainThread-25500]: ok to save dbid: 2
12:51:16.645 T:25500   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi DSPlayer\portable_data\addons\script.module.clouddrive.common\clouddrive\common\service\player.py", line 92, in onPlayBackStopped
                                                self.player_stopped()
                                              File "C:\Program Files\Kodi DSPlayer\portable_data\addons\script.module.clouddrive.common\clouddrive\common\service\player.py", line 96, in player_stopped
                                                self.saveProgress()
                                              File "C:\Program Files\Kodi DSPlayer\portable_data\addons\script.module.clouddrive.common\clouddrive\common\service\player.py", line 111, in saveProgress
                                                percent = position / total * 100
                                            ZeroDivisionError: float division by zero
                                            -->End of Python script error report<--

```

**To Reproduce**
Get Kodi DSPlayer from here: https://forum.kodi.tv/showthread.php?tid=223175

Add files to the database (I export .strm to do this).

Playback a file. Skip ahead 10 minutes or so. Stop playback. Save state could be saved or not. 

In this log  file https://paste.kodi.tv/ofuviloxax.kodi you can see the same file giving the error on lines 1980-1992 and later correctly saving the playback progress on lines 2454-2455.
I played the file the first time, stopped it, progress was not saved. I played it back a second time (from the beginning as the first time), stopped it, progress was saved.

**Comment by cguZZman** [comment]
Looks like DSPlayer has some weird behavior with its player events and therefore causing an error to the addon.
Can you test it with the latest version of Kodi?

**Comment by gorman42** [comment]
Unfortunately development is "stuck" at 17.6. Which currently isn't *too much* of a problem considering that the external filters and renderers are updated regularly by their respective authors.
What I am sure about is that it's never had problems saving the playback position on regular "local" playback or SMB or Google Drive through Google Drive File Stream.

**Comment by gorman42** [comment]
If there is *any* way I could help in finding a solution for this, please let me know.
I understand, as I wrote in the initial post, that this is an unofficial fork. But it seems so "close" to be working correctly that it feels as such a shame for it to be incomplete. :(

**Comment by cguZZman** [comment]
I'll keep this open to take a look on it later. No ETA though.

**Comment by gorman42** [comment]
There's nothing more I could ask for. Thanks for keeping an open mind on this.

**Comment by cguZZman** [comment]
There is a fix in the latest version from my repo. Test it and create a new issue if still happening.
