### ISSUE TITLE
Add the option to choose not to include the filename extension in a .strm file

### ISSUE THREAD

**Issue by diangelo84** [cguZZman/plugin.googledrive#63]
Hello, first of all thank you for this great work you do.
my question is, how to avoid that when exporting the strm do not put the extension of the file to the name ?.
Example: #SexPact (2018) .mkv.strm so it is by default, but I would like it to be like this #SexPact (2018) .strm, is it possible?

**Comment by cguZZman** [comment]
It's not possible right now. 
Is it causing an issue? or is just a personal preference?

**Comment by gorman42** [comment]
Personally I prefer it the way it currently is. If it was possible to achieve what diangelo84 is requesting, I'd like for it to be an option and not standard behavior.

**Comment by diangelo84** [comment]
No, it is not causing problems, but personally I can make things much easier, since I usually use emby as a database and it works wonders, but my problem arises when having the same movie in different versions.
Example: #SexPact (2018) [H.264-1080p] .mkv.strm
                 #SexPact (2018) [H.265-720p] .mkv.strm
in this case Emby creates two covers for me, one for each film.
instead #SexPact (2018) [H.264-1080p] .strm
                   #SexPact (2018) [H.265-720p] .strm
it detects it as the same movie in different versions, avoiding having the cover duplicated.

**Comment by gorman42** [comment]
I would ask Emby developers if there's something you could do to modify the regular expression that surely is involved in scraping for content.

**Comment by diangelo84** [comment]
Of course, but I think it would be much easier to remove the multimedia extension from the file name.
Even so, thanks for the suggestion.

**Comment by cguZZman** [comment]
I'll add this to the list of enhancements since it's not an error in the addon.

**Comment by gsantosoliver** [comment]
> Of course, but I think it would be much easier to remove the multimedia extension from the file name.
> Even so, thanks for the suggestion.

@diangelo84 I think you can write a cron job to run a schedule (maybe every 5 seconds of somethign) that removes the extensions from the files you want on the drop folder.

**Comment by diangelo84** [comment]
> > Of course, but I think it would be much easier to remove the multimedia extension from the file name.
> > Even so, thanks for the suggestion.
> 
> @diangelo84 I think you can write a cron job to run a schedule (maybe every 5 seconds of somethign) that removes the extensions from the files you want on the drop folder.

I have already tried with the scheduled tasks and it works, but every time a file is modified the name the server has to rescan the entire library, not to mention that when you export new strm duplicates will be created.
Example: we have
#SexPact (2018) [H.264-1080p] .mkv.strm
we create a task and eliminate .mkv and it would be like that.
#SexPact (2018) [H.264-1080p] .strm
what happens, that when you go to export new strm from the same folder where this film is contained, you will export it again.
#SexPact (2018) [H.264-1080p] .mkv.strm
with which we would have a duplicate of the same movie.
Anyway, I appreciate your interest. a greeting

**Comment by jaylex32** [comment]
> No, it is not causing problems, but personally I can make things much easier, since I usually use emby as a database and it works wonders, but my problem arises when having the same movie in different versions.
> Example: #SexPact (2018) [H.264-1080p] .mkv.strm
>                  #SexPact (2018) [H.265-720p] .mkv.strm
> in this case Emby creates two covers for me, one for each film.
> instead #SexPact (2018) [H.264-1080p] .strm
>                    #SexPact (2018) [H.265-720p] .strm
> it detects it as the same movie in different versions, avoiding having the cover duplicated.

how did you make the .strm work with Emby if it has the plugin path on it?
I test it and it didn't work can you elaborate how please?

**Comment by cguZZman** [comment]
fixed in latest version
