### ISSUE TITLE
Creating strm for miscellaneous files.

### ISSUE THREAD

**Issue by iorifly** [cguZZman/plugin.googledrive#65]
My ta creating strm files for files that are not mkv, mp4 ... actually does not have extension.
For example, this file  "_VUC69 ~ 7"

It would be better to filter out what kind of file it creates strm.

**Comment by cguZZman** [comment]
Need more info about the request.  What kind of files are they? Currently, export function will create strm files for media files. So, unless there is a pattern for your files, there is no way to include them into the export functionality.
If still is needed, create a new issue with all the required info.
