### ISSUE TITLE
Play movies in rar archives

### ISSUE THREAD

**Issue by JonasKress** [cguZZman/plugin.googledrive#68]
**Is your feature request related to a problem? Please describe.**
When I have a movie inside of an archive (rar) in my google drive then I would like to be able to open it and watch the movie.

**Describe the solution you'd like**
Show rar files and allow to open it and watch movies inside.

**Additional context**
Kodi allows play back of movies inside of archives.

**Comment by cguZZman** [comment]
This should be a Kodi feature. Go to Add-ons > My add-ons > Virtual Filesystems -> RAR -> Enable
