### ISSUE TITLE
Cannot change audio track

### ISSUE THREAD

**Issue by darshitpp** [cguZZman/plugin.googledrive#69]
I've noticed that if the video has multiple audio tracks, I cannot change the tracks unless I choose the Video format as Original format while starting to play the video. If I select some other provided resolution like 1920x1080, it defaults to the audio track being "und" which I presume means "undefined".

Any workaround to fix this?

**Comment by ryanjerskine** [comment]
This isn't a bug. Each resolution is it's own 'encoded' video/audio. When you upload a video to Google Drive, it encodes a 1080p/720p/480p/360p each with their own 2.0 channel audio track. The only way to "fix" this would to somehow be to pull the video from the 1080p mp4 file and mux the audio from the original back in. That's probably technically possible but it would be incredibly difficult in my opinion.

**Comment by manishrawat4u** [comment]
Does google stores the multiple audio tracks in multiple streams like 1080p/720p/480p etc? I wouldn't able to figure out how to retrieve the audio back from these tracks either

**Comment by ryanjerskine** [comment]
It creates entirely new mp4 files for each of those qualities. So you really end up with 4 entirely new mp4 files with their own audio/video. You would essentially have to mux them on the fly. No idea how feasible that is but it certainly doesn't seem simple.

**Comment by darshitpp** [comment]
Ah, it's ok. I really like the add-on btw! :) Thanks for the effort!

**Comment by cguZZman** [comment]
Closing this issue since is out of the scope of the addon.
