### ISSUE TITLE
Search by context menu returns 0 results

### ISSUE THREAD

**Issue by aspgh** [cguZZman/plugin.googledrive#71]
Though I can click on the folders and sub folders to see their contents, when I try to search for files from the topmost folder (or any sub folder) using the context menu, the search result is always 0, even though the text I input is surely to be found in some of the the file names inside the folder.

1. Open the Google Drive account folder.
2. Right click on any of the folders in the account (inside 'My Drive') to open the Context Menu.
3. Click 'Search...'
4. Input a text that you are sure to find in the file/folder names contained in the folder being searched.
5. The search results would be empty.

**Comment by cguZZman** [comment]
Please post your debug log file.

**Comment by vedant360** [comment]
Search function is also not working for me @cguZZman  are you facing this issue?

**Comment by cmarcosp78** [comment]
Search function is not working. Are you working on a solution?

Regards

**Comment by pekul** [comment]
Search function is not even working with Normal Search (Kodi v18.5 Stable, Estouchy/Estuary skin, left menu) or Context Search.

P/S: GG Drive addon v1.3.1

**Comment by cguZZman** [comment]
don't see anybody posting a debug log file

**Comment by aspgh** [comment]
For us who find it too complicated, maybe it would be faster if you try it out; if this bug occurs with your system as well, then you can get to the debug file much easier than we can. Thanks.

**Comment by cguZZman** [comment]
Fixed in the latest version. You can get it from my repository now or wait until Kodi team publish it in the Kodi repository.
