### ISSUE TITLE
Prevent strm export from modifying existing strm files which are not edited.

### ISSUE THREAD

**Issue by KinjigMedia** [cguZZman/plugin.googledrive#73]
My feature request is a little complicated so I have tried to break it down.

**Google Drive**
I have three folders in my account: _TV Shows_, _Movies_ and _Streams_.

**Computer Files**
I have a folder called _Streams_ on my Macbook. It syncs with the _Streams_ folder on Google Drive (using Google's Backup and Sync for Mac).

**Kodi**
Through your Google Drive add-on, I periodically export the _TV Shows_ and _Movies_ folders as .strm files. The location for both of these exports is in my computer's _Streams_ folder. 

**Request**
I would like for the add-on's strm export to only modify files which have been changed or added on Google Drive. Currently, the add-on goes through every file and "modifies" it, even though no edits are made to the text in the .strm file. Unfortunately, this means that when Backup & Sync syncs both the cloud and computer _Streams_ folders, it goes through and syncs every file in the _TV Shows_ and _Movies_ folders (thousands of files)... It should only recognize the newly added or actually edited .strm files.

For example: in kodi I export _TV Shows_, where a new show (e.g. The Sopranos) has .strm files created (let's say May 16 2019). When I export TV Shows once again on May 20th 2019, all of the episode files of The Sopranos will be "modified" on that date even though no changes will be made to the .strm file text and the original episode files are unchanged. Backup & Sync will think that changes were made to these files and will resync them. This happens for hundreds of shows :(

Please let me know if a solution is possible, or if there is a workaround I haven't considered. Thanks!

**Comment by cguZZman** [comment]
Use the "watch folder" option, it will export modified files only.
