### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by AlexGit74** [cguZZman/plugin.googledrive#74]
Hi there!
I am a bit concerned about security policies.
I have had issues on my Raspberry due to my negligence in forwarding a port for ssh testing that I was doing and I could have been owned, so now I have reinstalled the system (OSMC) and resumed previous .kodi settings from BackUp.
I am just wondering if any malicious script could have stolen access to my GoogleDrive using personal data or access token stored in your plugin... What should I do to check if this has occured and repair problems?

Thanks for any advice!

**Comment by cguZZman** [comment]
What you have to do is to revoke access to the addon from your google account settings. Once you do that, you will get a message from the addon saying the credentials are no longer valid, then you can login again with the addon and a new set of credentials will be granted.
