### ISSUE TITLE
Add Check mark for watched shows

### ISSUE THREAD

**Issue by 1Big8Poppa7** [cguZZman/plugin.googledrive#75]
would be awesome to see a check mark on each show that's been marked as watched rather then having so click on each file one by one. Not easy when your watching full seasons

**Comment by raycekar** [comment]
I think this is already a Kodi thing, unless your referring to use it across devices, then Just use Trakt

**Comment by 1Big8Poppa7** [comment]
1st off Thanks for answering I love your plugin. I do not use Kodi on cross devices. I recently decided to completely start my Kodi setup over cuz of so many old repos etc.. Anyway I have always used this old GDrive plugin by ddurdle: https://github.com/ddurdle/GDrive-for-KODI
It shows a little check mark on each video I have watched, But I found it a total pain to add accounts. Your method is so much more user friendly. I can deal with not seeing a check mark just wanted to see if it was possible. Thanks 🤙🏼

**Comment by raycekar** [comment]
ok, so I think I know what your referring to and that is in fact built into Kodi, press the c button (using keyboard), or whatever key it is to get the submenu up while you have a video selected, and click the Marked Watch button and the check mark should show up... and I didn't make this add-on 😋 I just use and love it
