### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by JorgeVasquezF** [cguZZman/plugin.googledrive#76]
No JSON object could be decoded
Please try again.

**Your debug log file**

[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/3463570/kodi.log)

**Comment by cguZZman** [comment]
Hi, thanks for your report. This is a known error.
I've been very busy these days. Lot of work. If somebody want to help fixing issues, feel free to send PRs.

**Comment by Buzzmovies** [comment]
Hello,

Sorry to reopen this but I started getting this error for the first time.

Since the changed to the API, I am no longer going the "SOURCE" route. Now using the STRM route. Was ok for a couple of hours but now I get that error message no matter what I do. Was this ever fixed? If there a way to work around that?

Thank you.

**Comment by cguZZman** [comment]
Just go to your kodi installation folder and delete the accounts.cfg file. 
This is the path: `\Kodi\userdata\addon_data\plugin.googledrive\accounts.cfg`

It will delete your registered accounts, but you can add them again and the issue will be fixed.

**Comment by cguZZman** [comment]
fixed in last version

**Comment by odell2000** [comment]
Hola, pues de nuevo el erro de json, ¿la única solución es borrar el archivo de la cuenta cfg y volver a instalar el addon y escanear todo?

**Comment by cguZZman** [comment]
the solution is to update the addon to the latest version.

**Comment by odell2000** [comment]
What is the last version?

**Comment by cguZZman** [comment]
1.4.6 as of now

**Comment by odell2000** [comment]
Where i can find it?

**Comment by cguZZman** [comment]
Follow the instructions here: https://github.com/cguZZman/repository.plugins

**Comment by odell2000** [comment]
Thanks, now works again.
