### ISSUE TITLE
GPhotos no longer syncs with GDrive workaround

### ISSUE THREAD

**Issue by raycekar** [cguZZman/plugin.googledrive#79]
So I am trying to work on a solution to the google drive and google photos split on being able to export (strm export) your media from google drive using this tool but the media is only stored in your google photos as the Google Photos Folder no longer works in Drive.  

My idea and where I am at so far:

- [X] Interface with photos and obtain a full list with id's, file names, and other info (using google scripts and Google Photos API)

- [ ] Create strm files (or google docs as its free storage) from  list and store in google drive (to use google scripts)

- [ ] update this tool for if it sees the extension ".strm" (or some other extension in the file name aka. future proofing google doc naming) to download its contents and store it in a strm file instead of pulling the item id

As you can see I have step one pretty much done, but before I continue, I want to figure out how to get the available resolutions from these video as I don't believe the current implemented solution will work ie. [drive.google.com/get_video_info](https://github.com/cguZZman/plugin.googledrive/blob/master/addon.py#L96).

If anyone has any other idea's, I am open to hear them, so let me know. 

EDIT:
Also, one other Idea I had was skipping the strm creation in google drive and if you have a google sheet with names and id's with maybe a preferred location (to spit diff media up if desired), just having this tool go and parse that and create the strm files as well.  But still have the issue of "get_video_info".

**Comment by cguZZman** [comment]
I'm trying to understand the issue here.
From the addon perspective, Google Photos has been always in a different API. I just test it and is still working within the addon (Picture Add-ons -> Google Drive -> Google Photos).
Can you give me more info?

**Comment by AchEgal** [comment]
Perhaps this error is the same as mine: "Google Photos Folder no longer works in Drive"

I can confirm that photos don't work for me too. Don't know what raycekar means with "syncing".

I would say it is syncing because I can see all my folders an picture names. Only thumbnail and pictures don't load.

**Comment by raycekar** [comment]
Aw ok, I thought the way the addon interacted with google photos was using the google photos folder setting that you enable through the google drive settings.  So I thought with [This URL](https://gsuiteupdates.googleblog.com/2019/06/google-photos-drive-sync-stopping.html) that that feature was now broken (as i didn't use the other method that you stated (Picture Add-ons -> Google Drive -> Google Photos).

@AchEgal I just tried the route that @cguZZman stated and would agree that albums show up but no media.

@cguZZman the way I talked about above was an idea I had, by constructing the strm files in google drive using google scripts and google photos api.  I figured this way, you can organize the strm file and then the google drive addon could see it was an strm file and simply download it to your device (ie the strm export method).

**Comment by cguZZman** [comment]
I'll take a look on why photos are not showing up.
That google change won't affect the addon. We are using the new API since day one.
