### ISSUE TITLE
Shared Drive not working after scanning

### ISSUE THREAD

**Issue by VoxRatio** [cguZZman/plugin.googledrive#80]
**Describe the bug**
I have set up the Google Drive plugin with my shared drive, and I was able to add the source "http://localhost:8587/source/Google%20Drive/WankNinja%20Storage%20%7C%20Team%20Drive%20%7C%20Wank%20Ninja%20Storage/Movies/", and it worked. I then scanned the directory to my library, and that is where the issue starts. The directory is no longer accessible.

**To Reproduce**
1. Add "Movies" on team directory as a source
2. "Change Content: Do you want to refresh information for all items in this path?" Click yes.
3. Let the scan finish.
4. Now, whenever you try to play a movie, it won't load.
5. Go to Media Settings > Library > Videos, and select the source. It now has a popup that says "Remote Share: Path not found or invalid".
6. Go to "http://localhost:8587/source/Google%20Drive/WankNinja%20Storage%20%7C%20Team%20Drive%20%7C%20Wank%20Ninja%20Storage/Movies/", you will be presented with an error similar to this

`Traceback (most recent call last): File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 351, in do_GET cached_page = self.handle_resource_request(data) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 310, in handle_resource_request cached_page = self.process_path(addon_name, drive_name, path) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 199, in process_path response.write(str(self.show_folder(driveid, path))) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 234, in show_folder items = self.get_folder_items(driveid, path) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 214, in get_folder_items items = provider.get_folder_items(path=request_path, include_download_info=True) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.googledrive\resources\lib\provider\googledrive.py", line 125, in get_folder_items item = self.get_item_by_path(path, include_download_info) File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.googledrive\resources\lib\provider\googledrive.py", line 316, in get_item_by_path raise RequestException('Not found by path', HTTPError(path, 404, 'Not found', None, None), 'Request URL: %s' % path, None) RequestException: Not found by path Root cause: None`

**Your debug log file**
https://pastebin.com/nY69jF0Q

**Comment by Animizio** [comment]
I got this problem too now with a teamdrive. I can add and scan files, but after it's finished, I can't play the files in my library or at least open the source folder.

**Comment by cguZZman** [comment]
Can you guys test it with a normal drive? to check if this is an issue only with team drives.
