### ISSUE TITLE
Add stream quality selection in source mode

### ISSUE THREAD

**Issue by jmiskinis** [cguZZman/plugin.googledrive#84]
**Is your feature request related to a problem? Please describe.**

When Google Drive is added as source, stream quality popup does not show up. Videos are played in their original quality. That's not desirable when playing high bit rate videos on a slow connection.

**Describe the solution you'd like**
Clicking on a video in source mode should present a popup window listing stream quality options.

**Describe alternatives you've considered**
Currently, one has to export the library as .strm files to enable this functionality which, in my mind, is not as convenient as using the source mode.

**Additional context**
Does Kodi framework even allow this? If yes, is it difficult to implement it?

**Comment by GhyslainBruno** [comment]
Would definitely be an amazing feature ! (using Google's servers to achieve quite the same result as Plex Cloud did...)

Could you please describe how you achieve to do this right now using .strm files ? I would love to try this out.

**Comment by cboswald95** [comment]
> Would definitely be an amazing feature ! (using Google's servers to achieve quite the same result as Plex Cloud did...)
> 
> Could you please describe how you achieve to do this right now using .strm files ? I would love to try this out.

in the add-on settings you can select: "always ask for stream quality", which will set a prompt to choose original quality, 1080p, 720p, etc every time you select a .strm file.  It's a nice feature but a bit clunky since you can't set a preferred/default quality

**Comment by vaccarieli** [comment]
This feature is awesome, but won't let me select the audio nor the subs, is there a way to fix this ?

**Comment by cguZZman** [comment]
Not possible to select audio or subs when changing the quality. Make a search in the issues for explanation.
