### ISSUE TITLE
Code is Invalid

### ISSUE THREAD

**Issue by freqzt** [cguZZman/plugin.googledrive#88]
**Describe the bug**
Cannot login to google drive. When input the code, it said the code is invalid. I have tried many times but still no result.

**To Reproduce**
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by cguZZman** [comment]
I need more information than that. Please upload your debug log file and screenshot of your login page with the error. I will close this and reopened once everything is completed
