### ISSUE TITLE
Time out with folders with many files

### ISSUE THREAD

**Issue by Sirfrancis17** [cguZZman/plugin.googledrive#90]
Hi
I try  select folder as a source but the movie folder contains more than 5000 files.
When i click the folder the Addons do nothing.
This same problem happen with series folder (1000 folders) but 5 o more click in this folder and worked
Is it possible that there is a problem with the response time?

**Comment by cguZZman** [comment]
No way to know it unless you post your debug log file. I'll close this untill you complete all the required information.

**Comment by Sirfrancis17** [comment]
I leave the log


> No way to know it unless you post your debug log file. I'll close this untill you complete all the required information.
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/3923268/kodi.log)

I leave a log

**Comment by cguZZman** [comment]
The debug mode was not enabled for the log. Enable the debug mode and then try again.

**Comment by Sirfrancis17** [comment]
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/3923724/kodi.log)

**Comment by cguZZman** [comment]
Your drive is returning 404, which means folder not found (/Peliculas).

Let's try again but before clean the cache (addon settings > Advanced > Clear cache now)
Then try again and send me the debug log.

**Comment by Sirfrancis17** [comment]
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/3923842/kodi.log)
![Screenshot_20191204-214014_Kodi](https://user-images.githubusercontent.com/44566906/70179753-eb08e180-16de-11ea-95ce-07fc929e5896.png)
