### ISSUE TITLE
recognizing .nomedia files.

### ISSUE THREAD

**Issue by hackmonker** [cguZZman/plugin.googledrive#91]
**Is your feature request related to a problem? Please describe.**

My bluray rips has extras along with the movies. I keep the extras in a separate folder called extras in side the movies folder . I then put a `.nomedia`  extension on a blank text file so that kodi does not scrape it into my main library. In kodi I use extras addon to watch the addons when I want to.
```
Movie\ Movie.mp4
     \ Extras\ extra 1.mp4
             \ trailer.mp4
             \ .nomedia

```
Now this structure is present in my gdrive too. Now comes my problem with the addon. When I export my library, the `.nomedia` file does not come. This causes my kodi to scan the extras as different movies named extra 1, extra 2 completely messing up my library.

Now even if I create a `.nomedia` file inside the extra folder locally, the next export removes the file since the gdrive plugin does not recognize it. And my library is again a mess. 

**Describe the solution you'd like**

The addon can recognize the `.nomedia` files and download them along with the strm filles or it can ignore the files having such extention in the library and not delete them or some other method to keep a `.nomedia` file in the extras folder.

 If this feature is possible I would be highly grateful if you can implement it. Anyway really love your addon and keep up the good work.

**Comment by cguZZman** [comment]
fixed in last version
