### ISSUE TITLE
Gdrive changes

### ISSUE THREAD

**Issue by asw13537** [cguZZman/plugin.googledrive#92]
With the changes to Gdrive API will the gdrive add-on need to be updated to continue to work?

https://www.google.com/amp/s/cloudblog.withgoogle.com/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api/amp/

**Comment by cguZZman** [comment]
Yes, it need to be updated. I'm working on that.

**Comment by Solwayuk** [comment]
> 
> 
> Yes, it need to be updated. I'm working on that.

Any luck on this? all videos streaming from Gdrive have stopped working due to API changes

**Comment by gsantosoliver** [comment]
I am also facing the same problem

**Comment by cguZZman** [comment]
Will try to have the fix ready this weekend. I will let you guys know when it's done.

**Comment by zeppelin33** [comment]
Awesome. In the meantime can someone explain how to select a different stream format other than the orginal?

**Comment by BSeller** [comment]
Thank you very much for trying to resolve

**Comment by zeppelin33** [comment]
Thanks for the advise cguzman
Go to Gdrive - settings - add on settings - then enable prompt to select stream format before playing

**Comment by zeppelin33** [comment]
Thanks for the advise cguzman
Gdrive - settings - add on settings - enable prompt to select stream format before playing

**Comment by JuenTingShie** [comment]
Wait for resolving,

**Comment by BSeller** [comment]
> Wait for resolving,

Thanks for the advise cguzman
Gdrive - settings - add on settings - enable prompt to select stream format before playing

**Comment by cguZZman** [comment]
Fix is ready. You can get it now from my repo https://github.com/cguZZman/repository.plugins
I will submit it to the Kodi repo in the next few days.

**Comment by cguZZman** [comment]
And some bad news for those who use the source mode to play videos. Due to the change made by google, this mode is no longer possible. I'm trying to find a solution, but it does not look good.

**Comment by I-MacHunt** [comment]
I have just updated to the latest version and fingers crossed, it appears to be working perfectly!! Thank you so much for that, I was afraid I was going to have to outside and get a life!! 😱😱;-)

**Comment by 4ld3v** [comment]
hello @cguZZman , First off, I want to thank you for your google drive addon! 

Regarding the gdrive as a source not working, can you confirm that this will not work anymore? Whats the reason, whats missing now?

**Comment by I-MacHunt** [comment]
> hello @cguZZman , First off, I want to thank you for your google drive addon!
> 
> Regarding the gdrive as a source not working, can you confirm that this will not work anymore? Whats the reason, whats missing now?

It's working perfectly for me at the moment.

**Comment by 4ld3v** [comment]
> > hello @cguZZman , First off, I want to thank you for your google drive addon!
> > Regarding the gdrive as a source not working, can you confirm that this will not work anymore? Whats the reason, whats missing now?
> 
> It's working perfectly for me at the moment.

Hi there, now thats a little surprising. I see alot of mentionings that the ability to add gdrive as a web source, to scan & scrape and add to library and all that stuff, this is not working anymore. All I saw by @cguZZman  so far is, responding that it doesnt seem this will ever work again.
I have tested this on 2 different devices with fresh installations of kodi the addons from repos but then again from the git source also, still it does not work for me.
Did you do anything to the code or anything that is different than the regular installation?

**Comment by I-MacHunt** [comment]
> > > hello @cguZZman , First off, I want to thank you for your google drive addon!
> > > Regarding the gdrive as a source not working, can you confirm that this will not work anymore? Whats the reason, whats missing now?
> > 
> > 
> > It's working perfectly for me at the moment.
> 
> Hi there, now thats a little surprising. I see alot of mentionings that the ability to add gdrive as a web source, to scan & scrape and add to library and all that stuff, this is not working anymore. All I saw by @cguZZman so far is, responding that it doesnt seem this will ever work again.
> I have tested this on 2 different devices with fresh installations of kodi the addons from repos but then again from the git source also, still it does not work for me.
> Did you do anything to the code or anything that is different than the regular installation?

I'll be honest but I'm no expert on this but I can stream all of my video files from Google Drive via Kodi on my Nvidia Shield and the library updates automatically when new files are added (now that I've fixed that setting!!🤦‍♂️)

**Comment by cguZZman** [comment]
May be @I-MacHunt is using strm files? beacause source mode is not working as of now. You can paste your debug log file to see what your are using.

I found a possible solution to get it working again using the transcode url, but subtitles won't work. They may need to be downloaded or something to get it working. Still working on that part.
Anyway, there is hope for it. No ETA tho.
Just out of curiosity, why do you prefer source mode over .strm files?

**Comment by I-MacHunt** [comment]
> May be @I-MacHunt is using strm files? beacause source mode is not working as of now. You can paste your debug log file to see what your are using.
> 
> I found a possible solution to get it working again using the transcode url, but subtitles won't work. They may need to be downloaded or something to get it working. Still working on that part.
> Anyway, there is hope for it. No ETA tho.
> Just out of curiosity, why do you prefer source mode over .strm files?

Yes, I am using .strm files.
