### ISSUE TITLE
Google Photos - Can't watch my videos

### ISSUE THREAD

**Issue by macamba** [cguZZman/plugin.googledrive#93]
Hi all, 

All work perfectly except an obvious detail, Google Photos is to store photos and videos but from section kodi picture I can't play any video only see photos so please, is it possible to add also the folder google photos to section kodi videos of this way I'm sure we could play our videos uploaded in Google Photos

So many thanks for the addon
Regards

**Comment by cguZZman** [comment]
This is a known issue. It's an enhancement already in the list: #40
