### ISSUE TITLE
Export strm option gets stuck indefinitely 

### ISSUE THREAD

**Issue by medstudent12** [cguZZman/plugin.googledrive#94]
**Describe the bug**
Exporting a large team drive strm
**To Reproduce**
1. Go to 'a teamdrive'
2. Click on 'right click on media'
3. Scroll down to 'export strm'
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

https://paste.kodi.tv/qamiqiyura.kodi

**Screenshots**
![image](https://user-images.githubusercontent.com/59299701/72553990-a797ba80-38bb-11ea-8148-cff25a13563d.png)

stuck like this

**Comment by cguZZman** [comment]
You are getting an "HTTP Error 401: Unauthorized" error, and I don't see any export configuration in the export map.
Can you detail more on your steps. How did you add the export folder, how did you run it, etc.

**Comment by medstudent12** [comment]
so I'll run it again. Basically I click on addon 
then it gives me an option to chose teamdrives

![image](https://user-images.githubusercontent.com/59299701/72578808-0596c300-38f9-11ea-9dbf-dfe66529b8ce.png)

I click on one

![image](https://user-images.githubusercontent.com/59299701/72578819-10e9ee80-38f9-11ea-89d9-b5bbaad0cce3.png)


get this

click on my drive get this

![image](https://user-images.githubusercontent.com/59299701/72578891-4d1d4f00-38f9-11ea-91c5-08bb24cbff59.png)

use these settings 

![image](https://user-images.githubusercontent.com/59299701/72578915-59091100-38f9-11ea-8fba-a1918f076fbb.png)

**Comment by medstudent12** [comment]
restarted kodi
got stuck again this time got this error

![image](https://user-images.githubusercontent.com/59299701/72582012-2ebc5100-3903-11ea-92cc-85a53ad1d9f6.png)

https://paste.kodi.tv/sawigehudo.kodi

reauth and will keep you in the loop

**Comment by cguZZman** [comment]
It's weird. But I think I can put a workaround in the addon by refreshing the tokens automatically. I'll mark this a bug. Thanks for your report.

**Comment by medstudent12** [comment]
Thank you for your extremely quick replies!

**Comment by cguZZman** [comment]
Should be fixed with last version 1.3.5.
Make sure your common cloud drive module is updated also to 1.2.14
