### ISSUE TITLE
can not scan library the addon crashes

### ISSUE THREAD

**Issue by medstudent12** [cguZZman/plugin.googledrive#95]
**Describe the bug**
If I try to add a large teamdrive to kodi and ask it to scan my tv shows in it eventually crashes the access using the localhost url
http://localhost:8587/source/Google%20Drive/Mun%20Hus%20%7C%20Team%20Drive%20%7C%20data/Media/

`Traceback (most recent call last): File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 351, in do_GET cached_page = self.handle_resource_request(data) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 310, in handle_resource_request cached_page = self.process_path(addon_name, drive_name, path) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 199, in process_path response.write(str(self.show_folder(driveid, path))) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 234, in show_folder items = self.get_folder_items(driveid, path) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\service\source.py", line 214, in get_folder_items items = provider.get_folder_items(path=request_path, include_download_info=True) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\plugin.googledrive\resources\lib\provider\googledrive.py", line 125, in get_folder_items item = self.get_item_by_path(path, include_download_info) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\plugin.googledrive\resources\lib\provider\googledrive.py", line 308, in get_item_by_path files = self.get('/files', parameters = parameters) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\oauth2.py", line 102, in get return self.request('get', path, **kwargs) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\oauth2.py", line 99, in request return Request(url, data, headers, **request_params).request_json() File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 169, in request_json return json.loads(Utils.default(self.request(), self._DEFAULT_RESPONSE)) File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 148, in request raise rex RequestException: HTTP Error 403: Forbidden Root cause: Traceback (most recent call last): File "C:\Users\Muneeb\AppData\Roaming\Kodi\addons\script.module.clouddrive.common\clouddrive\common\remote\request.py", line 117, in request response = urllib2.urlopen(req) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 435, in open response = meth(req, response) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 548, in http_response 'http', request, response, code, msg, hdrs) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 473, in error return self._call_chain(*args) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain result = func(*args) File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 556, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 403: Forbidden`

**To Reproduce**
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.
https://paste.kodi.tv/ajevamokif.kodi

**Screenshots**

![image](https://user-images.githubusercontent.com/59299701/72609017-c5a9fd00-3945-11ea-97ca-cf65e6559a38.png)

``

eventually it says download source not available

**Comment by cguZZman** [comment]
You are getting a 403 error. Which mean a temporary ban from google. This usually happens if you are sharing your team drive or doing multiple requests in a short period of time. Wait for a day at least and try again.
There is nothing the addon can do for this error. Just try to avoid the mentioned scenarios.

**Comment by medstudent12** [comment]
ok thank you for explaining this. though I am not sharing this its a large library being scanned for the first time and I was trying to generate strms before it. it could explain the ban for too many requests
