### ISSUE TITLE
STRM file not created automatically with "Watch for changes"

### ISSUE THREAD

**Issue by blackjack32** [cguZZman/plugin.googledrive#97]
**Describe the bug**
When a new video is added to the watched folder, the strm file corresponding to the new video file is not created automatically. Yet, a new empty folder with the correct name is created. However, if I change the filename of the new video, then a new strm file is properly generated. I was wondering if this might be a bug or there might be a setting I'm missing?

**To Reproduce**
1. Create new strm export on folder with "watch for changes" option ticked then saved and ran.
2. Add new folder with video file to said folder.
3. An new empty folder with the right name is created without the strm file.
4. Rename the original new video file.
5. The new video strm file is generated accordingly.

**Comment by gsantosoliver** [comment]
This problem happens a lot of times here - which requires me to run the export to .strm manually OR add a temp file to the movie folder.

Another problem, which may be related, is that when I add a new content to the Google Drive it takes forever for the entire folder to be identified as new and create the folder and the associated .strm files...

**Comment by tctfox** [comment]
yes I have this bug too. This basically makes the addon useless for me as I cant rescan my whole library all the time, it simply takes too long. Also the only library I ever succeeded exporting to srtm was my 4k library wich is way smaller than my normal movies library. with the normal one I get all kind of errors wich interrupt the export

**Comment by ckcr4lyf** [comment]
Is there a solution? How can I force it to check for new mkv files in my google drive and accordingly add srtm files?

**Comment by 4luk** [comment]
When I add a movie in a folder (google/movies/big buck bunny 2010/big buck bunny 2010.mkv) in the watched directory I have this issue of it creating a folder but no strm file inside, but when a mkv file is uploaded straight to the watched movie folder (google/movies/big buck bunny 2010.mkv) it creates a strm file for the movie.
This is a fresh install today with kodi 18.7 windows 10 x64
Your app version 1.3.6

Do I need to change some settings? 
Thank

**Comment by cguZZman** [comment]
fixed in last version
