### ISSUE TITLE
Uninstall Dependencies left behind

### ISSUE THREAD

**Issue by disgrace2029** [cguZZman/plugin.googledrive#98]
When uninstalling Google Drive these dependencies are left behind and when reinstalling it gives an error when trying to access Google Drive. Not sure if Kodi is not uninstalling all or if its a Google Drive thing.
**These are the dependencies:**
Cloud Drive
pythin-dateutil
pyQRcode

**Comment by cguZZman** [comment]
This would be a Kodi issue. 
Will test it later, but this is unrelated to the addon as far as I can see.
