### ISSUE TITLE
failed to play videos with original format 

### ISSUE THREAD

**Issue by nasmizi** [cguZZman/plugin.googledrive#99]
failed to play videos with original format but want i enable " always ask for the stream format before play ". Working play videos using another format  but without subtitle . Before this, i get no problem. Please fix

**Comment by vicnsol** [comment]
I am having the same issue, can't load videos since Yesterday  
V1.2.12
Kodi 18.5

**Comment by brunosaragiotto** [comment]
He already working in a fix:
https://github.com/cguZZman/plugin.googledrive/issues/92

**Comment by cguZZman** [comment]
Fix is ready. You can get it now from my repo https://github.com/cguZZman/repository.plugins
I will submit it to the Kodi repo in the next few days.
Read more details on #92

**Comment by nasmizi** [comment]
Thanks  cguzman

**Comment by karasawa-mido** [comment]
Thank you so much!
